[project]
name = "NExtSEEK"
version = "1.3.0"
description = "Extending SEEK for active management of scientific metadata"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "annotated-types",
  "asgiref",
  "attrs",
  "beautifulsoup4",
  "bleach",
  #"bunch",
  "certifi",
  "celery",
  "chardet",
  "charset-normalizer",
  "deepmerge",
  "dj-rest-auth",
  "Django",
  "django-contrib-comments",
  "django-cors-headers",
  "django-cprofile-middleware",
  "django-crontab",
  "django-filebrowser-no-grappelli",
  "django-markdownify",
  "django-realtime",
  "django-rest-framework",
  "django-widget-tweaks",
  "djangorestframework",
  "djangorestframework_simplejwt",
  "drf-spectacular",
  "drf-spectacular-sidecar",
  "duckdb",
  "et_xmlfile",
  "filebrowser-safe",
  "filelock",
  "fpdf",
  "fsspec",
  "future",
  "grappelli-safe",
  "gunicorn",
  "h5py",
  "hf-xet",
  "html5lib",
  "huggingface-hub",
  "idna",
  #"immpload",
  "importlib_metadata",
  "inflection",
  "isodate",
  "jdcal",
  "Jinja2",
  "joblib",
  "jsonref",
  "jsonschema",
  "jsonschema-specifications",
  "lxml",
  "Markdown",
  "MarkupSafe",
  "Mezzanine",
  "mpmath",
  "mysql-connector-python",
  "mysqlclient",
  "neo4j",
  "networkx",
  "numpy",
  "oauthlib",
  "olefile",
  "openpyxl",
  "packaging",
  "pandas",
  "parse",
  "pathlib",
  "polars",
  "pillow",
  "psutil",
  "pydantic",
  "pydantic_core",
  "PyJWT",
  "PyMySQL",
  "pyparsing",
  #"python-dateutil.post0",
  "python-docx",
  "pytz",
  "PyYAML",
  "rdflib",
  "referencing",
  "reportlab",
  "requests",
  "requests-oauthlib",
  "rpds-py",
  "ruff",
  "scipy",
  "simplejson",
  "six",
  "soupsieve",
  "SPARQLWrapper",
  "sentence-transformers",
  "sqlparse",
  "sqlalchemy",
  "sympy",
  "threadpoolctl",
  "tinycss2",
  "tokenizers",
  # "#torch+cpu",
  "tqdm",
  "typing-inspection",
  "typing_extensions",
  "tzdata",
  "tzlocal",
  "Unidecode",
  "uritemplate",
  "urllib3",
  "webencodings",
  "xlwt",
  "zipp",
  "chat_nextseek",
  "pytest-django",
]

[tool.uv.sources]
chat_nextseek = { path = "./chat_nextseek" }

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "dmac.settings"
