-- Curated context for SEEK projects and investigations: who runs one, what it
-- studies, where it is published. Generated from context/projects.json by
-- scripts/context_gen.py --emit seed; regenerate rather than hand-editing.
--
-- HELD: no install step reads this file until the curated content is signed off
-- (scripts/README.md group C).
--
-- Read by the project page header; every field is optional and the header falls
-- back to the SEEK title and description when the row is absent. The lookup is
-- `SELECT * FROM projects_context WHERE project_id = %s`
-- (nextseek_api/services/context_catalog.py), keyed on the SEEK project id and
-- with no fallback by name. The project_id values below are PRODUCTION's SEEK
-- ids. The committed seek seed carries exactly one project, `Published Data` at
-- id 1, so on a fresh install every row here matches no project and the header
-- falls back -- and on any stack whose SEEK projects were created in a different
-- order, a row renders against whichever project happens to hold that id. Check
-- the ids against the target stack's `projects` table before relying on them.
--
-- alternative_names and key_data_types are JSON arrays stored as text, matching
-- how chat_nextseek's map_project already reads them: it json.loads the value and
-- falls back to splitting on '|'. pi is display prose; nothing parses it.
--
-- pi, nih_reporter_link and fairdomhub_published_link are TEXT, which is what the
-- live column is in all three cases; a curated pi is longer than VARCHAR(255).
SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS projects_context (
  id                        INT AUTO_INCREMENT PRIMARY KEY,
  name                      VARCHAR(255) NULL,
  alternative_names         TEXT         NULL,
  entity_type               VARCHAR(64)  NULL,
  project_id                INT          NULL,
  parent_project            VARCHAR(255) NULL,
  pi                        TEXT         NULL,
  research_focus            TEXT         NULL,
  key_data_types            TEXT         NULL,
  description               TEXT         NULL,
  nih_reporter_link         TEXT         NULL,
  fairdomhub_published_link TEXT         NULL,
  tags                      TEXT         NULL,
  KEY idx_project_id (project_id),
  UNIQUE KEY `uq_projects_context_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `projects_context` (`name`, `alternative_names`, `entity_type`, `project_id`, `parent_project`, `pi`, `research_focus`, `key_data_types`, `description`, `nih_reporter_link`, `fairdomhub_published_link`, `tags`) VALUES ('BPRC', '["Biomedical Primate Research Centre", "Biomedical Primate Research Center"]', 'project', 15, NULL, NULL, 'Non-human primate models of tuberculosis; testing of BCG and new tuberculosis vaccine and therapy candidates in macaques', '[]', 'The Biomedical Primate Research Centre (BPRC) in Rijswijk, the Netherlands, is a not-for-profit research institute that works with non-human primate models. Its tuberculosis research uses macaques to test new tuberculosis vaccines and treatments against the current BCG vaccine, measuring safety, immune responses and protection. Its macaque tuberculosis work is related to the IMPAcTb program.', NULL, NULL, 'BPRC, Biomedical Primate Research Centre, Rijswijk, macaque, rhesus macaque, non-human primate, NHP, tuberculosis, TB, BCG, vaccine');
INSERT INTO `projects_context` (`name`, `alternative_names`, `entity_type`, `project_id`, `parent_project`, `pi`, `research_focus`, `key_data_types`, `description`, `nih_reporter_link`, `fairdomhub_published_link`, `tags`) VALUES ('Break Through Cancer', '["BTC", "Breakthrough Cancer", "Breakthrough_Cancer", "GBM_BTC", "BTC-GBM", "Serial Biopsies TeamLab"]', 'project', 9, NULL, NULL, 'Recurrent glioblastoma; serial brain biopsies to test whether a therapy reaches the tumor and acts on target; single-cell, proteomic, immunopeptidomic and spatial profiling; cerebrospinal fluid and blood as surrogate markers of drug activity', '["Spatial transcriptomics, proteomics and metabolomics", "Short- and long-read DNA sequencing with copy number analysis", "Mass spectrometry proteomics, phosphoproteomics and immunopeptidomics", "MRI, histopathology and slide imaging", "Glioblastoma patient tumor tissue", "Clinical oncopanel and proximity extension assays", "Cyclic immunofluorescence (CyCIF)"]', 'Break Through Cancer''s glioblastoma TeamLab, ''Accelerating GBM Therapies Through Serial Biopsies'', is a foundation-funded collaboration of Dana-Farber, Brigham and Women''s, Johns Hopkins, Memorial Sloan Kettering, MD Anderson and MIT''s Koch Institute. The team takes repeated (serial) biopsies from the same glioblastoma patients to learn whether a therapy reaches the tumor and has its intended effect, and tests whether cerebrospinal fluid and blood can serve as surrogate markers. Tumor samples are profiled with sequencing, proteomics, imaging and spatial methods. It is separate from CSBC, the NCI-funded glioblastoma center at MIT and Dana-Farber.', NULL, NULL, 'Break Through Cancer, BTC, GBM, glioblastoma, recurrent glioblastoma, serial biopsy, TeamLab, Dana-Farber, DFCI, Koch Institute, CAN-3110, oncolytic virus, spatial transcriptomics');
INSERT INTO `projects_context` (`name`, `alternative_names`, `entity_type`, `project_id`, `parent_project`, `pi`, `research_focus`, `key_data_types`, `description`, `nih_reporter_link`, `fairdomhub_published_link`, `tags`) VALUES ('CSBC', '["Cancer Systems Biology Consortium", "Center for Systems Biology of Glioblastoma", "MIT/DFCI CSBC"]', 'project', 10, NULL, 'White, Forest M. (MIT, contact PI); Michor, Franziska (Dana-Farber, co-PI)', 'Quantitative systems biology of glioblastoma; tumor-neural-immune interactions in the GBM microenvironment; integrated computational and multi-scale modeling to identify therapeutic strategies', '["Mass spectrometry proteomics and phosphoproteomics", "Mass spectrometry imaging (MALDI-MSI)", "Patient tumor tissue and biopsies", "Mouse and patient-derived xenograft (PDX) models", "Tissue sections with cyclic immunofluorescence (CyCIF) imaging", "Bulk and single-nucleus RNA sequencing", "In vitro tumor cell models"]', 'The MIT/Dana-Farber Center for Systems Biology of Glioblastoma is an NCI U54 center in the Cancer Systems Biology Consortium, led by Forest White (MIT) and Franziska Michor (Dana-Farber). It studies how neurons, immune cells and tumor cells interact in glioblastoma, and why the tumor microenvironment suppresses immune responses. The team combines patient tumor samples, mouse and patient-derived xenograft models and mass spectrometry proteomics with computational and multi-scale models to find therapeutic targets. It is separate from the Break Through Cancer glioblastoma TeamLab.', 'https://reporter.nih.gov/project-details/11420536', 'https://fairdomhub.org/projects/441', 'CSBC, Cancer Systems Biology Consortium, glioblastoma, brain tumor, Forest White, White, Forest, Michor, Dana-Farber, DFCI, NCI, U54, U54CA283114, proteomics, phosphoproteomics, MALDI-MSI, systems biology');
INSERT INTO `projects_context` (`name`, `alternative_names`, `entity_type`, `project_id`, `parent_project`, `pi`, `research_focus`, `key_data_types`, `description`, `nih_reporter_link`, `fairdomhub_published_link`, `tags`) VALUES ('Griffith', '["CGR-Endo", "CGR", "Center for Gynepathology Research", "Endometriosis"]', 'project', 7, NULL, 'Griffith, Linda G. (MIT, PI; Scientific Director, Center for Gynepathology Research); Goods, Brittany A. (University of Melbourne, partner lab)', 'Endometriosis and adenomyosis; the human endometrium across the menstrual cycle; patient-derived endometrial organoid and stromal co-cultures in synthetic hydrogels; single-cell RNA-seq and proteomic profiles of endometriosis', '["Endometrial organoids and cell co-cultures", "Organoid and cell imaging", "Single-cell and bulk sequencing", "Mass spectrometry proteomics", "Secreted protein assays (ELISA, Luminex)", "Patient endometrial tissue"]', 'Endometriosis and uterine biology research from Linda Griffith''s lab at MIT, working with Brittany Goods'' lab, and from the multi-lab Center for Gynepathology Research that Griffith directs. The work grows patient-derived endometrial organoids and stromal co-cultures in synthetic hydrogels to model the endometrium across the menstrual cycle, and profiles patient tissue with single-cell RNA sequencing and proteomics to find the molecular features of endometriosis and adenomyosis. It is funded by NIH (NICHD, and earlier NIBIB).', 'https://reporter.nih.gov/project-details/11115568', 'https://fairdomhub.org/projects/343', 'Griffith, CGR, CGR-Endo, Center for Gynepathology Research, endometriosis, adenomyosis, endometrium, menstrual cycle, organoid, synthetic hydrogel, Goods, single-cell RNA-seq, proteomics, R01HD110335, U01EB029132');
INSERT INTO `projects_context` (`name`, `alternative_names`, `entity_type`, `project_id`, `parent_project`, `pi`, `research_focus`, `key_data_types`, `description`, `nih_reporter_link`, `fairdomhub_published_link`, `tags`) VALUES ('Impact', '["IMPACT", "IMPAcTb", "Hi-IMPAcTB", "IMPAc-TB", "Fortune", "Impactb Investigation"]', 'project', 2, NULL, 'Fortune, Sarah M. (Harvard T.H. Chan School of Public Health, contact PI); Flynn, JoAnne L. (U Pittsburgh, co-lead); Boom, W. Henry (Case Western Reserve, co-lead); Bryson, Bryan (MIT, member lab); Lauffenburger, Douglas A. (MIT, member lab); Shalek, Alex K. (MIT, member lab)', 'Host-pathogen interactions in tuberculosis; characterizing protective vs. non-protective immunological responses to Mycobacterium tuberculosis to inform vaccine design', '["Flow cytometry and CyTOF", "Systems serology (antibody titers, Fc receptor binding, antibody-dependent functional assays, Luminex)", "Bulk and single-cell RNA sequencing", "NHP, mouse and human tissue and granuloma samples", "Human cohort patient visits", "PET/CT imaging and tissue imaging", "Bacterial samples and digitally barcoded Mtb"]', 'Hi-IMPAcTB is a multi-center tuberculosis consortium funded by NIAID as one of its Immune Mechanisms of Protection Against Mycobacterium tuberculosis (IMPAc-TB) centers, led by Sarah Fortune (Harvard T.H. Chan School of Public Health) with co-leads JoAnne Flynn (University of Pittsburgh) and W. Henry Boom (Case Western Reserve). It studies which immune responses to Mycobacterium tuberculosis protect against infection and disease, to guide vaccine and diagnostic design. The consortium collects multi-modal data from lungs and blood in mice, non-human primates and humans, including flow and mass cytometry, single-cell sequencing, systems serology, PET/CT imaging and barcoded Mtb strains.', 'https://reporter.nih.gov/project-details/11625980', 'https://fairdomhub.org/projects/222', 'Impact, IMPACT, IMPAcTb, Hi-IMPAcTB, tuberculosis, TB, Mycobacterium tuberculosis, Mtb, granuloma, non-human primate, immunology, Fortune, Flynn, Boom, Lauffenburger, Shalek, Bryson, NIAID, 75N93019C00071');
INSERT INTO `projects_context` (`name`, `alternative_names`, `entity_type`, `project_id`, `parent_project`, `pi`, `research_focus`, `key_data_types`, `description`, `nih_reporter_link`, `fairdomhub_published_link`, `tags`) VALUES ('MetNet', '["Kamm", "MIT MetNet", "MetNet Center", "Metastasis Research Network"]', 'project', 4, NULL, 'Kamm, Roger D. (MIT, contact PI); Shenoy, Vivek B. (UPenn, co-PI)', 'Mechanical determinants of metastatic cancer colonization, dormancy, and outgrowth; mechano-adaptation of circulating tumor cells during extravasation and organ-selective colonization', '["Microvascular network and organ-on-chip models", "Cell and device imaging with image analysis", "Extravasation, migration, permeability and clot assays", "RNA sequencing and chromatin sequencing analysis", "Computational and machine learning models", "Flow cytometry"]', 'The MIT MetNet Center is an NCI U54 center in the Metastasis Research Network, led by Roger Kamm (MIT) and Vivek Shenoy (University of Pennsylvania). It studies how mechanical and molecular stresses drive metastatic colonization, dormancy and outgrowth in different organs, including how circulating tumor cells adapt as they leave the blood vessels. The team combines engineered microvascular and organ-on-chip models, in vivo models and computational modeling to identify anti-metastatic therapeutic strategies.', 'https://reporter.nih.gov/project-details/11182474', 'https://fairdomhub.org/projects/340', 'MetNet, metastasis, microvascular network, organ-on-chip, extravasation, tumor microenvironment, Kamm, Shenoy, Friedl, NCI, U54, U54CA261694');
INSERT INTO `projects_context` (`name`, `alternative_names`, `entity_type`, `project_id`, `parent_project`, `pi`, `research_focus`, `key_data_types`, `description`, `nih_reporter_link`, `fairdomhub_published_link`, `tags`) VALUES ('MIT-Koch', '["Integrated Genome Technologies"]', 'project', 5, NULL, 'Levine, Stuart S. (MIT, Director, BioMicro Center)', 'Genomics core facility; sequencing library preparation and high-throughput sequencing; bioinformatics, including alignment, variant calling and mutational spectra', '["DNA sequencing", "Sequence alignment and variant calling", "Mutational spectra analysis"]', 'The MIT BioMicro Center, directed by Stuart Levine, is MIT''s genomics and bioinformatics core facility, run jointly by MIT''s Departments of Biology and Biological Engineering, the Koch Institute and the Center for Environmental Health Sciences. It provides sequencing library preparation, high-throughput sequencing, single-cell and spatial genomics, bioinformatics analysis and data management to labs across MIT. This project holds sequencing and analysis data generated at the center, such as alignments, variant calls and mutational spectra.', NULL, 'https://fairdomhub.org/investigations/779', 'MIT-Koch, BioMicro Center, BMC, genomics core, sequencing core, Koch Institute, Integrated Genome Technologies, Levine, MIT BioMicro Center, BioMicroCenter');
INSERT INTO `projects_context` (`name`, `alternative_names`, `entity_type`, `project_id`, `parent_project`, `pi`, `research_focus`, `key_data_types`, `description`, `nih_reporter_link`, `fairdomhub_published_link`, `tags`) VALUES ('NAMs', '["NAMs Technology Development Center for Women''s Health", "MIT NAMs Center", "NAMs Center"]', 'project', 14, NULL, 'Griffith, Linda G. (MIT, contact PI)', 'New approach methodologies; microphysiological systems and organ-on-chip models of gynecologic disease (endometriosis, adenomyosis, heavy menstrual bleeding, PCOS); computational systems biology; drug metabolism and safety models', '[]', 'The MIT NAMs Technology Development Center for Women''s Health, directed by Linda Griffith within the Center for Gynepathology Research, develops new approach methodologies (NAMs) to make drug development for gynecologic diseases easier. It builds human microphysiological systems of reproductive tissues and the liver, guided by computational systems biology and clinical data, and benchmarks them against patient data for endometriosis, adenomyosis, heavy menstrual bleeding and polycystic ovary syndrome. It is funded by NCATS through the NIH Common Fund''s Complement-ARIE program and works with industry partners on preclinical use cases.', 'https://reporter.nih.gov/project-details/11305605', NULL, 'NAMs, new approach methodologies, microphysiological systems, MPS, organ-on-chip, women''s health, gynecology, endometriosis, adenomyosis, Complement-ARIE, NCATS, Griffith, UM1TR006029');
INSERT INTO `projects_context` (`name`, `alternative_names`, `entity_type`, `project_id`, `parent_project`, `pi`, `research_focus`, `key_data_types`, `description`, `nih_reporter_link`, `fairdomhub_published_link`, `tags`) VALUES ('PUBLISHED', '[]', 'project', 6, NULL, NULL, NULL, '["Tissue and cell samples from mouse, non-human primate and patient studies", "Imaging data and image analysis", "Flow cytometry data", "Sequencing data and single-cell expression analysis", "Patient visit, bacterial and antibody samples"]', 'Published data: samples and data from NExtSEEK''s research programs that already appear in published papers, gathered in one shared project so any registered member can explore them. Most of these samples also belong to their program''s own project (Impact, SRP, MetNet, Griffith, Shoulders and CSBC).', NULL, NULL, 'PUBLISHED, published, published data, published samples, publications, papers');
INSERT INTO `projects_context` (`name`, `alternative_names`, `entity_type`, `project_id`, `parent_project`, `pi`, `research_focus`, `key_data_types`, `description`, `nih_reporter_link`, `fairdomhub_published_link`, `tags`) VALUES ('RMS-NGC', '["Koehler", "Next Generation Chemistry Center"]', 'project', 12, NULL, 'Koehler, Angela N. (MIT Koch Institute and Broad Institute, contact PI); Burgin, Alex B.; Gould, Alexandra E.; Linardic, Corinne M.; Nomura, Daniel (multi-PIs)', 'Fusion-positive alveolar rhabdomyosarcoma; PAX3-FOXO1 fusion oncoprotein; small-molecule discovery, targeted degraders (PROTACs, molecular glues) and chemoproteomics', '[]', 'An NCI Next Generation Chemistry Center at MIT, led by Angela Koehler with Alex Burgin, Alexandra Gould, Corinne Linardic and Daniel Nomura, that looks for drugs against fusion-positive alveolar rhabdomyosarcoma, a childhood cancer driven by the PAX3-FOXO1 fusion protein. Its projects look for small molecules that bind PAX3-FOXO1, degraders that remove it, and ways to target the transcriptional complex it works with, using medicinal chemistry, chemical biology and chemoproteomics. It is part of NCI''s Targeting Fusion Oncoproteins in Childhood Cancers (TFCC) network.', 'https://reporter.nih.gov/project-details/11401672', NULL, 'RMS-NGC, rhabdomyosarcoma, RMS, alveolar rhabdomyosarcoma, fusion-positive, PAX3-FOXO1, fusion oncoprotein, Next Generation Chemistry Center, NGC, TFCC, Koehler, Angela, Koch Institute, Broad Institute, Broad, small molecule, PROTAC, molecular glue, degrader, chemoproteomics, UM1CA294108');
INSERT INTO `projects_context` (`name`, `alternative_names`, `entity_type`, `project_id`, `parent_project`, `pi`, `research_focus`, `key_data_types`, `description`, `nih_reporter_link`, `fairdomhub_published_link`, `tags`) VALUES ('Shoulders', '["Shoulders Independent Projects", "Shoulders Lab", "Collagen Study"]', 'project', 11, NULL, 'Shoulders, Matthew D. (MIT Chemistry, PI)', 'Protein folding and proteostasis; collagen folding and ER quality control of procollagen; collagen disease variants (such as COL2A1 in osteoarthritis) in iPSC-derived cartilage models; chaperones and protein evolution', '["iPSC-derived cartilage (chondronoid) models", "Cell and tissue imaging", "RNA sequencing", "Mass spectrometry proteomics"]', 'Research from Matthew Shoulders'' lab in MIT Chemistry, which studies how cells fold proteins and how proteostasis networks, such as chaperones and endoplasmic reticulum quality control, shape protein function and evolution. A main direction is collagen proteostasis in health and disease: how procollagen is folded and checked, and how disease variants disrupt it, studied in human cartilage (chondronoids) grown from iPSCs and profiled by imaging, RNA sequencing and mass spectrometry proteomics. It is funded by NIAMS.', 'https://reporter.nih.gov/project-details/11400444', 'https://fairdomhub.org/projects/485', 'Shoulders, Shoulders Lab, collagen, Collagen Study, COL2A1, procollagen, proteostasis, protein folding, ER quality control, osteoarthritis, cartilage, chondronoid, iPSC, R01AR082995');
INSERT INTO `projects_context` (`name`, `alternative_names`, `entity_type`, `project_id`, `parent_project`, `pi`, `research_focus`, `key_data_types`, `description`, `nih_reporter_link`, `fairdomhub_published_link`, `tags`) VALUES ('SRP', '["Engelward", "MIT_SRP", "MIT SRP", "Superfund", "Superfund Research Program"]', 'project', 3, NULL, 'Engelward, Bevin P. (MIT)', 'Environmental health impacts of N-nitrosamines; hazardous chemical sensing, mutagenicity, cancer risk, and remediation of contaminated drinking water in affected communities (Wilmington, MA and Passamaquoddy Tribe)', '["Mouse nitrosamine exposure studies (tissues, histopathology, GPT assays)", "DNA damage and mutation assays (CometChip, RaDR imaging, mutational spectra sequencing)", "Community and field water sampling", "Chemical sensors and electrochemical detection", "Chemical synthesis and characterization (NMR, spectroscopy, crystallography)", "Water treatment (electrochemical filtration, ion chromatography)", "Sequencing and mass spectrometry"]', 'The MIT Superfund Research Program, an NIEHS-funded P42 center led by Bevin Engelward, studies the health risks of N-nitrosamines and other hazardous chemicals in drinking water, at the Olin Chemical Superfund Site in Wilmington, Massachusetts, and beyond. It combines engineering, biology and community engagement: sensors that detect contaminants, mouse and cell studies of DNA damage, mutation and cancer risk, and technologies that clean contaminated water. It works with affected communities, including Wilmington and the Passamaquoddy Tribe.', 'https://reporter.nih.gov/project-details/11398586', 'https://fairdomhub.org/projects/221', 'SRP, MIT SRP, Superfund, Superfund Research Program, NIEHS, P42, P42ES027707, Engelward, N-nitrosamines, nitrosamine, drinking water, water quality, DNA damage, mutagenesis, CometChip');
