-- 979 attribute definitions for dmac.sample_attributes_unique.
-- Every one judged from up to three real values observed in production
-- (166,235 samples). Attributes with no data anywhere are deliberately absent.
-- sample_type '' is the global definition; a code overrides it for that tab.

INSERT INTO sample_attributes_unique (field_name, sample_type, meaning) VALUES
 ('5_3UTR','','Ratio of reads mapping to the 5'' versus 3'' untranslated region, a measure of coverage evenness.'),
 ('ADVPowerLevel','','Power setting of the acoustic Doppler velocimeter, e.g. HIGH, LOW.'),
 ('ADVVelocityRange','','Velocity range the acoustic Doppler velocimeter was configured for, in the units named in ADVVelocityUnits.'),
 ('ADVVelocityUnits','','Unit for the ADVVelocity value, e.g. m/s, meters per second.'),
 ('Ablation','','Whether the patient has undergone an ablation procedure.'),
 ('Absorbance1','','First absorbance reading for this sample, at the wavelength named in AbsorbanceUnits.'),
 ('Absorbance2','','Second absorbance reading for this sample, at the wavelength named in Absorbance2Units.'),
 ('Absorbance2Units','','Unit for the Absorbance2 value, e.g. nm.'),
 ('AbsorbanceUnits','','Unit for the Absorbance value, e.g. nm.'),
 ('Accession','','The accession this data was deposited under in the repository named in Repository, e.g. PRJNA967652 or SRX25141024.'),
 ('ActiveCOVID19','','Whether the patient had an active COVID-19 infection at the time of sampling.'),
 ('AdditionalData','','Description of any supplementary file that accompanies this record, e.g. a supporting movie or summary output.'),
 ('AdditionalData_Link','','URL where the supplementary file described in AdditionalData can be downloaded.'),
 ('Adenomyosis','','Whether the patient has been diagnosed with adenomyosis.'),
 ('Age','','The subject''s age at the time of sampling.'),
 ('Age_Units','','Unit for the Age value, e.g. Years.'),
 ('Alcohol','','Whether the patient reports alcohol use.'),
 ('Algorithm','','The algorithm used to analyse this sample, e.g. 3D Horn-Schunck Optical Flow.'),
 ('Aligner','','The read aligner used, with version where known, e.g. star_salmon, bwa/0.7.12.'),
 ('Allergy','','Whether the patient has a recorded allergy.'),
 ('AlternativeID','','Another UID in NExtSEEK that refers to this same subject.'),
 ('AlternativeIDs','','Other identifiers this subject is known by, e.g. a facility ID such as 21-63.'),
 ('AminoAcidMutations','','Amino acid substitutions engineered into this antibody, e.g. L234A/L235A.'),
 ('AnalysisMethod','','The analytical method used, e.g. Capillary Electrophoresis.'),
 ('Analyte','','The molecule or antigen being measured or targeted. Semicolon-separate several, e.g. IFN-y; IL-6.'),
 ('AnalyteConc','','Concentration of the analyte, in the units named in AnalyteConcUnits.'),
 ('AnalyteConcUnits','','Unit for the Analyte Conc value, e.g. ppm, pg/mL.'),
 ('AnalyteProcedure','','How the analyte was applied or incubated, e.g. 100ug/mL overnight at 4C.'),
 ('AnalyteVolume','','Volume of analyte used, in the units named in AnalyteVolumeUnits.'),
 ('AnalyteVolumeUnits','','Unit for the Analyte Volume value, e.g. uL, ug.'),
 ('Analyte_Catalog#','','The vendor''s catalogue number for the analyte, e.g. G0885, NR-14848.'),
 ('Analyte_Vendor','','The vendor the analyte was purchased from, e.g. Millipore Sigma, BEI Resources.'),
 ('Analyzer','','The instrument the sample was read on, e.g. BD LSR II, FlexMap 3D.'),
 ('AnalyzerSoftware','','The software used for the analyzer, with version where known.'),
 ('Analyzer_Vendor','','The vendor the analyzer was purchased from, e.g. BD BioSciences, BD Biosciences.'),
 ('Animal','','Identifier of the individual animal this image or measurement came from.'),
 ('AnnotationGTF','','The GTF annotation file used for feature assignment, e.g. gencode.v43.primary_assembly.basic.'),
 ('AnnotationReference','','The reference genome annotation used for variant effect prediction.'),
 ('AnnotationTool','','The tool used to annotate variants, e.g. SnpEff.'),
 ('AntiCD107a_Ab_Fluorophore','','Fluorophore conjugated to the anti-CD107a antibody, e.g. PE-Cy5.'),
 ('AntiCD107a_Ab_Vendor','','The vendor the anti cd107a ab was purchased from, e.g. BD Biosciences, BD.'),
 ('AntiCD107a_Name','','Full product name of the anti-CD107a antibody used.'),
 ('AntibodyConcentrationUnits','','Unit for the Antibody Concentration value, e.g. ug/mL.'),
 ('AntibodyPanelParent','','UID of the antibody panel record used for this run.'),
 ('AntibodyParent','','UID or name of the antibody used to stain this sample, e.g. yH2AX.'),
 ('Antigen','','The antigen this assay was run against, e.g. LAM, PPD.'),
 ('AnxietyDepression','','Whether the patient has a recorded diagnosis of anxiety or depression.'),
 ('AreaUnits','','Unit for the Area value, e.g. cm^2.'),
 ('Arm','','The study arm or experimental group this subject belongs to, e.g. 10 week.'),
 ('Arm_Collapsed_Grouping','','The study arm this patient belongs to, after arms were collapsed into broader groups for analysis.'),
 ('Arm_Group_Name','','Name of the study arm group this patient belongs to.'),
 ('ArrayNumber','','Identifier of the physical array or plate this sample was run on.'),
 ('Ashermans','','Whether the patient has been diagnosed with Asherman''s syndrome.'),
 ('Assay','','The assay planned or performed on this sample.'),
 ('AssayType','','The type of assay performed, e.g. IHC, TEM.'),
 ('Assembly','','The reference genome assembly used, e.g. GRCh38.'),
 ('AssociatedCNV','','UID of the copy-number variant analysis derived from this sample.'),
 ('BALCollectedVolume','','Volume of bronchoalveolar lavage fluid recovered, in millilitres.'),
 ('BALCollectedVolumeUnits','','Unit for the BALCollected Volume value, e.g. mL.'),
 ('BALInstilledVolume','','Volume of fluid instilled during bronchoalveolar lavage, in millilitres.'),
 ('BALInstilledVolumeUnits','','Unit for the BALInstilled Volume value, e.g. milliliters.'),
 ('BCAValue','','Protein concentration measured by BCA assay.'),
 ('BCG_Cohort','','The BCG vaccination cohort this animal belongs to.'),
 ('BMI','','The patient''s body mass index.'),
 ('BacterialParent','','UID(s) of the bacterial stock used in this experiment. Semicolon-separate when several.'),
 ('BacterialStrain','','The bacterial strain used, e.g. H37Rv Mtb-Lux.'),
 ('Band','','The spectrometer frequency band used, e.g. X-band.'),
 ('BandQuantification','','How bands on the blot were quantified, including software and method.'),
 ('Barcode','','The nucleotide barcode identifying this sample within a pooled run, e.g. GAATTGCT.'),
 ('Barcode2','','The second nucleotide barcode, for dual-indexed libraries.'),
 ('Barcode2Type','','The kind of barcode used for the second index, e.g. Illumina Index.'),
 ('BarcodeType','','The kind of barcode identifying this sample within a pooled run, e.g. Illumina Index.'),
 ('Barcodes','','The cell-barcode companion file of a sparse expression matrix, as a filename or download URL.'),
 ('BarcodesDataType','','Format of the cell-barcode file named in Barcodes, e.g. TSV.'),
 ('BaselineCohort','','The baseline cohort label assigned to this patient at enrolment.'),
 ('Baseline_QFN','','The patient''s QuantiFERON result at baseline.'),
 ('BasisSet','','The basis set used for the quantum chemistry calculation, e.g. 6-31G*.'),
 ('BatteryLevelEnd','','Sensor battery voltage at the end of the deployment.'),
 ('BatteryLevelEndTime','','Clock time at which the end-of-deployment battery reading was taken.'),
 ('BatteryLevelStart','','Sensor battery voltage at the start of the deployment.'),
 ('BatteryLevelStartTime','','Clock time at which the start-of-deployment battery reading was taken.'),
 ('BatteryLevelUnits','','Unit for the Battery Level value, e.g. V, volt.'),
 ('BeadFluorescence','','The fluorescent label on the beads used, e.g. Streptavidin Phycoerythrin.'),
 ('Bead_Catalog#','','The vendor''s catalogue number for the bead, e.g. NR-14848, F8776.'),
 ('Bead_Coating','','What the beads were coated with, e.g. LAM, PPD.'),
 ('Bead_Fluorescence','','The fluorescent label on the beads used, e.g. yellow-green (FITC).'),
 ('Bead_Fluorophore','','The fluorophore conjugated to the beads used in this assay.'),
 ('Bead_Vendor','','The vendor the bead was purchased from, e.g. Invitrogen, Thermo Fisher Scientific.'),
 ('Bead_coating','','What the beads were coated with, e.g. LAM, PPD.'),
 ('Bead_coating_Catalog#','','The vendor''s catalogue number for the bead coating, e.g. MC10036-01, MC10048-01.'),
 ('Bead_coating_Vendor','','The vendor the bead coating was purchased from, e.g. BEI Resources, Staten Serum Institute.'),
 ('Bead_coating_vendor','','The supplier of the bead coating material, e.g. BEI Resources.'),
 ('Bead_fluorescence','','The fluorescent label on the beads used, e.g. MagPlex microspheres.'),
 ('BioSampleAccession','','The NCBI BioSample accession for this sample, e.g. SAMN32600606.'),
 ('Biotin','','The biotin reagent or biotinylation method used.'),
 ('Biotin_Vendor','','The vendor the biotin was purchased from, e.g. Avidity, Thermo Fisher Scientific.'),
 ('BirthWeight','','The subject''s weight at birth, in kilograms.'),
 ('BirthWeightUnits','','Unit for the Birth Weight value, e.g. kg.'),
 ('Blocking_solution','','The blocking solution used before staining, e.g. 5% BSA-PBS.'),
 ('BloodPressure_Units','','Unit for the Blood Pressure value, e.g. mmHg.'),
 ('Blood_Agar_Result','','The result of blood agar culture for this visit.'),
 ('BottleType','','The kind of container the water sample was collected in, e.g. Amber glass.'),
 ('C3Ab_Catalog#','','The vendor''s catalogue number for the c3 ab, e.g. 0855385, MP0855385.'),
 ('C3Ab_Fluorophore','','Fluorophore conjugated to the anti-C3 antibody, e.g. FITC.'),
 ('C3Ab_Vendor','','The vendor the c3 ab was purchased from, e.g. MP Biomedicals.'),
 ('CAD4TB_5','','CAD4TB version 5 chest X-ray score for this patient.'),
 ('CAD4TB_6','','CAD4TB version 6 chest X-ray score for this patient.'),
 ('CAD4TB_7','','CAD4TB version 7 chest X-ray score for this patient.'),
 ('CASNumber','','The CAS Registry Number identifying this chemical, e.g. 9005-79-2.'),
 ('CD16_Ab_Fluorophore','','Fluorophore conjugated to the anti-CD16 antibody, e.g. APC-Cy7.'),
 ('CD16_Ab_Vendor','','The vendor the cd16 ab was purchased from, e.g. BD Biosciences, BD.'),
 ('CD16_Name','','Full product name of the anti-CD16 antibody used.'),
 ('CD3Ab_Name','','Full product name of the anti-C3 detection antibody used.'),
 ('CD3_Ab_Fluorophore','','Fluorophore conjugated to the anti-CD3 antibody, e.g. Alexa Fluor 700.'),
 ('CD3_Ab_Vendor','','The vendor the cd3 ab was purchased from, e.g. BD Biosciences.'),
 ('CD3_Name','','Full product name of the anti-CD3 antibody used.'),
 ('CD4','','The patient''s CD4 T-cell measurement.'),
 ('CD4_Units','','Unit for the CD4 value, e.g. cells/uL.'),
 ('CD56_Ab_Fluorophore','','Fluorophore conjugated to the anti-CD56 antibody, e.g. PE-Cy7.'),
 ('CD56_Ab_Vendor','','The vendor the cd56 ab was purchased from, e.g. BD Biosciences, BD.'),
 ('CD56_Name','','Full product name of the anti-CD56 antibody used.'),
 ('CDSPercent','','Fraction of reads falling within coding sequence.'),
 ('CEQ','','Chromosomal equivalents measured for this sample, on the scale given in CEQUnits.'),
 ('CEQUnits','','Unit and transform for the CEQ value, e.g. Log10 CEQ (+1).'),
 ('CFU','','Colony forming units counted for this sample, on the scale given in CFUUnits.'),
 ('CFU/CEQ','','Ratio of colony forming units to chromosomal equivalents, on the scale in CFU/CEQUnits.'),
 ('CFU/CEQUnits','','Unit and transform for the CFU/CEQ value, e.g. Log10 CFU/CEQ.'),
 ('CFUUnits','','Unit and transform for the CFU value, e.g. log10CFU/lung.'),
 ('CFU_FileLink','','URL where the CFU count file named in CFU_FileName can be downloaded.'),
 ('CFU_FileName','','Filename of the spreadsheet holding this sample''s CFU counts.'),
 ('CNV_Detector','','The tool used to call copy-number variants, e.g. hmmcopy/0.1.1.'),
 ('COVID19TestType_LastPositiveCOVID19','','The kind of test used for the patient''s most recent positive COVID-19 result.'),
 ('COVID19Vax','','Whether the patient has been vaccinated against COVID-19.'),
 ('COVID19VaxDate','','When the patient received their COVID-19 vaccination.'),
 ('COVID19VaxName','','The COVID-19 vaccine product the patient received.'),
 ('COVID19VaxType','','The type of COVID-19 vaccine the patient received.'),
 ('COVID19_PCR_inlast4Weeks','','Whether the patient had a COVID-19 PCR test in the four weeks before sampling.'),
 ('COVID19_Test_Result','','The result of the COVID-19 test taken at this visit.'),
 ('COVID19_Test_Type','','The kind of COVID-19 test taken at this visit.'),
 ('COVIDHistory','','Whether the patient has a history of COVID-19 infection.'),
 ('CXRScore','','The chest X-ray score recorded for this patient.'),
 ('Calibration','','The calibration state of the instrument for this run.'),
 ('Cancer','','Whether the patient has a cancer diagnosis.'),
 ('CancerHistory','','Whether the patient has a history of cancer.'),
 ('Cannabis_Use','','Whether the patient reports cannabis use.'),
 ('CanonicalGenes','','The canonical genes covered by this panel, comma-separated.'),
 ('CaptureKit','','The kit used to capture or label the target molecules, e.g. Glycan Assure APTS Kit.'),
 ('CaptureKit_Vendor','','The vendor the capture kit was purchased from, e.g. Life Technologies.'),
 ('CardiacIllness','','Whether the patient has a recorded cardiac illness.'),
 ('CarrierGas','','The carrier gas used by the sensor or instrument, e.g. air.'),
 ('Catalog#','','The vendor''s catalogue number for the catalog#, e.g. 346276, 215392.'),
 ('CatalogLink','','URL of the vendor''s catalogue page for this product.'),
 ('CellConcentration','','Concentration of cells in the suspension, in cells per millilitre.'),
 ('CellConcentrationUnits','','Unit for the Cell Concentration value, e.g. cells/mL.'),
 ('CellCount','','Total number of cells counted for this sample.'),
 ('CellCount_File','','Filename of the spreadsheet holding this sample''s cell counts.'),
 ('CellCount_Link','','Where the cell count file is stored, e.g. Zenodo.'),
 ('CellCount_Macrophage','','Number of macrophages counted for this sample.'),
 ('CellCounter','','The instrument used to count cells, e.g. Bio-Rad TC20.'),
 ('CellLine','','The cell line used, e.g. A549.'),
 ('CellLineage','','The lineage or passage history of the cells used.'),
 ('CellTypes','','The cell types identified in this sample, with their proportions where recorded.'),
 ('Channel','','The detector channel this measurement was read on.'),
 ('Channels','','The imaging channels captured, e.g. w1, w2.'),
 ('Charge','','The net molecular charge used in the simulation.'),
 ('Checksum_Barcodes','','MD5 digest of the barcode file, used to verify it arrived intact. BMC data specialists can fill this out.'),
 ('Checksum_CompensationData','','MD5 digest of the compensation data file, used to verify it arrived intact. BMC data specialists can fill this out.'),
 ('Checksum_Genes','','MD5 digest of the gene/feature file, used to verify it arrived intact. BMC data specialists can fill this out.'),
 ('Checksum_Metadata','','MD5 digest of the metadata file, used to verify it arrived intact. BMC data specialists can fill this out.'),
 ('Checksum_PrimaryData','','MD5 digest of the primary data file, used to verify integrity after transfer. Compute with md5sum (Linux), md5 (macOS), or certutil -hashfile <file> MD5 (Windows). BMC data specialists can fill this out.'),
 ('Checksum_PrimaryType','','The digest algorithm used in the Checksum_ columns, e.g. MD5. BMC data specialists can fill this out.'),
 ('Checksum_SecondaryData','','MD5 digest of the secondary data file, used to verify it arrived intact. BMC data specialists can fill this out.'),
 ('Checksum_SecondaryType','','MD5 digest of the secondary type file, used to verify it arrived intact. BMC data specialists can fill this out.'),
 ('Chest_XRAY_Reading','','The radiologist''s reading of the chest X-ray taken at this visit.'),
 ('ChronicRespiratoryDisease','','Whether the patient has a chronic respiratory disease.'),
 ('Classification','','The classification assigned to this subject within the study, e.g. RSTR, Canonical.'),
 ('Clone','','The antibody clone designation, e.g. RPA-T8.'),
 ('CoScientist','','Another lab member who contributed to this sample, alongside the one named in Scientist.'),
 ('Code','','Link to the source code or repository used to produce this result.'),
 ('Cohort','','The cohort this animal belongs to, e.g. 1 Day, 3 Days.'),
 ('CollectionDate','','The date this sample was collected.'),
 ('CollectionTime','','Time elapsed at collection, in the units used by this assay.'),
 ('CollectionTimeUnits','','Unit for the Collection Time value, e.g. Day.'),
 ('ColonyTiter','','The selection condition used when titering colonies, e.g. Chloramphenicol.'),
 ('ColonyTiterCount','','Number of colonies counted during titering.'),
 ('Color','','The visual appearance of the sample, e.g. BLOODY, CLEAR.'),
 ('ComparatorReference','','The reference value the sensor reading was compared against.'),
 ('ComparatorReferenceUnits','','Unit for the Comparator Reference value, e.g. mV, millivolt.'),
 ('CompensationFCSParent','','UID(s) of the FCS compensation control files used for this run. Semicolon-separate when several.'),
 ('Complement','','The complement source used in the assay, e.g. guinea pig complement.'),
 ('Complement_Catalog#','','The vendor''s catalogue number for the complement, e.g. CL4051.'),
 ('Complement_Vendor','','The vendor the complement was purchased from, e.g. Cederlane, Cedar Lane Labs.'),
 ('ConcType','','The method used to measure concentration, e.g. qPCR, SYBR.'),
 ('ConcUnits','','Unit for the Conc value, e.g. ng/uL, ng/ul.'),
 ('Concentration','','Concentration of the material, in the units named in the matching Units column.'),
 ('ConcentrationPerVial','','Concentration of material in each vial, in cells or units per millilitre.'),
 ('ConcentrationRange','','The range of concentrations tested, e.g. 0.01 to 2 ug/mL.'),
 ('ConcentrationUnits','','Unit for the Concentration value, e.g. mg/mL, mg/ml.'),
 ('ConductivityCalibrationDate','','The date the sensor''s conductivity channel was last calibrated.'),
 ('ConductivityCalibrationUnits','','Unit for the Conductivity Calibration value, e.g. I/V ratio to uS/cm, I/V ratio to microsiemens per centimeter.'),
 ('ConductivityEndTime','','Clock time at which conductivity logging stopped.'),
 ('ConductivityLinearCalibrationIntercept','','Intercept of the linear calibration applied to the conductivity channel.'),
 ('ConductivityLinearCalibrationSlope','','Slope of the linear calibration applied to the conductivity channel.'),
 ('ConductivityStartTime','','Clock time at which conductivity logging started.'),
 ('Contact','','Email address of the person to contact about this record.'),
 ('Contamination','','How the data were screened for contamination, and against what reference.'),
 ('ContinuousPhase','','The continuous phase of the emulsion, e.g. 1X PBS.'),
 ('Core','','Identifier of the tissue core this sample came from, e.g. C4.'),
 ('Cough','','Whether the patient reported a cough.'),
 ('CoughSputum','','Whether the patient reported coughing up sputum.'),
 ('CountryOfOrigin','','The country the animal was sourced from.'),
 ('Crystal','','The crystal material used in the spectrometer, e.g. Diamond.'),
 ('Culture','','The culture medium and conditions used to grow this organism.'),
 ('CultureFormat','','The physical format the cells were cultured in, e.g. 2D monolayer in flasks, 3D Matrigel domes.'),
 ('CxrRadiologistConclusion','','The radiologist''s conclusion from the chest X-ray.'),
 ('Cycles','','Number of cycles run, e.g. imaging or amplification cycles.'),
 ('DESeqFile','','Filename of the DESeq results object for this analysis.'),
 ('DESeqFile_Link','','Where the DESeq results file named in DESeqFile is stored.'),
 ('DNA Type','','The kind of DNA in this sample, e.g. Microbial DNA, PCR Amplicon.'),
 ('DRTB_History','','Whether the patient has a history of drug-resistant TB.'),
 ('DWTP','','The drinking water treatment plant region this sample came from.'),
 ('DataDictionary','','URL of the data dictionary describing this study''s variables.'),
 ('DataType','','The format of the file named in File_PrimaryData, e.g. FASTQ.'),
 ('DatapointTime','','The time interval between logged sensor datapoints.'),
 ('DatapointTimeUnits','','Unit for the Datapoint Time value, e.g. ms, millisecond.'),
 ('Dataset','','The figure or dataset this record belongs to, e.g. Figure 2.'),
 ('DateLMP','','Date of the patient''s last menstrual period.'),
 ('DateOfBirth','','The subject''s date of birth.'),
 ('DateRange','','The span of dates this record covers, e.g. Feb. 20, 2020-April 15, 2020.'),
 ('Date_LastPositiveCOVID19','','Date of the patient''s most recent positive COVID-19 test.'),
 ('Deceased','','Whether the patient is deceased.'),
 ('Dechlorinated','','Whether the water sample was dechlorinated on collection.'),
 ('DechlorinationAgent','','The agent used to dechlorinate the sample, e.g. sodium thiosulfate.'),
 ('DechlorinationDoseMgPerL','','Dose of dechlorination agent added, in milligrams per litre.'),
 ('DeliveryMode','','How the patient was delivered at birth, e.g. NVD, C section.'),
 ('DemultiplexingTool','','The tool used to demultiplex reads, with version where known.'),
 ('Description','','Free-text description of this sample. Use it for context no other column captures.'),
 ('DetectionMethod','','How signal was detected, e.g. Near-infrared fluorescence, Chemiluminescence.'),
 ('Detection_Ab','','The detection antibody used, including its conjugate.'),
 ('Detection_Ab_Catalog#','','The vendor''s catalogue number for the detection ab, e.g. 1030-09S, 1020-09.'),
 ('Detection_Ab_Lot#','','The manufacturer''s lot number for the detection antibody.'),
 ('Detection_Ab_vendor','','The vendor the detection antibody was purchased from.'),
 ('Detector','','The detection reagent or substrate used, e.g. TMB.'),
 ('DetectorName','','The camera or detector used to acquire the image, e.g. AxioCam HR R3.'),
 ('Detector_Catalog#','','The vendor''s catalogue number for the detector, e.g. 34029, 555214.'),
 ('Detector_Vendor','','The vendor the detector was purchased from, e.g. Thermo Fisher Scientific, BD.'),
 ('DiagnosisDate','','The date the patient was diagnosed.'),
 ('DigestiveEnzyme','','The enzyme used to digest the sample, e.g. IdeS.'),
 ('DigestiveEnzyme_Vendor','','The vendor the digestive enzyme was purchased from, e.g. Promega.'),
 ('DigestiveTemperature','','Temperature the digestion was carried out at, in degrees Celsius.'),
 ('DigestiveTemperatureUnits','','Unit for the Digestive Temperature value, e.g. Celsius.'),
 ('Dilution','','The dilution the reagent was used at, e.g. 1:200.'),
 ('Disease','','The disease state of this subject, e.g. tuberculosis, control.'),
 ('DiseaseHistory','','Whether the patient has a relevant disease history.'),
 ('DiseaseReference','','The disease this record refers to, e.g. HIV.'),
 ('DiseaseStage','','The stage of disease, e.g. latent.'),
 ('DispersePhase','','The disperse phase of the emulsion, with its composition.'),
 ('DissociationConditions','','The conditions used to dissociate the tissue or cells.'),
 ('DissociationReagents','','The reagents used to dissociate the tissue or cells, e.g. TrypLE Express.'),
 ('Docker','','The container image or protocol record defining the analysis environment.'),
 ('Domain','','The image domain this analysis was run on, e.g. RaDR image.'),
 ('DomainBeadSelector','','The beads used to select the target domain, e.g. Protein G Beads.'),
 ('DomainSelectionTarget','','The antibody domain selected for, e.g. Fc.'),
 ('DurationUnits','','Unit for the Duration value, e.g. minutes.'),
 ('ELISAplate_Vendor','','The vendor the elisaplate was purchased from, e.g. Thermo Fisher Scientific, MaxiSorp.'),
 ('ElectrophoresisConditions','','The separation conditions used, including module and size range.'),
 ('EmissionWavelength','','The emission wavelength detected, in nanometres.'),
 ('End_Study_TB_Status','','The patient''s TB status at the end of the study.'),
 ('EnrollmentDate','','The date the patient was enrolled in the study.'),
 ('EthicsApproval','','The ethics approval reference covering use of this material.'),
 ('Ethnicity','','The patient''s self-reported ethnicity.'),
 ('ExcitationWavelength','','The excitation wavelength used, in nanometres.'),
 ('ExonIntergenicRatio','','Ratio of reads mapping to exons versus intergenic regions.'),
 ('ExonIntronRatio','','Ratio of reads mapping to exons versus introns.'),
 ('ExperimentType','','The kind of experiment this sample was used in, e.g. Flow, Histology.'),
 ('ExperimentalTimepoint','','The experimental timepoint this visit corresponds to, e.g. Depletion.'),
 ('ExposureTime','','How long the sample was exposed to the treatment or the detector.'),
 ('ExpressionKit','','The commercial kit used to prepare the expression library, with vendor and version.'),
 ('ExtractedMolecule','','The molecule extracted for library prep. GEO''s examples: total RNA, polyA RNA, cytoplasmic RNA, nuclear RNA, genomic DNA, protein, other.'),
 ('ExtractionInterval','','When this sample was extracted, stated relative to a study event.'),
 ('ExtractionIntervalNotes','','Notes on timing of extraction relative to study events, e.g. a vaccination date.'),
 ('ExtractionKit','','The commercial kit used to extract nucleic acid, with catalogue number and vendor.'),
 ('ExtractionMethod','','The method used to extract nucleic acid, e.g. TRIzol + Direct-zol.'),
 ('ExtractionWindowDaysMax','','The maximum number of days allowed between collection and extraction.'),
 ('FMO','','The fluorescence-minus-one control used for this marker.'),
 ('F_bp','','Read length in base pairs of the forward mate.'),
 ('Facility','','The facility or lab where this work was carried out.'),
 ('Fc_gamma_Receptor','','The Fc gamma receptor this assay was run against, e.g. FcyR2A.'),
 ('Fc_gamma_Receptor_Vendor','','The vendor the fc gamma receptor was purchased from, e.g. Sigma, Duke Production Facility.'),
 ('Fc_gamma_receptor_Catalog#','','The vendor''s catalogue number for the fc gamma receptor.'),
 ('Fever','','Whether the patient reported fever.'),
 ('Fibroid','','Whether the patient has been diagnosed with fibroids.'),
 ('FieldBlank','','Whether this sample is a field blank rather than a real collection.'),
 ('Figure','','The manuscript figure this image appears in.'),
 ('File_CompensationData','','Filename of the compensation data file, as deposited.'),
 ('File_PrimaryData','','Filename of the primary data file for this sample, as deposited. Every file listed must also appear in the checksums table.'),
 ('File_SearchEngineOutput','','Filename of the search engine output file, as deposited.'),
 ('File_SecondaryData','','Filename of the secondary data file, as deposited.'),
 ('File_TMT','','Filename of the tmt file, as deposited.'),
 ('File_TertiaryData','','Filename of the tertiary data file, as deposited.'),
 ('Filter','','The filter used to prepare the sample, e.g. 0.2 uM.'),
 ('FilterMethod','','The method used to filter variants, e.g. bcftools isec.'),
 ('FilterSet','','The filter set or benchmark applied, e.g. GIAB HG001 GRCh38 v4.2.1.'),
 ('Filter_Vendor','','The vendor the filter was purchased from, e.g. Fisher; Amicon.'),
 ('Fixation','','Whether the sample was fixed before analysis.'),
 ('Fixative','','The fixative used, e.g. 4% Paraformaldehyde.'),
 ('Fixed','','Whether the sample was fixed before analysis.'),
 ('FloorDist','','Distance from the sensor to the floor, in the units used by this deployment.'),
 ('FloorDistUnits','','Unit for the Floor Dist value, e.g. cm, centimeter.'),
 ('FlowAmount','','Number of events acquired on the flow cytometer.'),
 ('FlowAmountUnits','','Unit for the Flow Amount value, e.g. cells.'),
 ('FlowCellType','','The sequencer flow cell type used, e.g. HighOutput.'),
 ('FlowLane','','The flow cell or lane identifier this library was sequenced on.'),
 ('FluorescenceLinearCalibrationDate','','The date the sensor''s fluorescence channel was last calibrated.'),
 ('FluorescenceLinearCalibrationIntercept','','Intercept of the linear calibration applied to the fluorescence channel.'),
 ('FluorescenceLinearCalibrationSlope','','Slope of the linear calibration applied to the fluorescence channel.'),
 ('FluorescenceLinearCalibrationUnits','','Unit for the Fluorescence Linear Calibration value, e.g. photon counts/s to ppm humic acid, photon counts/s to ppm TOC.'),
 ('FluorescentLabels','','The fluorescent labels imaged, and what each one marks.'),
 ('Fluoro-Streptavidine','','The fluorophore-conjugated streptavidin used, e.g. Streptavidin-PE.'),
 ('Fluoro-Streptavidine_Catalog#','','The vendor''s catalogue number for the fluoro-streptavidine, e.g. PJ31S.'),
 ('Fluoro-Streptavidine_Vendor','','The vendor the fluoro-streptavidine was purchased from, e.g. Prozyme.'),
 ('FluorometerCell','','The cuvette used in the fluorometer, with its dimensions.'),
 ('Fluorophore','','The fluorophore conjugated to this antibody, e.g. BV421.'),
 ('FlushDurationMinutes','','How long the tap was flushed before collection, in minutes.'),
 ('Foci','','The nuclear foci marker scored in this image, e.g. yH2AX.'),
 ('FollowUp_QFN','','The patient''s QuantiFERON result at follow-up.'),
 ('Form','','The physical form of the chemical, e.g. powder.'),
 ('Formula','','The chemical formula of this compound, e.g. C39H37N3O5W.'),
 ('Frequency','','The operating frequency of the instrument, in the units it reports.'),
 ('FrequencyUnits','','Unit for the Frequency value, e.g. Hz, hertz.'),
 ('Funder','','The grant or funding source supporting this work, including the award number.'),
 ('G/P','','The patient''s gravidity and parity.'),
 ('GPS','','The latitude and longitude where this sample was collected.'),
 ('GPSUnits','','Unit for the GPS value, e.g. decimal degrees.'),
 ('GelType','','The gel and membrane used for separation and transfer.'),
 ('GeneTargets','','The genes targeted by this assay, comma-separated.'),
 ('GeneXPert_Ultra_Ranking','','The semi-quantitative ranking from the GeneXpert Ultra assay.'),
 ('GeneXPert_Ultra_Result','','The result of the GeneXpert Ultra assay for this visit.'),
 ('GeneXPert_Ultra_Rif_Resistance','','Whether the GeneXpert Ultra assay detected rifampicin resistance.'),
 ('GeneXpert','','The patient''s GeneXpert result.'),
 ('Genes','','The gene/feature-name companion file of a sparse expression matrix, as a filename or URL.'),
 ('GenesDataType','','Format of the gene/feature file named in Genes, e.g. TSV.'),
 ('GenesDetected','','Number of genes detected in this library.'),
 ('GenesDetectedPercent','','Fraction of the annotated genes detected in this library.'),
 ('Genome','','The reference genome used, e.g. GRCm38.p6.'),
 ('GenomeSequence','','Whether and where this organism''s genome was sequenced.'),
 ('Genotype','','The genotype of the animal or cell line.'),
 ('Gestation','','Gestational age at birth, in weeks and days.'),
 ('GramStaining','','The Gram stain result for this organism, e.g. Positive, Acid Fast.'),
 ('Gravity','','The patient''s gravidity, i.e. number of pregnancies.'),
 ('Group_InCohort','','Which group within the cohort this animal belongs to.'),
 ('GrowthConditions','','The conditions the cells were grown in, including format and substrate.'),
 ('HBA1CPercent','','The patient''s HbA1c, as a percentage.'),
 ('HIV_Test_Result','','The result of the HIV test taken at this visit.'),
 ('HIV_Test_Type','','The kind of HIV test taken at this visit.'),
 ('HLA_A','','The subject''s HLA-A alleles, e.g. A*01:01/A*02:01.'),
 ('HLA_B','','The subject''s HLA-B alleles, e.g. B*07:02/B*08:01.'),
 ('HLA_C','','The subject''s HLA-C alleles, e.g. C*07:02/C*07:01.'),
 ('HOMOEnergy','','Energy of the highest occupied molecular orbital from the calculation.'),
 ('HOMOEnergyUnits','','Unit for the HOMOEnergy value, e.g. eV.'),
 ('HeartRateFirstReading','','The patient''s first heart rate reading at this visit.'),
 ('HeartRateForthReading','','The patient''s fourth heart rate reading at this visit.'),
 ('HeartRateSecondReading','','The patient''s second heart rate reading at this visit.'),
 ('HeartRateThirdReading','','The patient''s third heart rate reading at this visit.'),
 ('HeartRate_Units','','Unit for the Heart Rate value, e.g. beats per minute.'),
 ('Height','','The patient''s height, in the units named in Height_Units.'),
 ('Height_Units','','Unit for the Height value, e.g. meter, centimeters.'),
 ('Hemoglobin','','The patient''s haemoglobin measurement at this visit.'),
 ('Hemoglobin_Units','','Unit for the Hemoglobin value.'),
 ('Hormones','','Whether the patient is on hormone treatment.'),
 ('HormonesHistory','','Whether the patient has a history of hormone treatment.'),
 ('Household','','The household TB contact status for this patient.'),
 ('Humidity','','Relative humidity recorded by the sensor.'),
 ('HumidityUnits','','Unit for the Humidity value, e.g. %.'),
 ('ID','','The study identifier for this subject, as used in the source records.'),
 ('INFg_Ab_Fluorophore','','Fluorophore conjugated to the anti-IFN-gamma antibody, e.g. FITC.'),
 ('INFg_Ab_Vendor','','The vendor the infg ab was purchased from, e.g. BD biosciences, BD Biosciences.'),
 ('INFg_Name','','Full product name of the anti-IFN-gamma antibody used.'),
 ('IUPAC Name','','The IUPAC systematic name of this compound.'),
 ('Identification','','The search engine used to identify peptides, e.g. SEQUEST.'),
 ('ImageTimepoint','','When this image was taken relative to the start of the experiment, e.g. 1 h.'),
 ('IndexInlineLength','','Length in bases of the inline index sequence.'),
 ('IndexInlineStartNT','','Position in the read where the inline index starts, counted in bases.'),
 ('Indication','','The clinical indication for this patient''s procedure.'),
 ('InfectedCells','','The cell type that was infected, e.g. Human monocyte-derived macrophages.'),
 ('Initial_Diagnosis','','The patient''s diagnosis at presentation, including molecular markers.'),
 ('InputMassRNA','','Amount of RNA put into library preparation.'),
 ('InsertionSize','','The library insert size, in base pairs.'),
 ('Instrument','','The instrument this sample was run on, e.g. Cytek Aurora Spectral Cytometer.'),
 ('Instrument2','','A second instrument used for this sample.'),
 ('InstrumentType','','The class of instrument used, e.g. Inverted, Scanning Transmission Electron Microscope.'),
 ('InstrumentUser','','The person who operated the instrument for this run.'),
 ('IntegrationTime','','The sensor''s integration time per reading.'),
 ('IntegrationTimeUnits','','Unit for the Integration Time value, e.g. ms, millisecond.'),
 ('IntergenicPercent','','Fraction of reads mapping to intergenic regions.'),
 ('IntronPercent','','Fraction of reads mapping to introns.'),
 ('Ionization','','The ionization source and polarity used, e.g. ESI, APCI Positive Mode.'),
 ('IonizationMethod','','The ionization method used, e.g. ESI.'),
 ('IsolationKit','','The kit used to isolate the target molecules.'),
 ('IsolationKit_Vendor','','The vendor the isolation kit was purchased from, e.g. Life Technologies.'),
 ('IsolationTarget','','What was isolated, e.g. Glycans.'),
 ('Isotype','','The antibody''s species and isotype, e.g. Mouse IgG1, kappa.'),
 ('KPS_Score','','The patient''s Karnofsky Performance Status score.'),
 ('Kit','','The assay kit used, with catalogue number where known.'),
 ('KitVendor','','The vendor the kit was purchased from, e.g. MilliporeSigma, Millipore Sigma.'),
 ('LEDCurrentAvgEnd','','Mean sensor LED current at the end of the deployment.'),
 ('LEDCurrentAvgStart','','Mean sensor LED current at the start of the deployment.'),
 ('LEDCurrentCalibrationDate','','The date the sensor''s LED current channel was last calibrated.'),
 ('LEDCurrentCalibrationUnits','','Unit for the LEDCurrent Calibration value, e.g. ADC counts to mA.'),
 ('LEDCurrentEndTime','','Clock time at which the end-of-deployment LED reading was taken.'),
 ('LEDCurrentLinearCalibrationIntercept','','Intercept of the linear calibration applied to the LED current channel.'),
 ('LEDCurrentLinearCalibrationSlope','','Slope of the linear calibration applied to the LED current channel.'),
 ('LEDCurrentStartTime','','Clock time at which the start-of-deployment LED reading was taken.'),
 ('LEDCurrentStdevEnd','','Standard deviation of LED current at the end of the deployment.'),
 ('LEDCurrentStdevStart','','Standard deviation of LED current at the start of the deployment.'),
 ('LEDCurrentUnits','','Unit for the LEDCurrent value, e.g. ADC counts.'),
 ('LUMOEnergy','','Energy of the lowest unoccupied molecular orbital from the calculation.'),
 ('LUMOEnergyUnits','','Unit for the LUMOEnergy value, e.g. eV.'),
 ('Lab','','The lab that owns or generated this sample.'),
 ('Label','','The label attached to the target molecules, e.g. APTS.'),
 ('LabellingKit','','The kit used to label the target molecules.'),
 ('LabellingKit_Vendor','','The vendor the labelling kit was purchased from, e.g. Life Technologies.'),
 ('Labels','','Mapping of sample names to isobaric label channels used in this run.'),
 ('Ladder','','The size ladder run alongside the samples.'),
 ('Ladder_Vendor','','The vendor the ladder was purchased from, e.g. Thermo Fisher Scientific.'),
 ('LanderBackLegHeight','','Height of the lander''s back leg, in the units used by this deployment.'),
 ('LanderLeftLegHeight','','Height of the lander''s left leg, in the units used by this deployment.'),
 ('LanderLegHeightUnits','','Unit for the Lander Leg Height value, e.g. cm, centimeter.'),
 ('LanderRightLegHeight','','Height of the lander''s right leg, in the units used by this deployment.'),
 ('Leukocytes','','The leukocyte source used in this assay, e.g. whole blood from healthy donors.'),
 ('Leukocytes_Vendor','','The vendor the leukocytes was purchased from, e.g. In-house isolation from naive mice, Research Blood Components.'),
 ('LevelofTheory','','The level of theory used for the calculation, e.g. B3LYP/6-31G*.'),
 ('LibraryDesign','','Whether each fragment was read once or from both ends.'),
 ('LibraryPrep','','The library preparation chemistry used, e.g. 10x Single Cell 3'' v3.'),
 ('LibrarySelection','','The method used to select or enrich the material before sequencing.'),
 ('LibrarySource','','The biological source category of the material that went into the library.'),
 ('LibraryStrategy','','The sequencing strategy, i.e. what kind of experiment produced the reads.'),
 ('LibraryType','','The kind of library prepared, e.g. mRNA, ADT.'),
 ('LightEmission_Plasmid','','The plasmid driving light emission in this reporter strain.'),
 ('LightEmission_Reporter','','The reporter used for light emission, e.g. GFP, mCherry.'),
 ('Link','','Path or URL where this record''s data is stored.'),
 ('LinkCohortFile','','URL of the cohort definition file for this antibody panel.'),
 ('Link_BAM.pdf','','Download URL or storage path for the bam.pdf file.'),
 ('Link_BiopsySites','','Download URL or storage path for the biopsy sites file.'),
 ('Link_BodyWeight','','Download URL or storage path for the body weight file.'),
 ('Link_Brainmask','','Download URL or storage path for the brainmask file.'),
 ('Link_Catalog#','','Download URL or storage path for the catalog# file.'),
 ('Link_Code','','Download URL or storage path for the code file.'),
 ('Link_CompensationData','','Download URL or storage path for the compensation data file.'),
 ('Link_Contamination','','Download URL or storage path for the contamination file.'),
 ('Link_Design','','Download URL or storage path for the design file.'),
 ('Link_GTF','','Download URL or storage path for the gtf file.'),
 ('Link_Genome','','Download URL or storage path for the genome file.'),
 ('Link_InjectionSite','','Download URL or storage path for the injection site file.'),
 ('Link_MASKFile','','Download URL or storage path for the maskfile file.'),
 ('Link_Matrix','','Download URL or storage path for the matrix file.'),
 ('Link_Metadata','','Download URL or storage path for the metadata file.'),
 ('Link_NeedleTracks','','Download URL or storage path for the needle tracks file.'),
 ('Link_OrganWeight','','Download URL or storage path for the organ weight file.'),
 ('Link_PSM','','Download URL or storage path for the psm file.'),
 ('Link_Pipeline','','Download URL or storage path for the pipeline file.'),
 ('Link_PrimaryData','','Download URL or storage path for the file named in File_PrimaryData.'),
 ('Link_QC','','Download URL or storage path for the qc file.'),
 ('Link_QualityControlFile','','Download URL or storage path for the quality control file file.'),
 ('Link_ReferenceGenome','','Download URL or storage path for the reference genome file.'),
 ('Link_Reviewer','','Download URL or storage path for the reviewer file.'),
 ('Link_SRA','','Download URL or storage path for the sra file.'),
 ('Link_SearchEngineOutput','','Download URL or storage path for the search engine output file.'),
 ('Link_SecondaryData','','Download URL or storage path for the secondary data file.'),
 ('Link_Sequence','','Download URL or storage path for the sequence file.'),
 ('Link_StealthTransform','','Download URL or storage path for the stealth transform file.'),
 ('Link_StrainReference','','Download URL or storage path for the strain reference file.'),
 ('Link_StudyDesign','','Download URL or storage path for the study design file.'),
 ('Link_TMT','','Download URL or storage path for the tmt file.'),
 ('Link_TertiaryData','','Download URL or storage path for the tertiary data file.'),
 ('LiquidCultureResult','','The patient''s liquid culture result.'),
 ('Location','','The position this sample was taken from, e.g. L1.'),
 ('LocationType','','The kind of water body sampled, e.g. River, Lake.'),
 ('Lot#','','The manufacturer''s lot number for this product.'),
 ('LowestBpDiastolic','','The lowest diastolic blood pressure recorded for this patient.'),
 ('LowestBpSystolic','','The lowest systolic blood pressure recorded for this patient.'),
 ('LuminexDesign','','The Luminex assay design used, including panel and platform details.'),
 ('LungCFU','','Colony forming units recovered from lung tissue.'),
 ('LungPathologyScore','','Pathology score assigned to the lung.'),
 ('LymphNodeCFU','','Colony forming units recovered from lymph node tissue.'),
 ('LymphNodePathologyScore','','Pathology score assigned to the lymph node.'),
 ('MDLNumber','','The MDL number identifying this chemical, e.g. MFCD00081547.'),
 ('MGITCulture_Result','','The patient''s MGIT culture result.'),
 ('MGIT_Culture_Result','','The MGIT culture result for this visit.'),
 ('MGMT_Promoter_Status','','The methylation status of the tumour''s MGMT promoter.'),
 ('MIP-1B_Ab_Fluorophore','','Fluorophore conjugated to the anti-MIP-1-beta antibody, e.g. PE.'),
 ('MIP-1B_Ab_Vendor','','The vendor the mip-1 b ab was purchased from, e.g. BD.'),
 ('MIP-1B_Name','','Full product name of the anti-MIP-1-beta antibody used.'),
 ('MTB_Cohort','','The M. tuberculosis challenge cohort this animal belongs to.'),
 ('MTB_LiquidCulture_Result','','The M. tuberculosis liquid culture result for this visit.'),
 ('MTB_LiquidCulture_Speciation','','The species identified from liquid culture at this visit.'),
 ('MTB_SputumSmear_Result','','The sputum smear result for this visit.'),
 ('MTB_SputumSmear_Score','','The sputum smear grading score for this visit.'),
 ('Magnification','','The objective magnification used, e.g. 20x.'),
 ('Manufacturer','','The manufacturer of this material.'),
 ('Markers','','The fluorescent markers present in this cell line, e.g. H2B-EGFP, DsRed2.'),
 ('Material','','The material the device is made from, e.g. Polydimethylsiloxane (PDMS).'),
 ('Matrix','','The expression matrix file or the quantification unit it holds, e.g. FPKM.'),
 ('MatrixDataType','','Format of the matrix file, e.g. TSV.'),
 ('MaxPassage','','The highest passage number the cells were used at.'),
 ('MeasurementDuration','','How long the measurement ran for.'),
 ('MeasurementInterval','','The interval between successive measurements.'),
 ('MeasurementTechnique','','The technique used to take the reading, e.g. Colorimetric ELISA (450 nm).'),
 ('MeasurementType','','The kind of measurement made, e.g. Absorption.'),
 ('MeasurementWavelength','','The wavelength the measurement was read at, in nanometres.'),
 ('MeasurementWavelengthUnits','','Unit for the Measurement Wavelength value, e.g. nm.'),
 ('Media','','The culture medium and supplements the cells were grown in.'),
 ('MediaBase','','The base medium used, before supplements are added.'),
 ('MediaSource','','The vendor and catalogue number the medium was purchased from.'),
 ('MediaSupplements','','The supplements added to the base medium, with concentrations.'),
 ('Medications','','Whether the patient was on medication at this visit.'),
 ('MedicineHistory','','Whether the patient has a relevant medication history.'),
 ('MenstrualStage','','The phase of the menstrual cycle at sampling, e.g. secretory, proliferative.'),
 ('Metadata','','The per-cell metadata companion file of a sparse expression matrix, as a filename or URL.'),
 ('MetadataDataType','','Format of the metadata file named in Metadata, e.g. TSV.'),
 ('MetadataFile','','Path to the instrument metadata file for this acquisition.'),
 ('Methamphetamine_Use','','Whether the patient reports methamphetamine use.'),
 ('Methaqualone_Use','','Whether the patient reports methaqualone use.'),
 ('Method','','The analytical method used, e.g. LC-MS/MS.'),
 ('MinSeedingDensity','','The minimum cell density the culture was seeded at.'),
 ('MiniKnowVersion','','The version of MinKNOW used to run the sequencer.'),
 ('Mobility','','The patient''s recorded mobility status.'),
 ('ModCall','','The base modification called, e.g. 5mC.'),
 ('Mode','','The acquisition mode used, e.g. HighAccuracy400, ATR.'),
 ('ModelDescription','','Description of the model architecture used for this analysis.'),
 ('ModelName','','The name or version of the model or software used, e.g. RPN_RCN_roiExtractor.'),
 ('ModelType','','The class of model used, e.g. deep convolutional neural network.'),
 ('Model_Type','','The class of model used, e.g. Convolutional Neural Network.'),
 ('ModulationFrequency','','The modulation frequency the sensor was operated at.'),
 ('ModulationFrequencyUnits','','Unit for the Modulation Frequency value, e.g. Hz, hertz.'),
 ('MolecularStructure','','URL of the deposited molecular structure file.'),
 ('Morphology','','The morphology of the organism or cell type, e.g. Bacillus, epithelial.'),
 ('MortalityObservation','','When and under what circumstances the animal died.'),
 ('MostRecent_TB_Treatment_Completion','','Whether the patient completed their most recent TB treatment.'),
 ('Multiplicity','','The spin multiplicity used in the calculation.'),
 ('Mutation','','The genetic modification carried by these cells, e.g. WildType.'),
 ('MutationFreq','','The measured mutation frequency for this sample.'),
 ('N50','','The N50 read or contig length for this run.'),
 ('N50Units','','Unit for the N50 value, e.g. kb.'),
 ('NKC_Name','','The natural killer cell source used in this assay.'),
 ('Name','','The identifier the submitting lab uses for this sample.'),
 ('NecropsyDate','','The date the animal was necropsied.'),
 ('Needle','','The needle used to form the droplet, with gauge and material.'),
 ('NegativeControl','','The negative control used in this assay.'),
 ('NegativeControl_Catalog#','','The vendor''s catalogue number for the negative control, e.g. IT-001-37G12, A80-104P.'),
 ('NegativeControl_Vendor','','The vendor the negative control was purchased from, e.g. Immune Technology, Bethyl Laboratory.'),
 ('NegativeMatrix','','The matrix used for negative-mode imaging, e.g. NEDC.'),
 ('NegativeScope','','The analyte class targeted in negative mode, e.g. Metabolomics.'),
 ('New/Reccurent','','Whether this tumour is newly diagnosed or recurrent.'),
 ('NewGranulomaCount','','Number of new granulomas counted in this animal.'),
 ('NightSweatsCurr','','Whether the patient currently reports night sweats.'),
 ('Normalization','','How signal was normalized, e.g. total protein stain or a housekeeping protein.'),
 ('NormalizationGene','','The housekeeping gene used to normalize expression, e.g. PPIA.'),
 ('Note','','Free-text note about how this sample was prepared or handled.'),
 ('Notes','','Any additional information.'),
 ('NumAligned','','Number of reads that aligned to the reference.'),
 ('NumAliquot','','Number of aliquots this sample was split into.'),
 ('NumFoci','','Number of nuclear foci counted in this image.'),
 ('NumInjections','','Number of injections the animal received.'),
 ('NumPrepCycles','','Number of PCR cycles used during library preparation.'),
 ('NumReads','','Total number of reads produced for this sample.'),
 ('NumReadsUnits','','Unit for the Num Reads value, e.g. M.'),
 ('NumVials','','Number of vials this sample is stored in.'),
 ('NumberInfectedCells','','Number of cells infected in this experiment.'),
 ('ODFrozen','','The optical density the culture was at when frozen.'),
 ('ObjectArea','','Measured area of the segmented object in this image.'),
 ('ObjectiveLens','','The objective lens used, with magnification and numerical aperture.'),
 ('Organ','','The organ this sample was taken from, e.g. Lung, Spleen.'),
 ('OrganDetail','','More precise anatomical location within the organ named in Organ.'),
 ('Origin','','The geographic origin of the animal.'),
 ('Other_Respiratory_Pathogens','','Whether other respiratory pathogens were detected.'),
 ('Other_Respiratory_Pathogens_Bacteria','','Whether a bacterial respiratory pathogen other than TB was detected.'),
 ('Other_Respiratory_Pathogens_Number','','How many other respiratory pathogens were detected.'),
 ('Other_Respiratory_Pathogens_Virus','','Whether a viral respiratory pathogen was detected.'),
 ('OxidationCondition','','The oxidant the sample was exposed to, e.g. O3.'),
 ('PRIDE_ExperimentType','','The proteomics experiment type, as PRIDE classifies it, e.g. Shotgun proteomics.'),
 ('PRIDE_FileType','','The kind of file being deposited to PRIDE, e.g. RAW, SEARCH.'),
 ('PRIDE_Modification','','The peptide modifications searched for, as declared to PRIDE.'),
 ('PRIDE_Quantification','','The quantification method declared to PRIDE, e.g. TMT.'),
 ('PainDiscomfort','','Whether the patient reports pain or discomfort.'),
 ('Panel','','The antibody or analyte panel used for this run.'),
 ('Parent','','UID(s) of the sample(s) this one was derived from. Semicolon-separate when several.'),
 ('Parity','','The patient''s parity, i.e. number of births.'),
 ('Part','','Which part of the specimen this sample came from, e.g. B, C.'),
 ('ParticleComp','','The composition of the particles the sample was exposed to.'),
 ('PassageNotes','','Notes on how the cells should be passaged.'),
 ('PassageNum','','The passage number the cells were at.'),
 ('Passages','','How the cells were passaged, or the passage stage reached.'),
 ('Path_PrimaryData','','Filesystem path to the primary data file on the storage server.'),
 ('PathologyReport','','Whether a pathology report exists for this patient.'),
 ('PeakConcUnits','','Unit for the Peak Conc value, e.g. pg/uL, ng/uL.'),
 ('PerfusingDate','','The date perfusion of the device began.'),
 ('PerinatalHealth','','Whether there were perinatal health complications.'),
 ('Phage','','The phage strain used, e.g. lambda EG10.'),
 ('PhagocyticCells','','The phagocytic cell line used in this assay, e.g. THP-1.'),
 ('PhagocyticCells_Catalog#','','The vendor''s catalogue number for the phagocytic cells, e.g. TIB-202.'),
 ('PhagocyticCells_Vendor','','The vendor the phagocytic cells was purchased from, e.g. ATCC.'),
 ('Phenotype','','The observed phenotype of this subject or cell line, e.g. Epithelial, LTBI.'),
 ('Pipeline','','The analysis pipeline used, e.g. nf-core/rnaseq, cellranger.'),
 ('PipelineVersion','','The version of the analysis pipeline used.'),
 ('PlaqueTiter','','The strain used to titer plaques, e.g. XL-1 Blue MRA.'),
 ('PlaqueTiterCount','','Number of plaques counted during titering.'),
 ('Plate','','Identifier of the assay plate this sample was run on.'),
 ('PlateBlocker','','The blocking agent used on the plate, e.g. 5% BSA-PBS.'),
 ('PlateBlockerProcedure','','How the plate was blocked, including time and temperature.'),
 ('PlateDesign_File','','Filename of the plate layout for this run.'),
 ('PlateDesign_Link','','URL where the plate layout file can be downloaded.'),
 ('PlateWash','','The wash buffer used between plate steps, e.g. PBS Tween 0.5%.'),
 ('Plate_Catalog#','','The vendor''s catalogue number for the plate, e.g. 63494, 269620 439454.'),
 ('Plate_Vendor','','The vendor the plate was purchased from, e.g. Thermo Fisher Scientific, ThermoFisher.'),
 ('Polysubstances_Use','','Whether the patient reports use of multiple substances.'),
 ('PositiveMatrix','','The matrix used for positive-mode imaging, e.g. DHB.'),
 ('PositiveScope','','The analyte targeted in positive mode.'),
 ('PostOpDiagnosis','','The patient''s diagnosis after surgery.'),
 ('PostOpLMP','','Date of the patient''s last menstrual period after surgery.'),
 ('Pregnant','','Whether the patient was pregnant at the time of sampling.'),
 ('Previous_COVID19','','Whether the patient had a previous COVID-19 infection.'),
 ('PrimaryAntibody','','The primary antibody used, e.g. STAT1, PCNA, pH2AX.'),
 ('PrimerSequences','','The primer sequences used, or a pointer to the table listing them.'),
 ('PrimerSource','','Where the primers were obtained, e.g. Integrated DNA Technologies.'),
 ('Procedure','','The clinical or lab procedure that produced this sample, e.g. Bronchoalveolar lavage.'),
 ('ProcedureDuration','','How long the procedure took, in minutes.'),
 ('Product#','','The manufacturer''s product number for this kit or reagent.'),
 ('ProductNumber','','The manufacturer''s product number for this chemical.'),
 ('ProteinAmount','','Amount of protein in this sample, in micrograms.'),
 ('ProteinSeqFile','','Filename of the protein sequence database searched against.'),
 ('Protocol','','The SOP followed, as a filename or a link to the SOP record. BMC data specialists can handle this section if given all protocols used.'),
 ('Protocol2','','An additional SOP followed for this sample, beyond the one named in Protocol.'),
 ('Protocol3','','A third SOP followed for this sample, beyond those in Protocol and Protocol2.'),
 ('Protocol_Device','','The SOP describing device fabrication or setup. BMC data specialists can handle this section if given all protocols used.'),
 ('Protocol_Stimulation','','The SOP describing the stimulation step. BMC data specialists can handle this section if given all protocols used.'),
 ('Protocol_Treatment','','The SOP describing the treatment step. BMC data specialists can handle this section if given all protocols used.'),
 ('Provider','','The supplier the animal was obtained from, e.g. JAX.'),
 ('ProviderProduct#','','The provider''s catalogue number for this animal strain, e.g. #000664.'),
 ('Pseudo_Aligner','','The pseudo-aligner used for quantification, e.g. Salmon.'),
 ('Publish_uri','','Public URL where this sample record is published.'),
 ('PurificationKit','','The kit used to purify the target molecules.'),
 ('PurificationKit_Vendor','','The vendor the purification kit was purchased from, e.g. Thermo Fisher Scientific.'),
 ('QC','','The quality control measurement recorded for this sample.'),
 ('QCInstrument','','The instrument used for quality control, e.g. Q Exactive HFX.'),
 ('QCPlatform','','The platform used for library quality control, e.g. Agilent Fragment Analyzer.'),
 ('QCUser','','The person who performed quality control on this sample.'),
 ('QC_Instrument','','The instrument used to quality-check this sample, e.g. FemtoPulse.'),
 ('QFN_Data','','The QuantiFERON result recorded at this visit.'),
 ('QFT_Result','','The patient''s QuantiFERON-TB result.'),
 ('Qtag','','The quantification tag sequence used for this strain.'),
 ('QualityHealth','','The patient''s self-reported quality of health.'),
 ('QuantificationMethod','','The method used to quantify, e.g. TMT10plex, Scaffold Q+.'),
 ('RADR_Count','','Count of RaDR foci measured in this image.'),
 ('RIN','','The RNA Integrity Number for this sample, from 1 to 10.'),
 ('RRID','','The Research Resource Identifier for this antibody, e.g. AB_394293.'),
 ('R_bp','','Read length in base pairs of the reverse mate. Leave blank for single-end runs.'),
 ('Race','','The patient''s self-reported race.'),
 ('RadiationSource','','The X-ray source used, e.g. Al K-alpha.'),
 ('RandomGlucoseTest','','Whether a random glucose test was done at this visit.'),
 ('RandomGlucoseTest_Reading','','The random glucose reading taken at this visit.'),
 ('RandomGlucoseTest_Units','','Unit for the Random Glucose Test value.'),
 ('ReactionStopper','','The solution used to stop the reaction, e.g. 2N H2SO4.'),
 ('ReadingIntervals','','When readings were taken relative to the start of the experiment.'),
 ('Reagent','','The catalogue number of the reagent used.'),
 ('ReagentBrand','','The brand and product name of the reagent used.'),
 ('ReagentCatalogNum','','The manufacturer''s catalogue number for this reagent.'),
 ('ReagentManufacturer','','The manufacturer of the main reagent or kit used.'),
 ('ReceiptDate','','The date this sample was received.'),
 ('ReceiptNotes','','Notes recorded when the sample was received, e.g. condition on arrival.'),
 ('RecordDate','','The date this record was created.'),
 ('RecoveryStandard','','The isotopically labelled standard spiked in to measure recovery, e.g. N15-NDMA.'),
 ('RecoveryStandardAddedWithinHours','','How many hours after collection the recovery standard was added.'),
 ('RecoveryStandardConcNgPerL','','Concentration of recovery standard added, in nanograms per litre.'),
 ('RecruitDate','','The date the patient was recruited.'),
 ('RecruitReason','','Why the patient was recruited, e.g. Contact.'),
 ('Reference','','URL or citation for the source of this material or method.'),
 ('ReferenceCompound','','The reference compound this measurement was made against.'),
 ('ReferenceGenome','','The reference genome used for alignment.'),
 ('ReferenceGenomeSource','','Path or source the reference genome was obtained from.'),
 ('ReferenceGenome_Link','','URL where the reference genome can be downloaded.'),
 ('Region','','The genomic or physical region this sample covers.'),
 ('RegionType','','The kind of tissue region sampled, e.g. Tumor Punch.'),
 ('Relationship','','How this subject relates to others in the study, e.g. a dyad pairing.'),
 ('Relationship_To_TBCase','','The patient''s relationship to the index TB case.'),
 ('RelativeHumidity','','Relative humidity during the exposure, as a percentage.'),
 ('Replicate','','Which replicate this sample is.'),
 ('Replicates','','How many replicates were run.'),
 ('Reporter','','The reporter or detection conjugate used, e.g. Alexa Fluor 647.'),
 ('Repository','','The public repository this data was deposited in, e.g. SRA, dbGaP.'),
 ('RepositoryID','','The accession assigned by the repository this data was deposited in, e.g. GSM6455810.'),
 ('RepositoryLink','','URL of this record in the public repository it was deposited to.'),
 ('RunDuration','','How long the sensor deployment ran, in minutes.'),
 ('RunDurationUnits','','Unit for the Run Duration value, e.g. min, minute.'),
 ('RunStartTime','','Clock time at which the run started.'),
 ('SMILES','','The SMILES string describing this compound''s structure.'),
 ('SacrificeDate','','The date the animal was sacrificed.'),
 ('SacrificeDescription','','The circumstances of the animal''s sacrifice, e.g. Moribund Sacrifice.'),
 ('SampleCollectionDate','','The date this sample was collected.'),
 ('SampleCreationDate','','The date this sample itself was created, as distinct from when the record was entered.'),
 ('SamplePreperation','','How the sample was prepared before analysis.'),
 ('SampleSite','','The field location this sample was collected from.'),
 ('SampleSource','','What the sample was derived from, e.g. Patient tumor, PBMC.'),
 ('ScanFile','','Path to the raw scan file for this acquisition.'),
 ('ScanID','','Identifier of the imaging scan for this visit.'),
 ('ScanMode','','The scanning mode used, e.g. Height Mode.'),
 ('Scarring','','Whether lung scarring was observed.'),
 ('Scientist','','The lab member responsible for this sample.'),
 ('SecondaryAntibody','','The secondary antibody used, including its conjugate.'),
 ('SecondaryAntibodyLink','','URL of the vendor page for the secondary antibody.'),
 ('Section#','','Which section of the block this slide came from.'),
 ('SeedingDate','','The date the device or culture was seeded.'),
 ('SelectionTemperature','','Temperature the selection step was carried out at.'),
 ('Selector','','The selector molecule used by the sensor.'),
 ('SelfCare','','The patient''s self-reported ability to perform self-care.'),
 ('SenseAntisenseRatio','','Ratio of sense to antisense reads, a strand-specificity measure.'),
 ('SensingVolumeSeparation','','Separation of the sensor''s sensing volume, in the units used by this deployment.'),
 ('SensingVolumeSeparationUnits','','Unit for the Sensing Volume Separation value, e.g. mm, millimeter.'),
 ('Sequencer','','The sequencing instrument model, e.g. Illumina NovaSeq 6000.'),
 ('SequencingFacility','','The facility that performed the sequencing, e.g. BMC.'),
 ('SequencingFacilityLocation','','Where the sequencing facility is located.'),
 ('SequencingType','','NExtSEEK''s internal label for the assay family, e.g. Single Cell RNA Sequencing.'),
 ('Sex','','The subject''s sex.'),
 ('ShipDate','','The date this sample was shipped.'),
 ('ShipDestination','','Where the sample was shipped to, including the receiving box and position, e.g. HSPH-Sept2024-BOX 1 (PLASMA)-A9.'),
 ('ShipID','','The shipment identifier this sample travelled under, e.g. SHIP-04826.'),
 ('ShipNotes','','Notes about this sample''s shipment or storage before shipping.'),
 ('ShipOrigin','','The site the sample was shipped from.'),
 ('ShippingTemperatures_Origin','','Minimum and maximum temperatures logged at the origin before shipping.'),
 ('ShoreDist','','Distance from the sensor to shore, in the units used by this deployment.'),
 ('ShoreDistUnits','','Unit for the Shore Dist value, e.g. m, meter.'),
 ('Signatures','','The mutational signature set used, e.g. COSMIC v3.4.'),
 ('SimulationData','','UID(s) of the simulation records associated with this sensor. Semicolon-separate when several.'),
 ('SingleCellFile','','Path to the per-cell results file for this acquisition.'),
 ('SingleStain_Control','','The single-stain compensation control file for this marker.'),
 ('Size','','The measured size of the library or fragment, in base pairs.'),
 ('SlideAntibodyConcentration','','The concentration or dilution the slide antibody was used at, e.g. 1:200.'),
 ('SlideStain','','The primary stain applied to this slide, e.g. H&E, DAB.'),
 ('SlideStain2','','A second stain applied to this slide, e.g. DAPI, Hematoxylin.'),
 ('Smear_Result','','The patient''s sputum smear result.'),
 ('Smoke','','Whether the patient reports smoking.'),
 ('SmokeDuration','','How long the patient has smoked.'),
 ('SmokeDuration_Units','','Unit for the Smoke Duration value.'),
 ('Software','','The analysis software used, with version where known, e.g. FlowJo 10.8.1.'),
 ('SolidCulture','','The patient''s solid culture result.'),
 ('Solvent','','The solvent the sample was dissolved in, e.g. CDCl3.'),
 ('Source','','Where this material was obtained from, e.g. ATCC, Lonza.'),
 ('SourceCode','','URL or filename of the analysis source code.'),
 ('SourceCode_Link','','URL where the analysis source code can be downloaded.'),
 ('SourceDataFile','','URL of the published source data file behind this figure.'),
 ('SourceFacility','','The facility the animal or material was obtained from, e.g. Jackson Laboratories.'),
 ('SourceTap','','The tap or outlet this water sample was drawn from.'),
 ('Source_Vendor','','The vendor the source was purchased from, e.g. Dr Koen Van Rompay, CNPRC, UC Davis.'),
 ('SpaceGroup','','The crystallographic space group, e.g. Pbca.'),
 ('Species','','The species, as the scientific binomial where possible, e.g. Macaca mulatta.'),
 ('Stain','','The stain applied to this slide, e.g. H&E.'),
 ('Staining_Antibody','','The antibody used to stain this sample, e.g. CD66b antibody.'),
 ('Staining_Antibody_Fluorophore','','Fluorophore conjugated to the staining antibody, e.g. Pacific Blue.'),
 ('Staining_Antibody_Vendor','','The vendor the staining antibody was purchased from, e.g. BioLegend.'),
 ('Stains','','All stains applied to this tissue, comma-separated.'),
 ('Standard','','The reference standard run alongside the samples, e.g. Polystyrene.'),
 ('StatusBCGVaccination','','The patient''s BCG vaccination status.'),
 ('StatusCOVID','','The patient''s COVID-19 status at sampling.'),
 ('StatusHIV','','The patient''s HIV status.'),
 ('Stimulation','','What the cells were stimulated with, e.g. Unstimulated, BCG.'),
 ('StimulationDate','','The date the stimulation was performed.'),
 ('StorageDate','','The date this sample was placed into storage.'),
 ('StorageLocation','','Where this sample is physically stored.'),
 ('StorageSite','','The freezer or cryotank this sample is stored in.'),
 ('StorageTempC','','The temperature this sample is stored at, in degrees Celsius.'),
 ('StorageTempMax','','The highest temperature this material may be stored at, in degrees Celsius.'),
 ('StorageTempMin','','The lowest temperature this material may be stored at, in degrees Celsius.'),
 ('StorageTempUnits','','Unit for the Storage Temp value, e.g. Celsius.'),
 ('StorageType','','The medium or buffer this sample is stored in, e.g. DMEM with 5% DMSO.'),
 ('StoredOnIceInField','','Whether the sample was kept on ice between collection and the lab.'),
 ('Strain','','The strain designation of the animal or organism, e.g. C57BL/6J, H37Rv.'),
 ('Study','','The study this sample belongs to.'),
 ('StudyDesign','','The study timeline for this subject, as dated events.'),
 ('StudyID','','The study this sample belongs to, e.g. CD8Depletion.'),
 ('SubjectLocation','','The country or site the subject was enrolled at.'),
 ('Substance_Use','','Whether the patient reports substance use.'),
 ('Substrain','','The specific substrain used, including any plasmid it carries.'),
 ('Supplier','','The supplier the material was purchased or obtained from.'),
 ('Supporting_Files','','Filenames of supporting files that accompany this run.'),
 ('Supporting_Links','','Storage location of the supporting files for this run.'),
 ('Surgery','','Whether the patient has undergone surgery.'),
 ('SurgeryTimepoint','','Which surgery this sample was taken at, e.g. Surgery 1.'),
 ('SurvivalTime','','How long the animal survived, or the date it reached endpoint.'),
 ('Symptoms','','The symptoms the patient reported.'),
 ('Symptoms_LastPositiveCOVID19','','The symptoms the patient had at their most recent positive COVID-19 test.'),
 ('SynthesisKit','','The kit used to synthesise cDNA, with catalogue number and vendor.'),
 ('Syringe','','The syringe used to dispense the sample, with make and model.'),
 ('TB_History','','Whether the patient has a history of TB.'),
 ('TB_Recurrence','','Whether the patient''s TB recurred.'),
 ('TB_Recurrence_Window','','The window in which the patient''s TB recurrence was assessed.'),
 ('TNFa_Ab_Catalog#','','The vendor''s catalogue number for the tnfa ab, e.g. 502936.'),
 ('TNFa_Ab_Fluorophore','','Fluorophore conjugated to the anti-TNF-alpha antibody, e.g. BV605.'),
 ('TNFa_Ab_Vendor','','The vendor the tnfa ab was purchased from, e.g. BioLegend.'),
 ('TNFa_Name','','Full product name of the anti-TNF-alpha antibody used.'),
 ('TOCEnd','','Total organic carbon measured at the end of the deployment.'),
 ('TOCEndTime','','Clock time at which the end-of-deployment TOC reading was taken.'),
 ('TOCStart','','Total organic carbon measured at the start of the deployment.'),
 ('TOCStartTime','','Clock time at which the start-of-deployment TOC reading was taken.'),
 ('TOCUnits','','Unit for the TOC value, e.g. ppm, parts per million.'),
 ('TST_Result','','The patient''s tuberculin skin test result.'),
 ('TTDCulture','','The time-to-detection result from culture.'),
 ('Targets','','The molecular targets imaged or assayed, comma-separated.'),
 ('TaxonomyID','','The NCBI Taxonomy identifier for the organism, e.g. 83332 for M. tuberculosis H37Rv.'),
 ('Temperature','','The temperature this measurement was made at, in degrees Celsius.'),
 ('TemperatureCalibrationDate','','The date the sensor''s temperature channel was last calibrated.'),
 ('TemperatureCalibrationUnits','','Unit for the Temperature Calibration value, e.g. ADC counts to C, ADC counts to celsius.'),
 ('TemperatureCompensationCoefficientConductivity','','Coefficient used to temperature-compensate the conductivity reading.'),
 ('TemperatureEnd','','Temperature recorded at the end of the deployment.'),
 ('TemperatureEndTime','','Clock time at which the end-of-deployment temperature reading was taken.'),
 ('TemperatureLinearCalibrationIntercept','','Intercept of the linear calibration applied to the temperature channel.'),
 ('TemperatureLinearCalibrationSlope','','Slope of the linear calibration applied to the temperature channel.'),
 ('TemperatureStart','','Temperature recorded at the start of the deployment.'),
 ('TemperatureStartTime','','Clock time at which the start-of-deployment temperature reading was taken.'),
 ('TemperatureUnits','','Unit for the Temperature value, e.g. C, celsius.'),
 ('TestResult','','The result of the test named in TestType.'),
 ('TestResult2','','The result of the test named in TestType2.'),
 ('TestResult3','','The result of the test named in TestType3.'),
 ('TestResult4','','The result of the test named in TestType4.'),
 ('TestResultFile','','Filename of the report holding this visit''s test results.'),
 ('TestType','','The test performed at this visit, e.g. QuantiFERON-TB Gold.'),
 ('TestType2','','A second test performed at this visit, e.g. TST.'),
 ('TestType3','','A third test performed at this visit.'),
 ('TestType4','','A fourth test performed at this visit.'),
 ('ThermistorRheostatSetting','','The rheostat setting used for the sensor''s thermistor.'),
 ('ThermometerEnd','','The kind of thermometer used for the end-of-deployment reading, e.g. glass, digital.'),
 ('ThermometerStart','','The kind of thermometer used for the start-of-deployment reading.'),
 ('TimeInterval','','The interval between successive images or readings.'),
 ('TimeOfDetection','','Whether detection occurred early or late in the time course.'),
 ('TimeSinceBCGVax','','How long before sampling the patient received BCG vaccination.'),
 ('TimeSinceCOVID','','How long before sampling the patient had COVID-19.'),
 ('TimeToTB','','Time from enrolment to TB diagnosis.'),
 ('TimeToTBUnits','','Unit for the Time To TB value, e.g. Day.'),
 ('Timepoint','','When this sample was taken relative to the start of the experiment, e.g. 24 hours.'),
 ('Timepoints','','The timepoints pooled or covered by this sample.'),
 ('Tissue','','The tissue this sample was derived from, e.g. Large intestine, Bone.'),
 ('Titer','','The measured titer of this preparation, e.g. 3.03e7/ul.'),
 ('TiterEfficiency','','The titering efficiency measured for this sample, as a percentage.'),
 ('Top30CountPercent','','Fraction of reads accounted for by the 30 most abundant features.'),
 ('TotalCFU','','Colony forming units summed across all tissues sampled.'),
 ('TotalEnergy','','Total energy from the quantum chemistry calculation.'),
 ('TotalEnergyUnits','','Unit for the Total Energy value, e.g. Hartree.'),
 ('TotalLungFDGActivity','','Total FDG activity measured across the lung on PET/CT.'),
 ('TotalLungFDGActivityUnits','','Unit for the Total Lung FDGActivity value, e.g. Based on a calculation (SUV).'),
 ('TotalPathologyScore','','Pathology score summed across all tissues scored.'),
 ('TotalReads','','Total number of reads produced, or the target range requested.'),
 ('TotalTime','','Total duration of the acquisition.'),
 ('TrainingDatasets','','The datasets this model was trained on.'),
 ('TravelHistory','','The patient''s relevant travel history, with destinations and dates.'),
 ('Treatment','','What this sample was treated with, e.g. Mtb infection, Unstimulated.'),
 ('Treatment1','','What the first treatment was.'),
 ('Treatment1Date','','When the first treatment was administered.'),
 ('Treatment1Dose','','How much of the first treatment was given. The units are named in Treatment1DoseUnits.'),
 ('Treatment1DoseUnits','','Unit for the Treatment1Dose value, e.g. ug/ml.'),
 ('Treatment1Parent','','UID of the sample used as the first treatment agent, e.g. the antibody or bacterial stock.'),
 ('Treatment1Protocol','','The SOP followed for treatment1. BMC data specialists can handle this section if given all protocols used.'),
 ('Treatment1Reference','','URL or citation describing the first treatment agent.'),
 ('Treatment1Route','','How the first treatment was administered, e.g. intravenously.'),
 ('Treatment1Time','','How long the first treatment was applied for.'),
 ('Treatment1TimeUnits','','Unit for the Treatment1 Time value, e.g. Days.'),
 ('Treatment1Type','','The category of the first treatment, e.g. Antibody, Infection, Control.'),
 ('Treatment2','','What the second treatment was.'),
 ('Treatment2Date','','When the second treatment was administered.'),
 ('Treatment2Dose','','How much of the second treatment was given. The units are named in Treatment2DoseUnits.'),
 ('Treatment2DoseRule','','The rule used to calculate the second treatment dose, e.g. by individual body weight.'),
 ('Treatment2DoseUnits','','Unit for the Treatment2Dose value, e.g. mg.'),
 ('Treatment2Parent','','UID of the sample used as the second treatment agent.'),
 ('Treatment2Reference','','URL or citation describing the second treatment agent.'),
 ('Treatment2Route','','How the second treatment was administered, e.g. Intramuscularly.'),
 ('Treatment2Type','','The category of the second treatment, e.g. Stimulation, Vaccination.'),
 ('Treatment3','','What the third treatment was.'),
 ('Treatment3Date','','When the third treatment was administered.'),
 ('Treatment3Dose','','How much of the third treatment was given. The units are named in Treatment3DoseUnits.'),
 ('Treatment3DoseUnits','','Unit for the Treatment3 Dose value, e.g. mg, milligram.'),
 ('Treatment3Parent','','UID of the sample used as the third treatment agent.'),
 ('Treatment3Route','','How the third treatment was administered, e.g. Intravenously.'),
 ('Treatment3Type','','The category of the third treatment, e.g. Antibody, Medication.'),
 ('Treatment4','','What the fourth treatment was.'),
 ('Treatment4Date','','When the fourth treatment was administered.'),
 ('Treatment4Dose','','How much of the fourth treatment was given. The units are named in Treatment4DoseUnits.'),
 ('Treatment4DoseUnits','','Unit for the Treatment4 Dose value, e.g. milligram, mg/kg.'),
 ('Treatment4Parent','','UID of the sample used as the fourth treatment agent.'),
 ('Treatment4Route','','How the fourth treatment was administered, e.g. Orally.'),
 ('Treatment4Type','','The category of the fourth treatment, e.g. Medication, Antibody.'),
 ('Treatment5','','What the fifth treatment was.'),
 ('Treatment5Dose','','How much of the fifth treatment was given.'),
 ('Treatment5DoseUnits','','Unit for the Treatment5 Dose value, e.g. milliliter.'),
 ('Treatment5Route','','How the fifth treatment was administered.'),
 ('Treatment5Type','','The category of the fifth treatment, e.g. Control.'),
 ('TreatmentDose','','How much of the treatment was given, in the units used by this assay.'),
 ('TreatmentDoseTime','','How long after dosing this sample was taken.'),
 ('TreatmentDoseUnits','','Unit for the Treatment Dose value, e.g. CFU, ng/mL.'),
 ('TreatmentRoute','','How the treatment was applied, e.g. Add to media.'),
 ('TreatmentTime','','How long the treatment was applied for.'),
 ('TreatmentTimeUnits','','Unit for the Treatment Time value, e.g. Day, Overnight.'),
 ('TreatmentType','','The category of treatment applied, e.g. Chemical, Infection.'),
 ('Treatment_LastPositiveCOVID19','','The treatment given at the patient''s most recent positive COVID-19 episode.'),
 ('Treatment_Outcome','','The outcome of the patient''s treatment.'),
 ('Trimmer','','The tool used to trim reads, e.g. fastxtoolkit/0.0.13.'),
 ('Tube','','Identifier of the tube this sample is held in.'),
 ('TubeNumber','','The tube number this sample is held in.'),
 ('TumorFractionFromCNV','','Estimated tumour fraction inferred from copy-number data, as a percentage.'),
 ('TumorWeight','','The weight of the excised tumour, in grams.'),
 ('TumorWeightUnits','','Unit for the Tumor Weight value, e.g. grams, milligrams.'),
 ('Tumor_Grade','','The histological grade of the tumour.'),
 ('Tumor_IDH','','The tumour''s IDH mutation status, e.g. Wild type.'),
 ('Type','','The subtype of this sample within its sample type, e.g. Blood, Tissue Extraction.'),
 ('UID','','The unique NExtSEEK identifier for this sample. Its prefix is the sample type code. BMC data specialist will create them for new samples.'),
 ('UTRPercent','','Fraction of reads mapping to untranslated regions.'),
 ('UltraSoundDesc','','The ultrasound findings recorded for this patient.'),
 ('UncompensatedConductivityEnd','','Raw, temperature-uncompensated conductivity at the end of the deployment.'),
 ('UncompensatedConductivityStart','','Raw, temperature-uncompensated conductivity at the start of the deployment.'),
 ('UncompensatedConductivityUnits','','Unit for the Uncompensated Conductivity value, e.g. uS/cm, microsiemens per centimeter.'),
 ('UsualActivity','','The patient''s self-reported ability to carry out usual activities.'),
 ('VaccinationHistory','','The patient''s vaccination history.'),
 ('ValidationDatasets','','UID(s) of the datasets this model was validated against. Semicolon-separate when several.'),
 ('ValidationMethod','','The method used to validate the cells, e.g. MycoAlert Mycoplasma detection kit.'),
 ('ValidationQuality','','The outcome of validation, e.g. Mycoplasma negative.'),
 ('VariantCaller','','The tool used to call variants, e.g. Mutect2 (GATK).'),
 ('Vascularization','','The vascularization process modelled in this device, e.g. Angiogenesis.'),
 ('Vendor','','The vendor the reagent or antibody was purchased from.'),
 ('Viability%','','Percentage of cells that were viable.'),
 ('ViableCellCount','','Number of viable cells counted.'),
 ('Vial#','','Which vial of the set this sample is.'),
 ('VialID','','The barcode or identifier printed on the vial.'),
 ('ViralLoad','','The patient''s measured viral load.'),
 ('VisibleLesion1_PETCT_ActiveTB','','Whether the first visible lesion showed active TB on PET/CT.'),
 ('VisibleLesion1_PETCT_FDG','','FDG uptake measured for the first visible lesion on PET/CT.'),
 ('VisibleLesion1_PETCT_Location','','Anatomical location of the first visible lesion on PET/CT.'),
 ('VisibleLesion1_Total_Glycolytic_Activity','','Total glycolytic activity of the first visible lesion.'),
 ('VisibleLesion2_PETCT_ActiveTB','','Whether the second visible lesion showed active TB on PET/CT.'),
 ('VisibleLesion2_PETCT_FDG','','FDG uptake measured for the second visible lesion on PET/CT.'),
 ('VisibleLesion2_PETCT_Location','','Anatomical location of the second visible lesion on PET/CT.'),
 ('VisibleLesion2_Total_Glycolytic_Activity','','Total glycolytic activity of the second visible lesion.'),
 ('VisibleLesion3_PETCT_ActiveTB','','Whether the third visible lesion showed active TB on PET/CT.'),
 ('VisibleLesion3_PETCT_FDG','','FDG uptake measured for the third visible lesion on PET/CT.'),
 ('VisibleLesion3_PETCT_Location','','Anatomical location of the third visible lesion on PET/CT.'),
 ('VisibleLesion3_Total_Glycolytic_Activity','','Total glycolytic activity of the third visible lesion.'),
 ('VisibleLesion4_PETCT_ActiveTB','','Whether the fourth visible lesion showed active TB on PET/CT.'),
 ('VisibleLesion4_PETCT_FDG','','FDG uptake measured for the fourth visible lesion on PET/CT.'),
 ('VisibleLesion4_PETCT_Location','','Anatomical location of the fourth visible lesion on PET/CT.'),
 ('VisibleLesion4_Total_Glycolytic_Activity','','Total glycolytic activity of the fourth visible lesion.'),
 ('Visible_Lesions_PETCT','','Whether any lesions were visible on PET/CT at this visit.'),
 ('VisitFacility','','The facility where this visit or collection took place.'),
 ('VisitLocation','','Where this visit took place, e.g. Kampala UG.'),
 ('Volume','','The volume of this sample, in the units used by this assay.'),
 ('VolumeCollectedL','','Volume of water collected, in litres.'),
 ('VolumeUnits','','Unit for the Volume value, e.g. cubic angstrom, milliliter.'),
 ('WaterDepth','','Depth of water at the sensor location.'),
 ('WaterDepthUnits','','Unit for the Water Depth value, e.g. cm, centimeter.'),
 ('Waterpipe_Use','','Whether the patient reports waterpipe use.'),
 ('Wavelength','','The wavelength used for this measurement, in nanometres.'),
 ('WavelengthUnits','','Unit for the Wavelength value, e.g. nm, nanometer.'),
 ('Wavelengths','','The excitation wavelengths used, and what each one images.'),
 ('WeeksSincePrimaryIntervention','','Weeks between the primary intervention and this sample. Negative values are before it.'),
 ('Weight','','The subject''s weight, in the units named in Weight_Units.'),
 ('WeightLoss6mo','','Whether the patient reported weight loss in the last six months.'),
 ('Weight_Units','','Unit for the Weight value, e.g. kilograms, kg.'),
 ('WellID','','The plate well this sample occupied, e.g. SI-TT-G2.'),
 ('Who4Symptoms','','Whether the patient reported any of the WHO four TB screening symptoms.'),
 ('Yield','','The amount of material or data produced by this run.'),
 ('YieldUnits','','Unit for the Yield value, e.g. Gbp.'),
 ('anti_IgX_Ab','','The anti-immunoglobulin detection antibody used, e.g. IgG1.'),
 ('anti_IgX_Ab_Catalog#','','The vendor''s catalogue number for the anti ig x ab, e.g. 9054-02, 9060-09.'),
 ('anti_IgX_Ab_vendor','','The vendor the anti-immunoglobulin antibody was purchased from.'),
 ('bead_catalog#','','The vendor''s catalogue number for the beads used.'),
 ('capturekit_catalog#','','The vendor''s catalogue number for the capture kit used.'),
 ('digestiveenzyme_catalog#','','The vendor''s catalogue number for the digestive enzyme used.'),
 ('figure','','The manuscript figure this image appears in.'),
 ('filter_catalog#','','The vendor''s catalogue number for the filter used.'),
 ('isolationkit_catalog#','','The vendor''s catalogue number for the isolation kit used.'),
 ('labellingkit_catalog#','','The vendor''s catalogue number for the labelling kit used.'),
 ('ladder_catalog#','','The vendor''s catalogue number for the size ladder used.'),
 ('purificationkit_catalog#','','The vendor''s catalogue number for the purification kit used.'),
 ('rRNAPercent','','Fraction of reads mapping to ribosomal RNA, a measure of rRNA carryover.')
ON DUPLICATE KEY UPDATE meaning=VALUES(meaning);
