"""Generate chat_nextseek/.env from sibling NExtSEEK docker + dmac sources.

Default target: docker-local (running inside the nextseek docker container).
Other targets (prod, docker-local-from-host) deferred to future iterations.
"""
from __future__ import annotations

import ast
import re
from datetime import datetime, timezone
from pathlib import Path


def _find_repo_root(start: Path) -> Path:
    """Walk up from `start` until we find a dir containing both docker/db.env and dmac/local_settings.py.

    In the canonical layout this is chat_nextseek/../ (NExtSEEK/). In a git worktree
    (e.g. NExtSEEK/.claude/worktrees/<branch>/chat_nextseek/) chat_nextseek/.. points
    into the worktree dir, not the actual repo, so we keep walking.
    """
    for candidate in (start, *start.parents):
        if (candidate / "docker" / "db.env").exists() and (candidate / "dmac" / "local_settings.py").exists():
            return candidate
    # Fall back to the canonical parent-of-chat_nextseek layout so paths still
    # render in error messages even when sources are missing.
    return start.parent.parent.parent  # e2e/import_env.py -> e2e/ -> chat_nextseek/ -> NExtSEEK/


REPO_ROOT = _find_repo_root(Path(__file__).resolve())
DB_ENV_PATH = REPO_ROOT / "docker" / "db.env"
NEXTSEEK_ENV_PATH = REPO_ROOT / "docker" / "nextseek.env"
LOCAL_SETTINGS_PATH = REPO_ROOT / "dmac" / "local_settings.py"


def _read_env_file(path: Path) -> dict[str, str]:
    """Read a shell-style .env file. Handles `KEY="value"`, `KEY=value`, blank lines, comments."""
    out: dict[str, str] = {}
    if not path.exists():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, val = line.split("=", 1)
        val = val.strip()
        # Strip surrounding quotes (single or double)
        if len(val) >= 2 and val[0] == val[-1] and val[0] in ('"', "'"):
            val = val[1:-1]
        out[key.strip()] = val
    return out


def _interpolate(value: str, env: dict[str, str]) -> str:
    """Replace $VAR and ${VAR} with values from env. Unset vars become empty string."""
    def repl(m: re.Match) -> str:
        name = m.group(1) or m.group(2)
        return env.get(name, "")
    return re.sub(r"\$\{(\w+)\}|\$(\w+)", repl, value)


def load_docker_env() -> dict[str, str]:
    """Read db.env + nextseek.env, then interpolate $VAR refs in nextseek.env using db.env values."""
    db = _read_env_file(DB_ENV_PATH)
    nextseek = _read_env_file(NEXTSEEK_ENV_PATH)
    merged = {**db, **nextseek}  # nextseek overrides db where keys collide
    return {k: _interpolate(v, merged) for k, v in merged.items()}


def load_prod_overrides() -> dict[str, str]:
    """Parse _PROD_OVERRIDES dict from dmac/local_settings.py via AST (no exec)."""
    if not LOCAL_SETTINGS_PATH.exists():
        return {}
    tree = ast.parse(LOCAL_SETTINGS_PATH.read_text(encoding="utf-8"))
    for node in ast.walk(tree):
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.target.id == "_PROD_OVERRIDES":
            value = node.value
            if isinstance(value, ast.Dict):
                out: dict[str, str] = {}
                for k_node, v_node in zip(value.keys, value.values):
                    if isinstance(k_node, ast.Constant) and isinstance(k_node.value, str):
                        if isinstance(v_node, ast.Constant) and isinstance(v_node.value, str):
                            out[k_node.value] = v_node.value
                return out
    return {}


def render_dotenv(target: str = "docker-local") -> str:
    """Build the .env file content for the given target."""
    if target != "docker-local":
        raise ValueError(f"Only target='docker-local' is supported in v1; got {target!r}")

    # docker_env is loaded for parity / future use (e.g. future targets that
    # emit the full interpolated env). For docker-local we only need it to
    # confirm sources parse cleanly; the container env_file: already loads it.
    _docker_env = load_docker_env()
    prod = load_prod_overrides()
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines: list[str] = [
        f"# Auto-generated by e2e/import_env.py at {ts}",
        f"# Target: docker-local (executed via: docker exec -it nextseek uv run e2e.py)",
        f"# Sources:",
        f"#   docker/db.env (interpolated into nextseek.env $VAR refs)",
        f"#   docker/nextseek.env",
        f"#   dmac/local_settings.py::_PROD_OVERRIDES (commented out below; uncomment for prod target)",
        f"#",
        f"# Inside the nextseek container, docker-compose env_file: already loads most of nextseek.env.",
        f"# This .env fills the API_USER/API_PASS gap and forces SESSION_DB_TYPE=sqlite for the runner.",
        f"#",
        f"# Note: chat_nextseek/src/chat_nextseek/config.py calls load_dotenv() with the default",
        f"# override=False, so values defined in the container's existing environment will WIN over",
        f"# values in this .env. To make SESSION_DB_TYPE=sqlite actually take effect, either:",
        f"#   (a) invoke via Python and call load_dotenv(override=True) yourself, or",
        f"#   (b) unset the conflicting docker env vars at exec time, e.g.:",
        f"#       docker exec -e SESSION_DB_TYPE= -e SESSION_DB_PATH= -it nextseek uv run e2e.py",
        f"",
        f"# --- API credentials (REQUIRED -- fill these in) ---",
        f"# Create a Django superuser for local docker:",
        f"#   docker exec -it nextseek uv run manage.py createsuperuser",
        f'API_USER=""',
        f'API_PASS=""',
        f"",
        f"# --- Session storage (override docker nextseek.env's mysql default) ---",
        f'SESSION_DB_TYPE="sqlite"',
        f'SESSION_DB_PATH="db.sqlite"',
        f"",
    ]

    if prod:
        lines.append("# --- PROD overrides (commented; uncomment to target MIT prod instead of local docker) ---")
        for k, v in prod.items():
            lines.append(f'# {k}="{v}"')
        lines.append("")

    return "\n".join(lines)


def write_env(target: str = "docker-local", path: Path | None = None, *, force: bool = False) -> Path:
    """Write the rendered .env to disk. Refuses to overwrite unless force=True."""
    if path is None:
        path = Path(__file__).resolve().parent.parent / ".env"
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists. Pass force=True to overwrite.")
    content = render_dotenv(target=target)
    path.write_text(content, encoding="utf-8")
    return path
