# Generated by Django 5.2.11 on 2026-02-11 21:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseek_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('query', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('progress', models.JSONField(default=list)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='nextseek_api.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_query_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
