# Generated by Django 5.2.15 on 2026-07-28 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseek_api', '0009_normalize_chat_log_turn_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeMutationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('actor_seek_person_id', models.BigIntegerField(db_index=True)),
                ('actor_django_user_id', models.BigIntegerField()),
                ('actor_login', models.CharField(max_length=255)),
                ('actor_scheme', models.CharField(max_length=32)),
                ('actor_identity', models.JSONField(default=dict)),
                ('canonical_submitted_request_sha256', models.CharField(db_index=True, max_length=64)),
                ('canonical_submitted_request', models.JSONField(default=dict)),
                ('resolved_plan_sha256', models.CharField(db_index=True, max_length=64)),
                ('resolved_plan_envelope', models.BinaryField()),
                ('execution_mode', models.CharField(default='synchronous', max_length=24)),
                ('state', models.CharField(default='accepted', max_length=32)),
                ('claim_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_generation', models.PositiveBigIntegerField(default=0)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('lease_version', models.PositiveBigIntegerField(default=0)),
                ('state_version', models.PositiveBigIntegerField(default=0)),
                ('outbox_state', models.CharField(default='not_required', max_length=24)),
                ('outbox_payload', models.JSONField(blank=True, default=dict)),
                ('outbox_attempts', models.PositiveIntegerField(default=0)),
                ('outbox_last_error', models.TextField(blank=True, null=True)),
                ('cancellation', models.JSONField(blank=True, default=dict)),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_actor_seek_person_id', models.BigIntegerField(blank=True, null=True)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('terminal_result', models.JSONField(blank=True, null=True)),
                ('http_classification', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attributes_mutation_job',
                'indexes': [models.Index(fields=['state', 'lease_expires_at', 'last_heartbeat_at'], name='attr_job_claim_scan'), models.Index(fields=['actor_seek_person_id', 'created_at'], name='attr_job_actor_time')],
            },
        ),
        migrations.CreateModel(
            name='AttributeMutationPartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type_id', models.BigIntegerField()),
                ('state', models.CharField(default='pending', max_length=32)),
                ('claim_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_generation', models.PositiveBigIntegerField(default=0)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('lease_version', models.PositiveBigIntegerField(default=0)),
                ('state_version', models.PositiveBigIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('before_physical_fingerprint', models.CharField(max_length=64)),
                ('expected_after_semantic_fingerprint', models.CharField(max_length=64)),
                ('created_identity_tokens', models.JSONField(default=list)),
                ('created_id_bindings', models.JSONField(blank=True, default=dict)),
                ('actual_after_physical_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('reconciliation', models.JSONField(blank=True, default=dict)),
                ('outcome', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='nextseek_api.attributemutationjob')),
            ],
            options={
                'db_table': 'attributes_mutation_partition',
                'indexes': [models.Index(fields=['job', 'state', 'lease_expires_at'], name='attr_part_job_claim')],
                'constraints': [models.UniqueConstraint(fields=('job', 'sample_type_id'), name='attr_part_job_type_uq')],
            },
        ),
    ]
