# Generated by Django 5.2.15 on 2026-09-01 00:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseek_api', '0019_merge_attribute_async_turn_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayRegistrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('actor_django_user_id', models.BigIntegerField()),
                ('actor_login', models.CharField(max_length=255)),
                ('submitted_request', models.JSONField(default=dict)),
                ('state', models.CharField(default='accepted', max_length=32)),
                ('state_version', models.PositiveBigIntegerField(default=0)),
                ('claim_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('terminal_result', models.JSONField(blank=True, null=True)),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_actor_django_user_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='assayregistrationjob',
            index=models.Index(fields=['state', 'created_at'], name='nextseek_ap_state_27d869_idx'),
        ),
    ]
