# Generated by Django 5.2.15 on 2026-09-15 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseek_api', '0020_assayregistrationjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_dir', models.CharField(max_length=768, unique=True)),
                ('run_name', models.CharField(max_length=255)),
                ('slurm_job_id', models.CharField(blank=True, default='', max_length=64)),
                ('pipeline', models.CharField(max_length=255)),
                ('revision', models.CharField(blank=True, default='', max_length=64)),
                ('params_digest', models.CharField(blank=True, default='', max_length=64)),
                ('launched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to=settings.AUTH_USER_MODEL)),
                ('launched_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='submitted', max_length=32)),
                ('cohort', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'assistant_pipeline_run',
                'ordering': ['-launched_at'],
            },
        ),
    ]
