# Generated by Django 5.2.15 on 2026-09-17 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseek_api', '0021_pipeline_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReingestAttributeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline', models.CharField(max_length=128)),
                ('raw_key', models.CharField(max_length=255)),
                ('proposed_target', models.CharField(max_length=64)),
                ('proposed_attribute', models.CharField(max_length=128)),
                ('datatype', models.CharField(default='string', max_length=32)),
                ('example_value', models.TextField(blank=True, default='')),
                ('source_file', models.CharField(blank=True, default='', max_length=1024)),
                ('rationale', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_definition', 'Needs definition')], default='pending', max_length=32)),
                ('times_proposed', models.PositiveIntegerField(default=1)),
                ('first_seen_run', models.CharField(blank=True, default='', max_length=1024)),
                ('last_seen_run', models.CharField(blank=True, default='', max_length=1024)),
                ('manifest_digest', models.CharField(blank=True, default='', max_length=64)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assistant_reingest_attribute_proposal',
                'ordering': ['-times_proposed', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reingestattributeproposal',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reingest_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reingestattributeproposal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reingest_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reingestattributeproposal',
            unique_together={('pipeline', 'raw_key', 'proposed_attribute')},
        ),
    ]
