# Generated by Django 5.2.15 on 2026-09-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextseek_api', '0022_reingest_attribute_proposal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='turnledger',
            new_name='assistant_t_task_fa_0b3487_idx',
            old_name='assistant_t_task_fa_6d0f8a_idx',
        ),
    ]
