# Generated by Django 5.2.15 on 2026-10-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextseek_api', '0025_cc_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccturn',
            name='ops_cost_partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ccturn',
            name='vocabulary_resolutions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
