"""The four seed DDL files exist, are well formed, and the bundles model maps one.

Since phase 6 these files are generated by `scripts/context_gen.py --emit seed`
from the hand-owned source in `context/`, not from a committed export of the table
they seed. `NessieAI/tests/api/test_context_gen.py` owns the generator; this module
owns what an install needs from the files themselves.
"""

import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
SQL = ROOT / "startup" / "seed" / "sql"
CONTEXT = ROOT / "context"


@pytest.mark.parametrize("name,table", [
    ("sample_types_context.sql", "sample_types_context"),
    ("assay_context.sql", "assay_context"),
    ("projects_context.sql", "projects_context"),
    ("project_template_bundles.sql", "project_template_bundles"),
])
def test_ddl_file_creates_its_table_idempotently(name, table):
    sql = (SQL / name).read_text()
    assert f"CREATE TABLE IF NOT EXISTS {table}" in sql
    assert "ENGINE=InnoDB" in sql
    assert "utf8mb4" in sql


@pytest.mark.parametrize("name,table,source", [
    ("sample_types_context.sql", "sample_types_context", "sample_types.json"),
    ("assay_context.sql", "assay_context", "assays.json"),
    ("projects_context.sql", "projects_context", "projects.json"),
])
def test_context_seed_carries_every_curated_row(name, table, source):
    """The seed is generated from `context/`, so the counts must agree.

    Not a magic number: read the source, so a regenerated seed stays honest.
    """
    rows = json.loads((CONTEXT / source).read_text())
    sql = (SQL / name).read_text()
    inserts = re.findall(rf"^INSERT INTO `{table}`", sql, flags=re.MULTILINE)
    assert len(inserts) == len(rows)


def test_the_table_that_ships_empty_carries_no_inserts():
    """Only `project_template_bundles` still ships empty.

    `projects_context` did until phase 6, when the curated source gave it 12 rows;
    a project with no row still falls back to the SEEK title and description.
    """
    assert "INSERT INTO" not in (SQL / "project_template_bundles.sql").read_text()


def test_schema_fixups_declares_all_four():
    from startup.steps.schema_fixups import KNOWN_TABLE_FIXUPS

    declared = {(f.database, f.table, f.ddl_path) for f in KNOWN_TABLE_FIXUPS}
    for table in ("sample_types_context", "assay_context", "projects_context",
                  "project_template_bundles"):
        assert ("dmac", table, f"startup/seed/sql/{table}.sql") in declared


def test_bundles_model_maps_the_table():
    from seek.models import Project_template_bundles

    assert Project_template_bundles._meta.db_table == "project_template_bundles"
    assert Project_template_bundles._meta.managed is False
    names = {f.name for f in Project_template_bundles._meta.get_fields()}
    assert {"project_id", "position", "label", "codes"} <= names
