"""The seed DDL files exist, are well formed, and the bundles model maps one.

Two kinds of file live in startup/seed/sql/. The ones startup/steps/schema_fixups.py
registers are what an install loads. The three `*.curated.sql` files are
generated by `scripts/context_gen.py --emit seed` from `context/` and HELD: no
install step reads them until the curated content is signed off.
`NessieAI/tests/api/test_context_gen.py` owns the generator; this module owns what
an install needs from the files themselves.
"""

import json
import re
from pathlib import Path

import pytest

from NessieAI import paths

ROOT = Path(__file__).resolve().parents[2]
SQL = ROOT / "startup" / "seed" / "sql"


@pytest.mark.parametrize("name,table", [
    ("assay_context.sql", "assay_context"),
    ("projects_context.sql", "projects_context"),
    ("project_template_bundles.sql", "project_template_bundles"),
])
def test_ddl_file_creates_its_table_idempotently(name, table):
    sql = (SQL / name).read_text()
    assert f"CREATE TABLE IF NOT EXISTS {table}" in sql
    assert "ENGINE=InnoDB" in sql
    assert "utf8mb4" in sql


def test_assay_context_seed_carries_every_row_from_the_committed_export():
    """The seed is generated from a committed JSON export, so the counts must agree.

    Not a magic 217: read the export, so a regenerated seed stays honest.
    """
    export = json.loads(
        (paths.CHAT_NEXTSEEK_DIR / "src" / "chat_nextseek" / "context"
         / "assays_db.json").read_text()
    )
    sql = (SQL / "assay_context.sql").read_text()
    inserts = re.findall(r"^INSERT INTO `assay_context`", sql, flags=re.MULTILINE)
    assert len(inserts) == len(export)


def test_the_two_tables_that_ship_empty_carry_no_inserts():
    for name in ("projects_context.sql", "project_template_bundles.sql"):
        assert "INSERT INTO" not in (SQL / name).read_text()


def test_schema_fixups_declares_all_three():
    from startup.steps.schema_fixups import KNOWN_TABLE_FIXUPS

    declared = {(f.database, f.table, f.ddl_path) for f in KNOWN_TABLE_FIXUPS}
    for table in ("assay_context", "projects_context", "project_template_bundles"):
        assert ("dmac", table, f"startup/seed/sql/{table}.sql") in declared


def test_bundles_model_maps_the_table():
    from seek.models import Project_template_bundles

    assert Project_template_bundles._meta.db_table == "project_template_bundles"
    assert Project_template_bundles._meta.managed is False
    names = {f.name for f in Project_template_bundles._meta.get_fields()}
    assert {"project_id", "position", "label", "codes"} <= names


# --- the held curated seeds --------------------------------------------------

CONTEXT = ROOT / "context"
CURATED = {
    "sample_types_context": ("sample_types_context.curated.sql", "sample_types.json"),
    "assay_context": ("assay_context.curated.sql", "assays.json"),
    "projects_context": ("projects_context.curated.sql", "projects.json"),
}


def _values(line: str) -> list[str]:
    """The top-level values of one `INSERT ... VALUES (...);` line, as SQL text.

    A real tokenizer rather than a `'[^']*'` regex: a quote inside a value is
    written doubled (`'Women''s Health'`), and a value with a newline is a
    `CONCAT(...)` call, so neither a quote nor a comma alone ends a value.
    """
    body = line.split(") VALUES (", 1)[1].rsplit(");", 1)[0]
    values, current, depth, quoted, index = [], [], 0, False, 0
    while index < len(body):
        char = body[index]
        if quoted:
            current.append(char)
            if char == "\\":                        # a backslash escape, if any
                current.append(body[index + 1:index + 2])
                index += 1
            elif char == "'":
                if body[index + 1:index + 2] == "'":
                    current.append("'")
                    index += 1
                else:
                    quoted = False
        elif char == "'":
            quoted = True
            current.append(char)
        elif char == "(":
            depth += 1
            current.append(char)
        elif char == ")":
            depth -= 1
            current.append(char)
        elif char == "," and depth == 0:
            values.append("".join(current).strip())
            current = []
        else:
            current.append(char)
        index += 1
    values.append("".join(current).strip())
    return values


@pytest.mark.parametrize("table", sorted(CURATED))
def test_a_curated_seed_creates_its_table_and_carries_every_curated_row(table):
    name, source = CURATED[table]
    sql = (SQL / name).read_text()
    assert f"CREATE TABLE IF NOT EXISTS {table}" in sql
    assert "ENGINE=InnoDB" in sql and "utf8mb4" in sql
    rows = json.loads((CONTEXT / source).read_text())
    inserts = re.findall(rf"^INSERT INTO `{table}`", sql, flags=re.MULTILINE)
    assert len(inserts) == len(rows)


@pytest.mark.parametrize("table", sorted(CURATED))
def test_a_curated_seed_pins_the_connection_charset_before_its_ddl(table):
    """The installer pipes a file into `mysql` with no `--default-character-set`
    and the db container has no UTF-8 locale, so without this line every
    non-ASCII value is double-encoded (latin1 read as utf8mb4)."""
    sql = (SQL / CURATED[table][0]).read_text()
    assert sql.index("SET NAMES utf8mb4;") < sql.index(f"CREATE TABLE IF NOT EXISTS {table} (")


def test_the_curated_sample_types_header_tells_the_truth_about_the_dump():
    """The seeded dump DOES create and populate sample_types_context.

    Measured with `zcat startup/seed/dmac.sql.gz | grep 'CREATE TABLE'`: of the
    three context tables it creates exactly this one. A header saying otherwise
    sends an operator to hand-apply the file to a stack that already has the table.
    """
    import gzip

    dump = gzip.open(ROOT / "startup" / "seed" / "dmac.sql.gz", "rt",
                     encoding="utf-8", errors="replace").read()
    creates = {table for table in CURATED if f"CREATE TABLE `{table}`" in dump}
    assert creates == {"sample_types_context"}, creates
    header = (SQL / CURATED["sample_types_context"][0]).read_text().split("CREATE TABLE", 1)[0]
    header = " ".join(header.replace("\n--", "").split())
    assert "startup/seed/dmac.sql.gz DOES create and populate it" in header
    assert "It is not an update." in header


def test_the_curated_projects_seed_warns_that_its_project_ids_are_productions():
    """The rows are keyed to production's SEEK ids and nothing checks them.

    context_catalog looks a row up by SEEK project id with no fallback by name,
    and the committed seek seed carries only `Published Data` at id 1. Every row
    is read, including those whose text carries a quote.
    """
    sql = (SQL / CURATED["projects_context"][0]).read_text()
    header = " ".join(sql.split("CREATE TABLE", 1)[0].replace("\n--", "").split())
    assert "PRODUCTION's SEEK ids" in header
    assert "Check the ids against the target stack's `projects` table" in header
    lines = [line for line in sql.splitlines() if line.startswith("INSERT INTO ")]
    columns = lines[0].split("` (", 1)[1].split(") VALUES", 1)[0]
    position = [c.strip(" `") for c in columns.split(",")].index("project_id")
    ids = [_values(line)[position] for line in lines]
    assert len(ids) == len(json.loads((CONTEXT / "projects.json").read_text()))
    assert "1" not in ids          # the one project the committed seek seed has


def test_values_reads_a_doubled_quote_and_a_concat_as_one_value_each():
    line = ("INSERT INTO `t` (`a`, `b`, `c`) VALUES ('Women''s Health, NIH', "
            "CONCAT('x', CHAR(10 USING utf8mb4), 'y, z'), 7);")
    assert _values(line) == ["'Women''s Health, NIH'",
                             "CONCAT('x', CHAR(10 USING utf8mb4), 'y, z')", "7"]
