# Generated by Django 4.2.23 on 2026-01-23 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assay_assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay_id', models.IntegerField(default=None)),
                ('asset_id', models.IntegerField(default=None)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
                ('relationship_type_id', models.IntegerField(default=None)),
                ('asset_type', models.CharField(default=None, max_length=255)),
                ('direction', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'assay_assets',
            },
        ),
        migrations.CreateModel(
            name='Assays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None)),
                ('description', models.TextField(default=None)),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
                ('study_id', models.IntegerField()),
                ('contributor_id', models.IntegerField()),
                ('first_letter', models.CharField(default=None, max_length=1)),
                ('assay_class_id', models.IntegerField()),
                ('uuid', models.CharField(default=None, max_length=255)),
                ('policy_id', models.IntegerField()),
                ('assay_type_uri', models.TextField()),
                ('technology_type_uri', models.TextField()),
                ('suggested_assay_type_id', models.IntegerField()),
                ('suggested_technology_type_id', models.IntegerField()),
                ('other_creators', models.TextField(default=None)),
                ('deleted_contributor', models.TextField(default=None)),
                ('sample_type_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('assay_stream_id', models.IntegerField()),
            ],
            options={
                'db_table': 'assays',
            },
        ),
        migrations.CreateModel(
            name='Assays_internal_assays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_assay_id', models.IntegerField(default=None)),
                ('assay_id', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'assays_internal_assays',
            },
        ),
        migrations.CreateModel(
            name='Assets_creators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.IntegerField(default=None)),
                ('creator_id', models.IntegerField(default=None)),
                ('asset_type', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
            options={
                'db_table': 'assets_creators',
            },
        ),
        migrations.CreateModel(
            name='Clades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None)),
                ('color', models.TextField(default=None)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'clades',
            },
        ),
        migrations.CreateModel(
            name='Content_blobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5sum', models.CharField(default=None, max_length=255)),
                ('url', models.TextField(default=None)),
                ('uuid', models.CharField(default=None, max_length=255)),
                ('original_filename', models.CharField(default=None, max_length=255)),
                ('content_type', models.CharField(default=None, max_length=255)),
                ('asset_id', models.IntegerField(default=None)),
                ('asset_type', models.CharField(default=None, max_length=255)),
                ('asset_version', models.IntegerField(default=1)),
                ('is_webpage', models.BooleanField(default=0)),
                ('external_link', models.BooleanField(default=None)),
                ('sha1sum', models.CharField(default=None, max_length=255)),
                ('file_size', models.BigIntegerField(default=None)),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
            options={
                'db_table': 'content_blobs',
            },
        ),
        migrations.CreateModel(
            name='Data_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_id', models.IntegerField(default=None)),
                ('title', models.CharField(default=None, max_length=255)),
                ('description', models.TextField(default=None)),
                ('template_id', models.IntegerField(default=None)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('version', models.IntegerField(default=1)),
                ('first_letter', models.CharField(default=None, max_length=1)),
                ('other_creators', models.TextField(default=None)),
                ('uuid', models.CharField(default=None, max_length=255)),
                ('policy_id', models.IntegerField(default=None)),
                ('doi', models.CharField(default=None, max_length=255)),
                ('license', models.CharField(default=None, max_length=255)),
                ('simulation_data', models.BooleanField(default=0)),
                ('deleted_contributor', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'data_files',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('description', models.TextField(default=None)),
                ('contributor_id', models.IntegerField(default=None)),
                ('version', models.IntegerField(default=1)),
                ('first_letter', models.CharField(default=None, max_length=1)),
                ('uuid', models.CharField(default=None, max_length=255)),
                ('policy_id', models.IntegerField(default=None)),
                ('doi', models.CharField(default=None, max_length=255)),
                ('license', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('other_creators', models.TextField(default=None)),
                ('deleted_contributor', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Internal_assays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_assay_title', models.TextField(default=None)),
            ],
            options={
                'db_table': 'internal_assays',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('first_name', models.CharField(default=None, max_length=255)),
                ('last_name', models.CharField(default=None, max_length=255)),
                ('email', models.CharField(default=None, max_length=255)),
                ('phone', models.CharField(default=None, max_length=255)),
                ('skype_name', models.CharField(default=None, max_length=255)),
                ('web_page', models.CharField(default=None, max_length=255)),
                ('description', models.TextField(default=None)),
                ('avatar_id', models.IntegerField(default=None)),
                ('status_id', models.IntegerField(default=None)),
                ('first_letter', models.CharField(default=None, max_length=1)),
                ('uuid', models.CharField(default=None, max_length=255)),
                ('roles_mask', models.IntegerField(default=None)),
                ('orcid', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_type', models.CharField(default=None, max_length=255)),
                ('contributor_id', models.IntegerField(default=None)),
                ('policy_id', models.IntegerField(default=None)),
                ('access_type', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('sharing_scope', models.IntegerField(default=None)),
                ('access_type', models.IntegerField(default=0)),
                ('use_allowlist', models.BooleanField(default=None)),
                ('use_denylist', models.BooleanField(default=None)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'policies',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('web_page', models.TextField(default=None)),
                ('wiki_page', models.TextField(default=None)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('description', models.TextField(default=None)),
                ('avatar_id', models.IntegerField()),
                ('default_policy_id', models.IntegerField()),
                ('first_letter', models.CharField(default=None, max_length=1)),
                ('site_credentials', models.TextField(default=None)),
                ('site_root_uri', models.TextField(default=None)),
                ('last_jerm_run', models.DateTimeField()),
                ('uuid', models.CharField(default=None, max_length=255)),
                ('programme_id', models.IntegerField()),
                ('default_license', models.CharField(default=None, max_length=255)),
                ('use_default_policy', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Sample_attribute_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('base_type', models.CharField(default=None, max_length=255)),
                ('regexp', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('placeholder', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(default=None, max_length=255)),
                ('resolution', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'sample_attribute_types',
            },
        ),
        migrations.CreateModel(
            name='Sample_attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('sample_attribute_type_id', models.IntegerField()),
                ('required', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('pos', models.IntegerField(default=None)),
                ('sample_type_id', models.IntegerField()),
                ('unit_id', models.IntegerField(default=None)),
                ('is_title', models.BooleanField(default=0)),
                ('template_column_index', models.IntegerField(default=None)),
                ('original_accessor_name', models.CharField(default=None, max_length=255)),
                ('sample_controlled_vocab_id', models.IntegerField(default=None)),
                ('linked_sample_type_id', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'sample_attributes',
            },
        ),
        migrations.CreateModel(
            name='Sample_tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.IntegerField()),
                ('uuid', models.CharField(default=None, max_length=255)),
                ('parents', models.TextField(default=None)),
                ('children', models.TextField(default=None)),
                ('full', models.TextField(default=None)),
                ('updated', models.DateTimeField(default=None)),
            ],
            options={
                'db_table': 'seek_sample_tree',
            },
        ),
        migrations.CreateModel(
            name='Sample_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('uuid', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('first_letter', models.CharField(default=None, max_length=1)),
                ('description', models.TextField(default=None)),
                ('uploaded_template', models.BooleanField(default=0)),
                ('contributor_id', models.IntegerField(default=None)),
                ('deleted_contributor', models.CharField(default=None, max_length=255)),
                ('template_id', models.IntegerField(default=None)),
                ('other_creators', models.TextField(default=None)),
            ],
            options={
                'db_table': 'sample_types',
            },
        ),
        migrations.CreateModel(
            name='Sample_types_clades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clade_id', models.IntegerField(default=None)),
                ('sample_type_id', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'sample_types_clades',
            },
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('sample_type_id', models.IntegerField()),
                ('json_metadata', models.TextField(default=None)),
                ('uuid', models.CharField(default=None, max_length=255)),
                ('contributor_id', models.IntegerField(default=None)),
                ('policy_id', models.IntegerField(default=None)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('first_letter', models.CharField(default=None, max_length=1)),
                ('other_creators', models.TextField(default=None)),
                ('originating_data_file_id', models.IntegerField(default=None)),
                ('deleted_contributor', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'samples',
            },
        ),
        migrations.CreateModel(
            name='Sops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_id', models.IntegerField(default=None)),
                ('title', models.CharField(default=None, max_length=255)),
                ('description', models.TextField(default=None)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('version', models.IntegerField(default=1)),
                ('first_letter', models.CharField(default=None, max_length=1)),
                ('other_creators', models.TextField(default=None)),
                ('uuid', models.CharField(default=None, max_length=255)),
                ('policy_id', models.IntegerField(default=None)),
                ('doi', models.CharField(default=None, max_length=255)),
                ('license', models.CharField(default=None, max_length=255)),
                ('deleted_contributor', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'sops',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default=None, max_length=255)),
                ('crypted_password', models.CharField(default=None, max_length=255)),
                ('salt', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('remember_token', models.CharField(default=None, max_length=255)),
                ('remember_token_expires_at', models.DateTimeField()),
                ('activation_code', models.CharField(default=None, max_length=255)),
                ('activated_at', models.DateTimeField()),
                ('person_id', models.IntegerField(default=None)),
                ('reset_password_code', models.CharField(default=None, max_length=255)),
                ('reset_password_code_until', models.DateTimeField()),
                ('posts_count', models.IntegerField(default=None)),
                ('last_seen_at', models.DateTimeField()),
                ('uuid', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(choices=[('Undefined', 'Undefined'), ('IMPAcTb', 'IMPAcTb'), ('MIT_SRP', 'MIT_SRP'), ('MetNet', 'MetNet'), ('MIT-Koch', 'MIT-Koch'), ('Training/Test', 'Training/Test')], max_length=255)),
                ('laboratory', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects_sops',
            fields=[
                ('project_id', models.IntegerField(default=None)),
                ('sop_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'projects_sops',
                'unique_together': {('project_id', 'sop_id')},
            },
        ),
        migrations.CreateModel(
            name='Projects_samples',
            fields=[
                ('project_id', models.IntegerField(default=None)),
                ('sample_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'projects_samples',
                'unique_together': {('project_id', 'sample_id')},
            },
        ),
        migrations.CreateModel(
            name='Data_files_projects',
            fields=[
                ('project_id', models.IntegerField(default=None)),
                ('data_file_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'data_files_projects',
                'unique_together': {('project_id', 'data_file_id')},
            },
        ),
    ]
