# Generated by Django 4.2.23 on 2025-09-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seek', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample_types',
            name='clade_id',
        ),
        migrations.RemoveField(
            model_name='sample_types',
            name='st_group',
        ),
        migrations.RemoveField(
            model_name='sample_types_clades',
            name='clade',
        ),
        migrations.RemoveField(
            model_name='sample_types_clades',
            name='sample_type',
        ),
        migrations.AddField(
            model_name='sample_types_clades',
            name='clade_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sample_types_clades',
            name='sample_type_id',
            field=models.IntegerField(default=None),
        ),
    ]
