#!/bin/bash
# Independent re-verification of every asserted count in the 2026-08-06 question set.
S=/tmp/claude-1000/-home-cdemu-code-dmac-docker/7c6b89bb-13b7-48d6-8ccd-7b0eda6e02a0/scratchpad
Q() { printf '%-46s %s\n' "$1" "$($S/q.sh "$2" | tr '\n' ' ')"; }
C() { printf '%-46s %s\n' "$1" "$($S/cy.sh "$2" | tail -n +2 | tr '\n' ' ')"; }
J="JSON_UNQUOTE(JSON_EXTRACT(s.json_metadata,"
T="FROM seek_production.samples s JOIN seek_production.sample_types st ON st.id=s.sample_type_id"

Q "195 MUS NDMA"        "SELECT COUNT(*) $T WHERE st.title='MUS' AND $J'\$.Treatment1'))='NDMA';"
Q "529 female mice"     "SELECT COUNT(*) $T WHERE st.title='MUS' AND $J'\$.Sex')) IN ('F','Female');"
Q "26 RIN>7"            "SELECT COUNT(*) $T WHERE st.title='RNA' AND CAST($J'\$.RIN')) AS DECIMAL(6,2))>7;"
Q "241 fibrin D.IMG"    "SELECT COUNT(*) $T WHERE st.title='D.IMG' AND LOWER(s.json_metadata) LIKE '%fibrin%';"
Q "420/610 TIS liver"   "SELECT SUM($J'\$.Organ'))='Liver'), SUM(TRIM(LOWER($J'\$.Organ')))='liver') $T WHERE st.title='TIS';"
Q "530 OOC KAM"         "SELECT COUNT(*) $T WHERE st.title='OOC';"
Q "38 RNA KAM"          "SELECT COUNT(*) $T WHERE st.title='RNA' AND $J'\$.UID')) LIKE 'RNA-%KAM-%';"
Q "144/83 Owen Leddy"   "SELECT COUNT(*), SUM(st.title='D.MSP') $T WHERE $J'\$.Scientist')) LIKE '%Leddy%';"
Q "4264 Cytek Aurora"   "SELECT COUNT(*) $T WHERE $J'\$.Instrument'))='Cytek Aurora Spectral Cytometer';"
Q "2271 CometChip"      "SELECT COUNT(*) $T WHERE st.title='D.IMG' AND $J'\$.Type'))='CometChip';"
Q "0 HeLa CellLine"     "SELECT COUNT(*) $T WHERE $J'\$.CellLine'))='HeLa';"
Q "0 ChIP-seq"          "SELECT COUNT(*) $T WHERE LOWER(s.json_metadata) LIKE '%chip-seq%' OR LOWER(s.json_metadata) LIKE '%chipseq%';"
Q "0 PAT male"          "SELECT COUNT(*) $T WHERE st.title='PAT' AND $J'\$.Sex')) IN ('M','Male');"
Q "104/78 sampletypes"  "SELECT COUNT(*), SUM(n>0) FROM (SELECT st.id, COUNT(s.id) n FROM seek_production.sample_types st LEFT JOIN seek_production.samples s ON s.sample_type_id=st.id GROUP BY st.id) x;"
Q "0 vocab refs / 6"    "SELECT (SELECT COUNT(*) FROM seek_production.sample_attributes WHERE sample_controlled_vocab_id IS NOT NULL), (SELECT COUNT(*) FROM seek_production.sample_controlled_vocabs);"
Q "324 assays"          "SELECT COUNT(*) FROM seek_production.assays;"
Q "42/40 clades"        "SELECT SUM(c.title='Analyzed'), SUM(c.title='Raw') FROM dmac.clades c JOIN dmac.sample_types_clades stc ON stc.clade_id=c.id;"
Q "2 people/113 sci"    "SELECT (SELECT COUNT(*) FROM seek_production.people), COUNT(DISTINCT $J'\$.Scientist'))) $T WHERE JSON_TYPE(JSON_EXTRACT(s.json_metadata,'\$.Scientist'))='STRING' AND $J'\$.Scientist'))<>'';"
Q "175/34 SOPs"         "SELECT COUNT(*), SUM(title LIKE 'TEST\_SOP%') FROM seek_production.sops;"
Q "214 NextSeq"         "SELECT COUNT(*) $T WHERE $J'\$.Sequencer')) LIKE '%NextSeq%';"
Q "41 TIS via IHC"      "SELECT COUNT(DISTINCT aa.asset_id) FROM dmac.assays_internal_assays aia JOIN dmac.internal_assays ia ON ia.id=aia.internal_assay_id JOIN seek_production.assay_assets aa ON aa.assay_id=aia.assay_id JOIN seek_production.samples s2 ON s2.id=aa.asset_id JOIN seek_production.sample_types st2 ON st2.id=s2.sample_type_id WHERE ia.internal_assay_title='Immunohistochemistry' AND aa.asset_type='Sample' AND st2.title='TIS';"
Q "1179 amplicon"       "SELECT COUNT(*) $T WHERE st.title='D.SEQ' AND LOWER($J'\$.LibraryStrategy')))='amplicon';"
Q "4449 TIS lung"       "SELECT COUNT(*) $T WHERE st.title='TIS' AND LOWER($J'\$.Organ')))='lung';"
Q "127 C57BL/6 split"   "SELECT COUNT(*) $T WHERE st.title='MUS' AND $J'\$.Genotype')) IN ('C57BL/6','C57Bl/6');"
Q "342 rhesus"          "SELECT COUNT(*) $T WHERE st.title='NHP' AND $J'\$.Species')) IN ('Macaca mulatta (Rhesus)','Macaca mulatta','Rhesus macaque');"
Q "4080 ImmPort"        "SELECT COUNT(*) $T WHERE LOWER($J'\$.Repository')))='immport';"
Q "5649 tif"            "SELECT COUNT(*) $T WHERE st.title='D.IMG' AND LOWER($J'\$.DataType'))) IN ('tif','.tif');"
Q "332/278 Catalog#"    "SELECT SUM(JSON_CONTAINS_PATH(s.json_metadata,'one','\$.\"Catalog#\"')), SUM(JSON_CONTAINS_PATH(s.json_metadata,'one','\$.\"catalog#\"')) $T WHERE st.title='AB';"
Q "379 Edward B Irvine" "SELECT COUNT(*) $T WHERE $J'\$.Scientist'))='Edward B. Irvine';"
Q "237/8/8 4wk"         "SELECT SUM($J'\$.Cohort'))='4wk'), SUM($J'\$.Cohort'))='4wk_Day1'), SUM($J'\$.Cohort'))='4wk_Day2') $T WHERE st.title='MUS';"
Q "457/653 PBMC"        "SELECT SUM($J'\$.Type'))='PBMC'), SUM(s.json_metadata LIKE '%PBMC%') $T WHERE st.title='TIS';"
Q "75/3 MUS attrs"      "SELECT COUNT(*), SUM(required) FROM seek_production.sample_attributes sa JOIN seek_production.sample_types st3 ON st3.id=sa.sample_type_id WHERE st3.title='MUS';"
Q "47 NHP attrs"        "SELECT COUNT(*) FROM seek_production.sample_attributes sa JOIN seek_production.sample_types st3 ON st3.id=sa.sample_type_id WHERE st3.title='NHP';"
Q "76 internal assays"  "SELECT COUNT(*) FROM dmac.internal_assays;"
Q "2057 D.SEQ"          "SELECT COUNT(*) $T WHERE st.title='D.SEQ';"
Q "118 D.MSP"           "SELECT COUNT(*) $T WHERE st.title='D.MSP';"
Q "26 empty types"      "SELECT COUNT(*) FROM (SELECT st.id, COUNT(s.id) n FROM seek_production.sample_types st LEFT JOIN seek_production.samples s ON s.sample_type_id=st.id GROUP BY st.id HAVING n=0) x;"
Q "13351 D.IMG"         "SELECT COUNT(*) $T WHERE st.title='D.IMG';"
Q "1378/1290 granuloma" "SELECT COUNT(*), SUM(LOWER($J'\$.Organ')))='lung') $T WHERE st.title='TIS' AND $J'\$.Type'))='Granuloma';"
Q "577 acetaminophen"   "SELECT COUNT(*) $T WHERE st.title='PAV' AND $J'\$.Treatment1'))='Acetaminophen';"
Q "96/24 PWK"           "SELECT COUNT(*), SUM($J'\$.Sex'))='F') $T WHERE st.title='MUS' AND $J'\$.Genotype'))='PWK';"
Q "545 brightfield"     "SELECT COUNT(*) $T WHERE st.title='D.IMG' AND $J'\$.Type'))='Brightfield';"
Q "800 illumina lib"    "SELECT COUNT(*) $T WHERE $J'\$.Type'))='Illumina Library';"
Q "223 CEX plasma"      "SELECT COUNT(*) $T WHERE st.title='CEX' AND $J'\$.Type'))='Plasma';"
Q "136 vasculogenesis"  "SELECT COUNT(*) $T WHERE st.title='OOC' AND $J'\$.Vascularization'))='Vasculogenesis';"
Q "701/142 spleen/kid"  "SELECT SUM(LOWER($J'\$.Organ')))='spleen'), SUM(LOWER($J'\$.Organ')))='kidney') $T WHERE st.title='TIS';"
Q "188/12 WGS/HiC"      "SELECT SUM($J'\$.LibraryStrategy'))='WGS'), SUM($J'\$.LibraryStrategy'))='Hi-C') $T WHERE st.title='D.SEQ';"
Q "194/82 India/China"  "SELECT SUM($J'\$.Origin'))='India'), SUM($J'\$.Origin'))='China') $T WHERE st.title='NHP';"
Q "90/541 RNAlater/SF"  "SELECT SUM($J'\$.StorageType'))='RNALater'), SUM($J'\$.StorageType'))='Snap Frozen') $T WHERE st.title='TIS';"
Q "248/30 IM/ID"        "SELECT SUM($J'\$.Treatment1Route'))='Intramuscularly'), SUM($J'\$.Treatment1Route'))='Intradermally') $T WHERE st.title='PAV';"
Q "1178/427 MiSeq/Nova" "SELECT SUM($J'\$.Sequencer'))='Illumina MiSeq'), SUM($J'\$.Sequencer'))='Illumina NovaSeq 6000') $T WHERE st.title='D.SEQ';"
Q "7269 KAM lab"        "SELECT COUNT(*) FROM seek_production.samples s WHERE $J'\$.UID')) REGEXP '-[0-9]{6}KAM-';"
Q "176 D.SEQ LAU"       "SELECT COUNT(*) $T WHERE st.title='D.SEQ' AND $J'\$.UID')) LIKE 'D.SEQ-%LAU-%';"
Q "89 PAT TB"           "SELECT COUNT(*) $T WHERE st.title='PAT' AND $J'\$.Disease'))='Tuberculosis';"
Q "46 NHP CD8 cohorts"  "SELECT COUNT(*) $T WHERE st.title='NHP' AND LOWER($J'\$.Cohort'))) LIKE '%cd8%';"
Q "15 CD8 Depletion"    "SELECT COUNT(*) $T WHERE st.title='NHP' AND $J'\$.Cohort'))='CD8 Depletion';"
Q "103 TIS pancreas"    "SELECT COUNT(*) $T WHERE st.title='TIS' AND $J'\$.Organ'))='Pancreas';"
Q "0 western blot"      "SELECT COUNT(*) FROM seek_production.samples s WHERE LOWER(s.json_metadata) LIKE '%western blot%';"
Q "0 zebrafish"         "SELECT COUNT(*) FROM seek_production.samples s WHERE LOWER(s.json_metadata) LIKE '%zebrafish%' OR s.json_metadata LIKE '%Danio%';"
Q "318 CEL Impact SQL"  "SELECT COUNT(DISTINCT aa.asset_id) FROM seek_production.assay_assets aa JOIN seek_production.assays a ON a.id=aa.assay_id JOIN seek_production.studies stu ON stu.id=a.study_id JOIN seek_production.investigations i ON i.id=stu.investigation_id JOIN seek_production.samples s2 ON s2.id=aa.asset_id JOIN seek_production.sample_types st2 ON st2.id=s2.sample_type_id WHERE aa.asset_type='Sample' AND i.title='Impact' AND st2.title='CEL';"
Q "1858 D.SEQ Impact"   "SELECT COUNT(DISTINCT aa.asset_id) FROM seek_production.assay_assets aa JOIN seek_production.assays a ON a.id=aa.assay_id JOIN seek_production.studies stu ON stu.id=a.study_id JOIN seek_production.investigations i ON i.id=stu.investigation_id JOIN seek_production.samples s2 ON s2.id=aa.asset_id JOIN seek_production.sample_types st2 ON st2.id=s2.sample_type_id WHERE aa.asset_type='Sample' AND i.title='Impact' AND st2.title='D.SEQ';"

C "705 mice Impact"     "MATCH (s:Sample {type:'MUS'})-[:IN_STUDY]->(:Study)-[:IN_INVESTIGATION]->(:Investigation {title:'Impact'}) RETURN count(DISTINCT s)"
C "185 mice with seq"   "MATCH (d:Sample {type:'D.SEQ'})-[:DERIVED_FROM*1..8]->(m:Sample {type:'MUS'}) RETURN count(DISTINCT m)"
C "7 TIS CSBC"          "MATCH (s:Sample {type:'TIS'})-[:IN_STUDY]->(:Study)-[:IN_INVESTIGATION]->(:Investigation {title:'CSBC'}) RETURN count(DISTINCT s)"
C "2 Griffith studies"  "MATCH (st:Study)-[:IN_INVESTIGATION]->(:Investigation {title:'Griffith'}) RETURN count(st)"
C "5859 D.IMG from OOC" "MATCH (d:Sample {type:'D.IMG'})-[:DERIVED_FROM*1..8]->(:Sample {type:'OOC'}) RETURN count(DISTINCT d)"
C "3061 D.FLOW from NHP" "MATCH (d:Sample {type:'D.FLOW'})-[:DERIVED_FROM*1..8]->(:Sample {type:'NHP'}) RETURN count(DISTINCT d)"
C "139 monkeys w/ seq"  "MATCH (d:Sample {type:'D.SEQ'})-[:DERIVED_FROM*1..8]->(n:Sample {type:'NHP'}) RETURN count(DISTINCT n)"
C "1608 D.SEQ from NHP" "MATCH (d:Sample {type:'D.SEQ'})-[:DERIVED_FROM*1..8]->(:Sample {type:'NHP'}) RETURN count(DISTINCT d)"
C "6441 D.IMG MetNet"   "MATCH (s:Sample {type:'D.IMG'})-[:IN_STUDY]->(:Study)-[:IN_INVESTIGATION]->(:Investigation {title:'MetNet'}) RETURN count(DISTINCT s)"
C "79 CEL Impact graph" "MATCH (s:Sample {type:'CEL'})-[:IN_STUDY]->(:Study)-[:IN_INVESTIGATION]->(:Investigation {title:'Impact'}) RETURN count(DISTINCT s)"
C "11 CEL descendants"  "MATCH (d:Sample)-[:DERIVED_FROM*1..10]->(:Sample {uuid:'CEL-250319WHI-1-PUB'}) RETURN count(DISTINCT d)"
C "221 NHP-5 desc"      "MATCH (d:Sample)-[:DERIVED_FROM*1..10]->(:Sample {uuid:'NHP-220630FLY-5-PUB'}) RETURN count(DISTINCT d)"
C "56 monkeys flow+seq" "MATCH (n:Sample {type:'NHP'}) WHERE EXISTS { MATCH (:Sample {type:'D.FLOW'})-[:DERIVED_FROM*1..8]->(n) } AND EXISTS { MATCH (:Sample {type:'D.SEQ'})-[:DERIVED_FROM*1..8]->(n) } RETURN count(n)"
C "4061 multiparent"    "MATCH (c:Sample)-[:DERIVED_FROM]->(p:Sample) WITH c, count(DISTINCT p) AS k WHERE k>1 RETURN count(c)"
C "5616 roots"          "MATCH (s:Sample) WHERE NOT (s)-[:DERIVED_FROM]->() RETURN count(s)"
C "21501 leaves"        "MATCH (s:Sample) WHERE NOT ()-[:DERIVED_FROM]->(s) RETURN count(s)"
C "938 fanout"          "MATCH (c:Sample)-[:DERIVED_FROM]->(:Sample {uuid:'TIS-230830ENG-1-PUB'}) RETURN count(DISTINCT c)"
C "0 unrelated pair"    "MATCH (a:Sample {uuid:'MUS-200901ENG-23-PUB'}), (b:Sample {uuid:'D.SEQ-221031SHA-67-PUB'}) RETURN EXISTS { MATCH (a)-[:DERIVED_FROM*1..12]-(b) }"
C "2 OOC parents"       "MATCH (c:Sample {uuid:'OOC-250519KAM-21-PUB'})-[:DERIVED_FROM]->(p:Sample) RETURN count(DISTINCT p)"
C "0 NHP in SRP"        "MATCH (s:Sample {type:'NHP'})-[:IN_STUDY]->(:Study)-[:IN_INVESTIGATION]->(i:Investigation) RETURN i.title, count(DISTINCT s)"
C "144/568/6708/7365"   "MATCH (s:Sample)-[:IN_STUDY]->(:Study)-[:IN_INVESTIGATION]->(i:Investigation) RETURN i.title, count(DISTINCT s) ORDER BY i.title"
