#!/usr/bin/env python3
"""Turn `context/` into database writes.

The five JSON files Nessie reads are exports, not source. Once per UTC day
`_fetch_context_files_from_db`
(`NessieAI/chat_nextseek/src/chat_nextseek/config.py:717-725`) runs
`SELECT * FROM dmac.sample_types_context`, `dmac.assay_context` and
`dmac.projects_context` and rewrites them in place, so editing an export changes
nothing that survives a day. `context/` is the hand-owned source; this program is
how it reaches a database.

    python scripts/context_gen.py --emit update --table all --out /tmp/context.sql
    python scripts/context_gen.py --emit seed --table assays --out startup/seed/sql/assay_context.sql

Nothing here connects to a database. It reads committed JSON and writes SQL text.
"""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def load_source(path: Path) -> list[dict]:
    """The curated rows at `path`, as a list of dicts.

    A relative path is tried against the working directory first and then
    against the repository root, so callers can name `context/projects.json`
    from anywhere.
    """
    candidate = Path(path)
    if not candidate.is_absolute() and not candidate.exists():
        candidate = REPO_ROOT / candidate
    rows = json.loads(candidate.read_text(encoding="utf-8"))
    if not isinstance(rows, list):
        raise ValueError(f"{path}: expected a list of rows")
    return rows


# --- the three context tables ------------------------------------------------
#
# Column spellings, and where each one is pinned:
#
#   assays        scripts/generate_assay_context_seed.py::COLUMNS, whose database
#                 side is map_assay's first choice for each field, which is what
#                 production answered with
#   sample_types  the lowercase keys map_sampletype reads in
#                 NessieAI/chat_nextseek/src/chat_nextseek/config.py
#   projects      the CREATE TABLE in startup/seed/sql/projects_context.sql
#
# NessieAI/tests/api/test_context_gen.py re-derives all three from those files
# and fails if this module drifts from them.

# Columns newer than every one of those fixtures, so a table created before this
# change does not have them. render_update emits an idempotent ALTER for each.
# Both are TEXT, not JSON: `projects_context` already stores `alternative_names`
# and `key_data_types` as JSON text in TEXT columns because `map_project` reads
# them with json.loads and a '|' split fallback, and these two are read the same
# way. A JSON column would be stricter than every sibling for no gain.
ADDED_COLUMNS = {
    "sample_types": {
        # Curated in context/sample_types.json; see context/README.md
        # "repository_attributes". Absent from the 2026-09-11 production pull.
        "repository_attributes": "TEXT NULL",
    },
    "projects": {
        # Generated by parse_pi, not curated: the free-text `pi` field parsed
        # into names the person-name rule can match without an LLM (plan D7).
        "pi_names": "TEXT NULL",
    },
}


class UnknownColumn(KeyError):
    """A curated row carries a key that is not a column of its table."""


class MissingKey(ValueError):
    """A curated row has no value for the column rows are keyed on."""


class Table:
    """One context table: where its rows come from and how they are written."""

    def __init__(self, name, source, key, columns, json_columns=(), int_columns=()):
        self.name = name
        self.source = Path(source)
        self.key = key
        self.columns = tuple(columns)
        self.json_columns = frozenset(json_columns)
        self.int_columns = frozenset(int_columns)


TABLES = {
    "sample_types": Table(
        name="sample_types_context",
        source="context/sample_types.json",
        key="sample_type",
        columns=(
            "sample_type", "sampletype_id", "name", "clade", "description", "Tags",
            "required_metadata", "standard_metadata", "possible_metadata_fields",
            "parent_sampletypes", "child_sampletypes",
            "associated_assay_parents", "associated_assay_children",
            "repository_attributes", "sampletype_file_link",
        ),
        json_columns=("repository_attributes",),
        int_columns=("sampletype_id",),
    ),
    "assays": Table(
        name="assay_context",
        source="context/assays.json",
        key="assay_name",
        columns=(
            "assay_name", "Description", "Tags", "Alternative_Assay_Names",
            "Required_Parent_Sample_Types", "Optional_Parent_Sample_Types",
            "Children_Sample_Types", "Parent_Clade_Type", "Child_Clade_Type",
            "AssaySheet_Link", "AssociatedRepository", "Critical_Attributes",
            "Protocols_Phrases", "Protocols_UIDs", "internal_assay_id",
        ),
        int_columns=("internal_assay_id",),
    ),
    "projects": Table(
        name="projects_context",
        source="context/projects.json",
        key="name",
        columns=(
            "name", "alternative_names", "entity_type", "project_id",
            "parent_project", "pi", "pi_names", "research_focus", "key_data_types",
            "description", "nih_reporter_link", "fairdomhub_published_link", "tags",
        ),
        json_columns=("alternative_names", "key_data_types", "pi_names"),
        int_columns=("project_id",),
    ),
}

COLUMNS = {name: table.columns for name, table in TABLES.items()}


def check_columns(table: str, rows: list[dict]) -> None:
    """Refuse rows whose keys are not columns, or that lack the natural key.

    A typo in a curated file has to fail here. The alternative is a column
    silently dropped at write time, which looks like a successful write.
    """
    spec = TABLES[table]
    known = set(spec.columns)
    for index, row in enumerate(rows):
        unknown = sorted(set(row) - known)
        if unknown:
            raise UnknownColumn(
                f"{spec.source} row {index}: {', '.join(unknown)} "
                f"{'is not a column' if len(unknown) == 1 else 'are not columns'} "
                f"of {table} ({spec.name})"
            )
        if not row.get(spec.key):
            raise MissingKey(f"{spec.source} row {index}: no {spec.key}, which rows are keyed on")


# --- the PI field ------------------------------------------------------------

# Anything that means "no PI recorded". The database and the curated files
# disagree about how to spell an absent value.
_NO_PI = {"", "none", "null", "n/a", "na", "-", "tbd", "unknown"}


def _split_outside_parens(value: str, separator: str = ";") -> list[str]:
    """Split on `separator`, ignoring separators inside parentheses.

    Required, not defensive: one curated row is
    `Griffith, Linda G. (MIT, PI; Scientific Director, Center for Gynepathology
    Research); Goods, Brittany A. (...)`. Splitting on every semicolon invents a
    PI called "Scientific Director, Center for Gynepathology Research".
    """
    parts, current, depth = [], [], 0
    for char in value:
        if char == "(":
            depth += 1
        elif char == ")":
            depth = max(0, depth - 1)
        if char == separator and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(char)
    parts.append("".join(current))
    return [part.strip() for part in parts if part.strip()]


def parse_pi(value) -> list[str]:
    """The names in a free-text `pi` field: each PI's surname, then their full name.

    `Last, First M. (Affiliation, role)`, semicolon-separated, the parenthetical
    optional. Returns names in file order, deduplicated, so the person-name rule
    can match a question's person name without an LLM (plan D7). An absent PI
    gives an empty list.

        >>> parse_pi("White, Forest M. (MIT, contact PI); Michor, Franziska (Dana-Farber, co-PI)")
        ['White', 'Forest M. White', 'Michor', 'Franziska Michor']
    """
    if value is None:
        return []
    text = str(value).strip()
    if text.lower() in _NO_PI:
        return []

    names: list[str] = []
    for entry in _split_outside_parens(text):
        # Drop the affiliation and role, which are not names.
        bare = entry.split("(", 1)[0].strip().rstrip(",").strip()
        if not bare or bare.lower() in _NO_PI:
            continue
        surname, _, given = (part.strip() for part in bare.partition(","))
        for name in (surname, f"{given} {surname}".strip() if given else surname):
            if name and name not in names:
                names.append(name)
    return names


def with_pi_names(rows: list[dict]) -> list[dict]:
    """Copies of `rows` carrying `pi_names` beside the free-text `pi`.

    Every row gains the column, including the ones with no PI, so the write never
    leaves it undefined. This happens before the database write, not after.
    """
    return [{**row, "pi_names": parse_pi(row.get("pi"))} for row in rows]


# --- rendering values --------------------------------------------------------


class UnsupportedValue(ValueError):
    """A value this renderer will not put in a SQL literal."""


class DuplicateKey(ValueError):
    """Two curated rows share a natural key, as MySQL would compare it."""


def json_text(value) -> str:
    """A JSON column's stored text.

    `json.dumps` defaults, which is how production already stores
    `alternative_names` (`'["Forest", "White", "U54"]'`), and `ensure_ascii=False`
    to match `context/README.md`'s convention and the utf8mb4 columns.
    """
    return json.dumps(value, ensure_ascii=False)


def db_value(table: str, column: str, value):
    """The Python value a column holds, before it becomes a SQL literal.

    One place so that the renderers and the round-trip check cannot disagree
    about it. Empty strings become NULL, which is how production stores them.
    """
    spec = TABLES[table]
    if column in spec.json_columns:
        return None if value is None else json_text(value)
    if value is None or value == "":
        return None
    if column in spec.int_columns:
        return int(value)
    return value


def literal(value) -> str:
    """A portable SQL literal: NULL, a bare integer, or a single-quoted string.

    Quotes are doubled rather than backslash-escaped and newlines stay literal, so
    the text means the same thing to MySQL and to the SQLite the round-trip check
    runs against. That is the whole reason this differs from
    `seed_literal` below, which keeps the committed seed files' one-line shape.

    A backslash is refused rather than guessed at: MySQL interprets `\\` inside a
    string literal and SQLite does not, so no single spelling survives both. No
    curated value contains one today (`test_no_curated_value_needs_a_backslash`),
    and if one ever does, this raises instead of writing something that means one
    thing to the generator's tests and another to production.
    """
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        raise UnsupportedValue(f"boolean {value!r}: no context column is boolean")
    if isinstance(value, int):
        return str(value)
    text = str(value)
    if "\\" in text:
        raise UnsupportedValue(
            f"{text[:60]!r} contains a backslash; MySQL and SQLite disagree about "
            "how to spell it, so add explicit handling rather than guessing"
        )
    return "'" + text.replace("'", "''") + "'"


def _checked_keys(table: str, rows: list[dict]) -> list[str]:
    """The rows' natural keys, refusing any collision MySQL would see.

    `sample_types_context`, `assay_context` and `projects_context` are all
    utf8mb4_unicode_ci, which compares case-insensitively and ignores trailing
    spaces. Two curated rows that differ only that way would collide in the unique
    key below, so they are refused here instead.
    """
    spec = TABLES[table]
    keys, seen = [], {}
    for index, row in enumerate(rows):
        key = str(row[spec.key])
        folded = key.strip().lower()
        if folded in seen:
            raise DuplicateKey(
                f"{spec.source}: rows {seen[folded]} and {index} both key on "
                f"{key!r} as MySQL compares it (case-insensitive, trailing space ignored)"
            )
        seen[folded] = index
        keys.append(key)
    return keys


# --- the update script -------------------------------------------------------

# The round-trip check splits the script here and applies only what follows, so
# that the MySQL-only preamble (information_schema, PREPARE, multi-table DELETE)
# does not have to be translated into another dialect to be tested.
ROWS_MARKER = "-- == rows =="

_IDEMPOTENT = """\
SET @nextseek_missing := (SELECT COUNT(*) = 0 FROM information_schema.{catalog}
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = '{table}' AND {name_column} = '{name}');
SET @nextseek_stmt := IF(@nextseek_missing, '{statement}', 'DO 0');
PREPARE nextseek_stmt FROM @nextseek_stmt;
EXECUTE nextseek_stmt;
DEALLOCATE PREPARE nextseek_stmt;
"""


def _add_column(table_name: str, column: str, definition: str) -> str:
    return _IDEMPOTENT.format(
        catalog="COLUMNS", table=table_name, name_column="COLUMN_NAME", name=column,
        statement=f"ALTER TABLE `{table_name}` ADD COLUMN `{column}` {definition}",
    )


def _add_unique_key(table_name: str, key: str) -> str:
    index = f"uq_{table_name}_{key}"
    return _IDEMPOTENT.format(
        catalog="STATISTICS", table=table_name, name_column="INDEX_NAME", name=index,
        statement=f"ALTER TABLE `{table_name}` ADD UNIQUE KEY `{index}` (`{key}`)",
    )


def render_update(table: str, rows: list[dict]) -> str:
    """The SQL that makes `table` hold exactly these rows, re-runnable.

    Four things happen before the upserts, in this order, and each one is needed
    against the 2026-09-11 production pull rather than hypothetical:

      1. **Add the columns the table may predate.** `repository_attributes` and
         `pi_names` are newer than every instance's table.
      2. **Delete the rows the curated source no longer names.** Production's
         `assay_context` holds 68 such names and `projects_context` holds one
         (`GBM`). An upsert alone leaves every one of them in place while
         reporting success.
      3. **Collapse duplicate keys, keeping the lowest id.** Production's
         `assay_context` has 22 duplicated `assay_name` values, 20 of them names
         the curated source carries, and the unique key in step 4 cannot be added
         while they exist.
      4. **Add the unique key.** `ON DUPLICATE KEY UPDATE` only fires against one,
         and no context table has one today.

    Then one upsert per row, which sets every column including the key: MySQL
    matches the key case-insensitively, so the one case-only correction in the
    curated data (`Chemical challenge` -> `Chemical Challenge`) needs the key
    reassigned or production keeps its old spelling.
    """
    if table == "mappings":
        return render_mappings(rows)
    spec = TABLES[table]
    check_columns(table, rows)
    keys = _checked_keys(table, rows)
    columns = ", ".join(f"`{c}`" for c in spec.columns)
    assignments = ", ".join(f"`{c}`=VALUES(`{c}`)" for c in spec.columns)

    out = [
        f"-- {spec.name}: {len(rows)} rows generated from {spec.source} by",
        "-- scripts/context_gen.py --emit update. Regenerate rather than hand-editing.",
        "--",
        "-- Re-runnable: every statement below is idempotent, so applying this twice",
        f"-- leaves {spec.name} holding exactly the {len(rows)} curated rows.",
        "",
        "-- 1. columns this instance's table may predate",
    ]
    for column, definition in ADDED_COLUMNS.get(table, {}).items():
        out.append(_add_column(spec.name, column, definition))
    out += [
        f"-- 2. rows {spec.source} no longer names",
        f"DELETE FROM `{spec.name}` WHERE `{spec.key}` NOT IN "
        f"({', '.join(literal(k) for k in keys)});",
        "",
        f"-- 3. duplicate `{spec.key}` values, keeping the lowest id",
        f"DELETE `a` FROM `{spec.name}` `a` JOIN `{spec.name}` `b` "
        f"ON `a`.`{spec.key}` = `b`.`{spec.key}` AND `a`.`id` > `b`.`id`;",
        "",
        "-- 4. the unique key the upsert fires against",
        _add_unique_key(spec.name, spec.key),
        ROWS_MARKER,
    ]
    for row in rows:
        values = ", ".join(literal(db_value(table, c, row.get(c))) for c in spec.columns)
        out.append(f"INSERT INTO `{spec.name}` ({columns}) VALUES ({values})\n"
                   f"  ON DUPLICATE KEY UPDATE {assignments};")
    return "\n".join(out) + "\n"


# --- the seed files ----------------------------------------------------------
#
# A fresh install gets these three tables from here, not from
# startup/seed/dmac.sql.gz: none of them has a Django migration, and regenerating
# that dump needs maintainer credentials for a remote host
# (startup/seed/README.md). assay_context.sql is the template every header
# follows, so a regenerated file is a diff of rows rather than of shape.
#
# Column types come from seek/models/nextseek.py::Sample_types_context for the
# sample types and from the committed DDL for the other two. The unique key on
# each natural key is what `ON DUPLICATE KEY UPDATE` fires against; before this
# change no context table had one, and `assay_context` could not have had one
# while its rows were two unreconciled sources merged.

DDL = {
    "sample_types": """\
-- Curated context for sample types: what each code means, which attributes it
-- collects, what it is made from and what it feeds. Generated from
-- context/sample_types.json by scripts/context_gen.py --emit seed; regenerate
-- rather than hand-editing.
--
-- Created in SQL like assay_context and for the same reason: no Django migration
-- references it, and it is absent from dmac.sql.gz because regenerating that seed
-- needs maintainer credentials for a remote host. Production has its own copy of
-- this table; this file is what gives the local and dev stacks one.
--
-- Column types follow seek/models/nextseek.py::Sample_types_context, which is
-- how the application reads and writes these rows. `Tags` is capitalised: it is
-- that model's one db_column override. `repository_attributes` is newer than the
-- model and is read as JSON text, like the JSON columns of projects_context.
CREATE TABLE IF NOT EXISTS sample_types_context (
  id                        INT AUTO_INCREMENT PRIMARY KEY,
  sample_type               VARCHAR(32)  NULL,
  sampletype_id             INT          NULL,
  name                      VARCHAR(255) NULL,
  clade                     VARCHAR(64)  NULL,
  description               TEXT         NULL,
  Tags                      TEXT         NULL,
  required_metadata         TEXT         NULL,
  standard_metadata         TEXT         NULL,
  possible_metadata_fields  TEXT         NULL,
  parent_sampletypes        TEXT         NULL,
  child_sampletypes         TEXT         NULL,
  associated_assay_parents  TEXT         NULL,
  associated_assay_children TEXT         NULL,
  repository_attributes     TEXT         NULL,
  sampletype_file_link      VARCHAR(255) NULL,
  UNIQUE KEY `uq_sample_types_context_sample_type` (`sample_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
""",
    "assays": """\
-- Curated context for internal assays: what each one consumes, produces and is
-- called. Generated from context/assays.json by
-- scripts/context_gen.py --emit seed; regenerate rather than hand-editing.
--
-- Created in SQL like sample_types_context and for the same reason: no Django
-- migration references it, and it is absent from dmac.sql.gz because
-- regenerating that seed needs maintainer credentials for a remote host.
-- Production has its own copy of this table; this file is what gives the local
-- and dev stacks one.
--
-- One row per internal assay, `assay_name` unique. Production's copy is still two
-- unreconciled sources merged, 217 rows with 22 duplicated names; the curated
-- source is what reconciles them, and the update SQL collapses the duplicates
-- before it adds the unique key.
CREATE TABLE IF NOT EXISTS assay_context (
  id                           INT AUTO_INCREMENT PRIMARY KEY,
  assay_name                   VARCHAR(255) NULL,
  Description                  TEXT         NULL,
  Tags                         TEXT         NULL,
  Alternative_Assay_Names      TEXT         NULL,
  Required_Parent_Sample_Types TEXT         NULL,
  Optional_Parent_Sample_Types TEXT         NULL,
  Children_Sample_Types        TEXT         NULL,
  Parent_Clade_Type            VARCHAR(64)  NULL,
  Child_Clade_Type             VARCHAR(64)  NULL,
  AssaySheet_Link              VARCHAR(255) NULL,
  AssociatedRepository         VARCHAR(255) NULL,
  Critical_Attributes          TEXT         NULL,
  Protocols_Phrases            TEXT         NULL,
  Protocols_UIDs               TEXT         NULL,
  internal_assay_id            INT          NULL,
  UNIQUE KEY `uq_assay_context_assay_name` (`assay_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
""",
    "projects": """\
-- Curated context for SEEK projects and investigations: who runs one, what it
-- studies, where it is published. Generated from context/projects.json by
-- scripts/context_gen.py --emit seed; regenerate rather than hand-editing.
--
-- Read by the project page header; every field is optional and the header falls
-- back to the SEEK title and description when the row is absent.
--
-- alternative_names, key_data_types and pi_names are JSON arrays stored as text,
-- matching how chat_nextseek's map_project already reads them: it json.loads the
-- value and falls back to splitting on '|'. pi_names is generated from the
-- free-text pi field by scripts/context_gen.py::parse_pi, never hand-written.
CREATE TABLE IF NOT EXISTS projects_context (
  id                        INT AUTO_INCREMENT PRIMARY KEY,
  name                      VARCHAR(255) NULL,
  alternative_names         TEXT         NULL,
  entity_type               VARCHAR(64)  NULL,
  project_id                INT          NULL,
  parent_project            VARCHAR(255) NULL,
  pi                        VARCHAR(255) NULL,
  pi_names                  TEXT         NULL,
  research_focus            TEXT         NULL,
  key_data_types            TEXT         NULL,
  description               TEXT         NULL,
  nih_reporter_link         VARCHAR(512) NULL,
  fairdomhub_published_link VARCHAR(512) NULL,
  tags                      TEXT         NULL,
  KEY idx_project_id (project_id),
  UNIQUE KEY `uq_projects_context_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
""",
}


def seed_literal(value) -> str:
    """A MySQL literal in the committed seed files' style.

    Newlines are escaped rather than emitted raw so every INSERT is exactly one
    line: 79 curated sample type values and 30 assay values run to a dozen
    sentences with embedded newlines, and a statement that spans lines makes the
    file painful to diff and to count. Carried over verbatim from the retired
    scripts/generate_assay_context_seed.py, which is why these files' shape did
    not change when this module took them over.

    This is MySQL-only, on purpose: `\\n` in a literal means a newline to MySQL and
    two characters to SQLite. `literal` above is the portable one.
    """
    if value is None:
        return "NULL"
    if isinstance(value, int) and not isinstance(value, bool):
        return str(value)
    text = str(value)
    # Backslash first, or it would double-escape everything added after it.
    text = text.replace("\\", "\\\\").replace("'", "\\'")
    text = text.replace("\r\n", "\\n").replace("\n", "\\n").replace("\r", "\\n")
    return "'" + text + "'"


def render_seed(table: str, rows: list[dict]) -> str:
    """The seed file for `table`: its DDL, then one INSERT per row per line."""
    if table not in TABLES:
        raise ValueError(
            f"{table!r} has no seed file. context/assay_mappings.json is a list of "
            "operations on rows that already exist in internal_assays and "
            "assays_internal_assays, not a table to seed; use --emit update."
        )
    spec = TABLES[table]
    check_columns(table, rows)
    _checked_keys(table, rows)
    columns = ", ".join(f"`{c}`" for c in spec.columns)
    out = [DDL[table]]
    for row in rows:
        values = ", ".join(seed_literal(db_value(table, c, row.get(c))) for c in spec.columns)
        out.append(f"INSERT INTO `{spec.name}` ({columns}) VALUES ({values});")
    return "\n".join(out) + "\n"


# --- the mapping operations --------------------------------------------------
#
# context/assay_mappings.json is not a table. It is a list of operations on rows
# that already exist in `dmac.internal_assays` and `dmac.assays_internal_assays`,
# applied grouped in the order context/README.md gives: renames, creates, maps and
# remaps, merges. Targets are named by title, after renames, and every `from_*`
# key is a production value so the generator can refuse if production has moved.
# Each statement's WHERE clause is that refusal and also what makes it a no-op on
# a second run.
#
# Each guard below is there for a measured reason, not a hypothetical one. Against
# the 2026-09-11 production pull: the 25 `map` ops name exactly the 25
# `assays_internal_assays` rows whose `internal_assay_id` is NULL; every `remap`
# matches a row carrying its stated `from_internal_assay_id`; and every
# `merge_internal` id and `rename_internal` from_title matches.
#
# The rename-before-create order is load-bearing, not stylistic. Exactly 2 of the
# 14 `create_internal` titles already exist in production, `Mass Spectrometry` and
# `Mass Spectrometry Analysis`, and they are exactly the 2 titles the renames free
# up (ids 130 and 47 become `Mass Spectrometry Proteomics` and `Mass Spectrometry
# Proteomics Analysis`). Run the creates first and their NOT EXISTS guard skips
# both, so the two new internal assays never exist and every remap aimed at them
# resolves to the old id instead. `test_the_renames_have_to_run_before_the_creates`
# pins that.

TABLES_EXTRA = {"mappings": Path("context/assay_mappings.json")}

MAPPING_KEYS = {
    "rename_internal": {"internal_assay_id", "from_title", "internal_assay_title"},
    "create_internal": {"internal_assay_title"},
    "map": {"seek_assay_id", "seek_title", "internal_assay_title"},
    "remap": {"seek_assay_id", "seek_title", "from_internal_assay_id", "internal_assay_title"},
    "merge_internal": {"internal_assay_id", "from_title", "into_internal_assay_title"},
}
MAPPING_ORDER = ("rename_internal", "create_internal", "map", "remap", "merge_internal")


class UnknownAction(ValueError):
    """A mapping row names an operation this generator does not implement."""


class MappingMismatch(ValueError):
    """assays.json and assay_mappings.json disagree about a new internal assay."""


def _by_title(title: str) -> str:
    """The subquery that resolves an internal assay title to its id.

    By title and never by id, because `create_internal` ids are assigned by the
    database, and after the rename group every title is the curated spelling.
    """
    return (f"(SELECT `id` FROM `internal_assays` WHERE `internal_assay_title` = "
            f"{literal(title)} ORDER BY `id` LIMIT 1)")


def check_mapping_consistency(assays: list[dict], mappings: list[dict]) -> None:
    """Refuse a new internal assay that only one of the two files knows about.

    context/README.md: a row in `assays.json` with `internal_assay_id: null` IS a
    `create_internal` entry, and its `assay_name` must equal that entry's title.
    A rename in one file that misses the other fails here rather than leaving an
    assay_context row pointing at nothing.
    """
    nameless = {r.get("assay_name") for r in assays if r.get("internal_assay_id") is None}
    created = {m.get("internal_assay_title") for m in mappings
               if m.get("action") == "create_internal"}
    if nameless != created:
        raise MappingMismatch(
            f"created but not in assays.json: {sorted(created - nameless)}; "
            f"null internal_assay_id but never created: {sorted(nameless - created)}"
        )


def _check_mapping_rows(rows: list[dict]) -> None:
    for index, row in enumerate(rows):
        action = row.get("action")
        if action not in MAPPING_KEYS:
            raise UnknownAction(f"assay_mappings.json row {index}: unknown action {action!r}")
        expected = MAPPING_KEYS[action]
        keys = set(row) - {"action"}
        if keys != expected:
            raise UnknownColumn(
                f"assay_mappings.json row {index} ({action}): expected "
                f"{sorted(expected)}, got {sorted(keys)}"
            )


def render_mappings(rows: list[dict]) -> str:
    """The SQL for `context/assay_mappings.json`, grouped and re-runnable."""
    _check_mapping_rows(rows)
    grouped = {action: [r for r in rows if r["action"] == action] for action in MAPPING_ORDER}

    out = [
        f"-- internal_assays and assays_internal_assays: {len(rows)} operations generated",
        "-- from context/assay_mappings.json by scripts/context_gen.py --emit update.",
        "--",
        "-- Grouped in context/README.md's order. Every WHERE clause pins the production",
        "-- value the operation was written against, so an operation whose target has",
        "-- moved affects no rows instead of writing the wrong one, and a second run is",
        "-- a no-op.",
        "",
        f"-- rename_internal: {len(grouped['rename_internal'])}",
    ]
    for row in grouped["rename_internal"]:
        out.append(
            f"UPDATE `internal_assays` SET `internal_assay_title` = "
            f"{literal(row['internal_assay_title'])}\n"
            f"  WHERE `id` = {int(row['internal_assay_id'])} AND `internal_assay_title` IN "
            f"({literal(row['from_title'])}, {literal(row['internal_assay_title'])});"
        )

    out += ["", f"-- create_internal: {len(grouped['create_internal'])}. These run AFTER the "
                "renames on purpose: two of the",
            "-- titles are ones a rename above frees up, and the guard would skip them.",
            "-- The guard itself is what makes a second run a no-op."]
    for row in grouped["create_internal"]:
        title = literal(row["internal_assay_title"])
        out.append(
            f"INSERT INTO `internal_assays` (`internal_assay_title`) SELECT {title} FROM DUAL\n"
            f"  WHERE NOT EXISTS (SELECT 1 FROM `internal_assays` "
            f"WHERE `internal_assay_title` = {title});"
        )

    out += ["", f"-- map and remap: {len(grouped['map'])} + {len(grouped['remap'])}. A map only "
                "fills a NULL; a remap only",
            "-- moves the internal assay it was written against."]
    for row in grouped["map"]:
        out.append(
            f"-- {row['seek_title']} (SEEK assay {int(row['seek_assay_id'])})\n"
            f"UPDATE `assays_internal_assays` SET `internal_assay_id` = "
            f"{_by_title(row['internal_assay_title'])}\n"
            f"  WHERE `assay_id` = {int(row['seek_assay_id'])} AND `internal_assay_id` IS NULL;"
        )
    for row in grouped["remap"]:
        target = _by_title(row["internal_assay_title"])
        out.append(
            f"-- {row['seek_title']} (SEEK assay {int(row['seek_assay_id'])})\n"
            f"UPDATE `assays_internal_assays` SET `internal_assay_id` = {target}\n"
            f"  WHERE `assay_id` = {int(row['seek_assay_id'])} AND `internal_assay_id` IN "
            f"({int(row['from_internal_assay_id'])}, {target});"
        )

    out += ["", f"-- merge_internal: {len(grouped['merge_internal'])}. Each one refuses while any "
                "SEEK assay still points at it,",
            "-- which is what makes the remaps above a precondition rather than an intention."]
    for row in grouped["merge_internal"]:
        assay_id = int(row["internal_assay_id"])
        out.append(
            f"-- into {row['into_internal_assay_title']}\n"
            f"DELETE FROM `internal_assays` WHERE `id` = {assay_id} AND "
            f"`internal_assay_title` = {literal(row['from_title'])}\n"
            f"  AND NOT EXISTS (SELECT 1 FROM `assays_internal_assays` "
            f"WHERE `internal_assay_id` = {assay_id});"
        )
    return "\n".join(out) + "\n"


# --- the command line --------------------------------------------------------

SEED_FILES = {"sample_types": "sample_types_context.sql",
              "assays": "assay_context.sql",
              "projects": "projects_context.sql"}
SEED_DIR = Path("startup/seed/sql")


def rows_for(table: str) -> list[dict]:
    """The curated rows for `table`, with everything the generator adds."""
    if table in TABLES_EXTRA:
        return load_source(TABLES_EXTRA[table])
    rows = load_source(TABLES[table].source)
    return with_pi_names(rows) if table == "projects" else rows


def _emit(text: str, out) -> None:
    if out is None:
        print(text, end="")
        return
    path = Path(out)
    if not path.is_absolute():
        path = Path.cwd() / path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"wrote {out} ({len(text.splitlines())} lines)")


def main(argv=None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--emit", required=True, choices=("update", "seed"),
                        help="update: SQL for a live database. seed: a fresh install's file.")
    parser.add_argument("--table", default="all",
                        choices=("all",) + tuple(TABLES) + tuple(TABLES_EXTRA),
                        help="which table, or all of them")
    parser.add_argument("--out", default=None,
                        help="a file for --emit update (default stdout), or the seed "
                             f"directory for --emit seed (default {SEED_DIR})")
    args = parser.parse_args(argv)

    if args.table == "all":
        tables = list(TABLES) + (list(TABLES_EXTRA) if args.emit == "update" else [])
    else:
        tables = [args.table]
    if {"assays", "mappings"} <= set(tables):
        # Both files describe the same new internal assays; refuse if they disagree.
        check_mapping_consistency(rows_for("assays"), rows_for("mappings"))
    if args.emit == "seed":
        directory = Path(args.out) if args.out else (REPO_ROOT / SEED_DIR)
        for table in tables:
            _emit(render_seed(table, rows_for(table)), directory / SEED_FILES[table])
        return 0
    _emit("\n".join(render_update(table, rows_for(table)) for table in tables), args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
