#!/usr/bin/env python3
"""Turn `context/` into database writes.

The five JSON files Nessie reads are exports, not source. Once per UTC day
`_fetch_context_files_from_db`
(`NessieAI/chat_nextseek/src/chat_nextseek/config.py:717-725`) runs
`SELECT * FROM dmac.sample_types_context`, `dmac.assay_context` and
`dmac.projects_context` and rewrites them in place, so editing an export changes
nothing that survives a day. `context/` is the hand-owned source; this program is
how it reaches a database.

    python scripts/context_gen.py --emit update --table all --out /tmp/context.sql
    python scripts/context_gen.py --emit seed --table assays --out startup/seed/sql/assay_context.sql

Nothing here connects to a database. It reads committed JSON and writes SQL text.
"""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def load_source(path: Path) -> list[dict]:
    """The curated rows at `path`, as a list of dicts.

    A relative path is tried against the working directory first and then
    against the repository root, so callers can name `context/projects.json`
    from anywhere.
    """
    candidate = Path(path)
    if not candidate.is_absolute() and not candidate.exists():
        candidate = REPO_ROOT / candidate
    rows = json.loads(candidate.read_text(encoding="utf-8"))
    if not isinstance(rows, list):
        raise ValueError(f"{path}: expected a list of rows")
    return rows


# --- the three context tables ------------------------------------------------
#
# Column spellings, and where each one is pinned:
#
#   assays        scripts/generate_assay_context_seed.py::COLUMNS, whose database
#                 side is map_assay's first choice for each field, which is what
#                 production answered with
#   sample_types  the lowercase keys map_sampletype reads in
#                 NessieAI/chat_nextseek/src/chat_nextseek/config.py
#   projects      the CREATE TABLE in startup/seed/sql/projects_context.sql
#
# NessieAI/tests/api/test_context_gen.py re-derives all three from those files
# and fails if this module drifts from them.

# Columns newer than every one of those fixtures, so a table created before this
# change does not have them. render_update emits an idempotent ALTER for each.
ADDED_COLUMNS = {
    "sample_types": {
        # Curated in context/sample_types.json; see context/README.md
        # "repository_attributes". Absent from the 2026-09-11 production pull.
        "repository_attributes": "JSON NULL",
    },
    "projects": {
        # Generated by parse_pi, not curated: the free-text `pi` field parsed
        # into names the person-name rule can match without an LLM (plan D7).
        "pi_names": "JSON NULL",
    },
}


class UnknownColumn(KeyError):
    """A curated row carries a key that is not a column of its table."""


class MissingKey(ValueError):
    """A curated row has no value for the column rows are keyed on."""


class Table:
    """One context table: where its rows come from and how they are written."""

    def __init__(self, name, source, key, columns, json_columns=(), int_columns=()):
        self.name = name
        self.source = Path(source)
        self.key = key
        self.columns = tuple(columns)
        self.json_columns = frozenset(json_columns)
        self.int_columns = frozenset(int_columns)


TABLES = {
    "sample_types": Table(
        name="sample_types_context",
        source="context/sample_types.json",
        key="sample_type",
        columns=(
            "sample_type", "sampletype_id", "name", "clade", "description", "Tags",
            "required_metadata", "standard_metadata", "possible_metadata_fields",
            "parent_sampletypes", "child_sampletypes",
            "associated_assay_parents", "associated_assay_children",
            "repository_attributes", "sampletype_file_link",
        ),
        json_columns=("repository_attributes",),
        int_columns=("sampletype_id",),
    ),
    "assays": Table(
        name="assay_context",
        source="context/assays.json",
        key="assay_name",
        columns=(
            "assay_name", "Description", "Tags", "Alternative_Assay_Names",
            "Required_Parent_Sample_Types", "Optional_Parent_Sample_Types",
            "Children_Sample_Types", "Parent_Clade_Type", "Child_Clade_Type",
            "AssaySheet_Link", "AssociatedRepository", "Critical_Attributes",
            "Protocols_Phrases", "Protocols_UIDs", "internal_assay_id",
        ),
        int_columns=("internal_assay_id",),
    ),
    "projects": Table(
        name="projects_context",
        source="context/projects.json",
        key="name",
        columns=(
            "name", "alternative_names", "entity_type", "project_id",
            "parent_project", "pi", "pi_names", "research_focus", "key_data_types",
            "description", "nih_reporter_link", "fairdomhub_published_link", "tags",
        ),
        json_columns=("alternative_names", "key_data_types", "pi_names"),
        int_columns=("project_id",),
    ),
}

COLUMNS = {name: table.columns for name, table in TABLES.items()}


def check_columns(table: str, rows: list[dict]) -> None:
    """Refuse rows whose keys are not columns, or that lack the natural key.

    A typo in a curated file has to fail here. The alternative is a column
    silently dropped at write time, which looks like a successful write.
    """
    spec = TABLES[table]
    known = set(spec.columns)
    for index, row in enumerate(rows):
        unknown = sorted(set(row) - known)
        if unknown:
            raise UnknownColumn(
                f"{spec.source} row {index}: {', '.join(unknown)} "
                f"{'is not a column' if len(unknown) == 1 else 'are not columns'} "
                f"of {table} ({spec.name})"
            )
        if not row.get(spec.key):
            raise MissingKey(f"{spec.source} row {index}: no {spec.key}, which rows are keyed on")


# --- the PI field ------------------------------------------------------------

# Anything that means "no PI recorded". The database and the curated files
# disagree about how to spell an absent value.
_NO_PI = {"", "none", "null", "n/a", "na", "-", "tbd", "unknown"}


def _split_outside_parens(value: str, separator: str = ";") -> list[str]:
    """Split on `separator`, ignoring separators inside parentheses.

    Required, not defensive: one curated row is
    `Griffith, Linda G. (MIT, PI; Scientific Director, Center for Gynepathology
    Research); Goods, Brittany A. (...)`. Splitting on every semicolon invents a
    PI called "Scientific Director, Center for Gynepathology Research".
    """
    parts, current, depth = [], [], 0
    for char in value:
        if char == "(":
            depth += 1
        elif char == ")":
            depth = max(0, depth - 1)
        if char == separator and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(char)
    parts.append("".join(current))
    return [part.strip() for part in parts if part.strip()]


def parse_pi(value) -> list[str]:
    """The names in a free-text `pi` field: each PI's surname, then their full name.

    `Last, First M. (Affiliation, role)`, semicolon-separated, the parenthetical
    optional. Returns names in file order, deduplicated, so the person-name rule
    can match a question's person name without an LLM (plan D7). An absent PI
    gives an empty list.

        >>> parse_pi("White, Forest M. (MIT, contact PI); Michor, Franziska (Dana-Farber, co-PI)")
        ['White', 'Forest M. White', 'Michor', 'Franziska Michor']
    """
    if value is None:
        return []
    text = str(value).strip()
    if text.lower() in _NO_PI:
        return []

    names: list[str] = []
    for entry in _split_outside_parens(text):
        # Drop the affiliation and role, which are not names.
        bare = entry.split("(", 1)[0].strip().rstrip(",").strip()
        if not bare or bare.lower() in _NO_PI:
            continue
        surname, _, given = (part.strip() for part in bare.partition(","))
        for name in (surname, f"{given} {surname}".strip() if given else surname):
            if name and name not in names:
                names.append(name)
    return names


def with_pi_names(rows: list[dict]) -> list[dict]:
    """Copies of `rows` carrying `pi_names` beside the free-text `pi`.

    Every row gains the column, including the ones with no PI, so the write never
    leaves it undefined. This happens before the database write, not after.
    """
    return [{**row, "pi_names": parse_pi(row.get("pi"))} for row in rows]


# --- rendering values --------------------------------------------------------


class UnsupportedValue(ValueError):
    """A value this renderer will not put in a SQL literal."""


class DuplicateKey(ValueError):
    """Two curated rows share a natural key, as MySQL would compare it."""


def json_text(value) -> str:
    """A JSON column's stored text.

    `json.dumps` defaults, which is how production already stores
    `alternative_names` (`'["Forest", "White", "U54"]'`), and `ensure_ascii=False`
    to match `context/README.md`'s convention and the utf8mb4 columns.
    """
    return json.dumps(value, ensure_ascii=False)


def db_value(table: str, column: str, value):
    """The Python value a column holds, before it becomes a SQL literal.

    One place so that the renderers and the round-trip check cannot disagree
    about it. Empty strings become NULL, which is how production stores them.
    """
    spec = TABLES[table]
    if column in spec.json_columns:
        return None if value is None else json_text(value)
    if value is None or value == "":
        return None
    if column in spec.int_columns:
        return int(value)
    return value


def literal(value) -> str:
    """A portable SQL literal: NULL, a bare integer, or a single-quoted string.

    Quotes are doubled rather than backslash-escaped and newlines stay literal, so
    the text means the same thing to MySQL and to the SQLite the round-trip check
    runs against. That is the whole reason this differs from
    `seed_literal` below, which keeps the committed seed files' one-line shape.

    A backslash is refused rather than guessed at: MySQL interprets `\\` inside a
    string literal and SQLite does not, so no single spelling survives both. No
    curated value contains one today (`test_no_curated_value_needs_a_backslash`),
    and if one ever does, this raises instead of writing something that means one
    thing to the generator's tests and another to production.
    """
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        raise UnsupportedValue(f"boolean {value!r}: no context column is boolean")
    if isinstance(value, int):
        return str(value)
    text = str(value)
    if "\\" in text:
        raise UnsupportedValue(
            f"{text[:60]!r} contains a backslash; MySQL and SQLite disagree about "
            "how to spell it, so add explicit handling rather than guessing"
        )
    return "'" + text.replace("'", "''") + "'"


def _checked_keys(table: str, rows: list[dict]) -> list[str]:
    """The rows' natural keys, refusing any collision MySQL would see.

    `sample_types_context`, `assay_context` and `projects_context` are all
    utf8mb4_unicode_ci, which compares case-insensitively and ignores trailing
    spaces. Two curated rows that differ only that way would collide in the unique
    key below, so they are refused here instead.
    """
    spec = TABLES[table]
    keys, seen = [], {}
    for index, row in enumerate(rows):
        key = str(row[spec.key])
        folded = key.strip().lower()
        if folded in seen:
            raise DuplicateKey(
                f"{spec.source}: rows {seen[folded]} and {index} both key on "
                f"{key!r} as MySQL compares it (case-insensitive, trailing space ignored)"
            )
        seen[folded] = index
        keys.append(key)
    return keys


# --- the update script -------------------------------------------------------

# The round-trip check splits the script here and applies only what follows, so
# that the MySQL-only preamble (information_schema, PREPARE, multi-table DELETE)
# does not have to be translated into another dialect to be tested.
ROWS_MARKER = "-- == rows =="

_IDEMPOTENT = """\
SET @nextseek_missing := (SELECT COUNT(*) = 0 FROM information_schema.{catalog}
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = '{table}' AND {name_column} = '{name}');
SET @nextseek_stmt := IF(@nextseek_missing, '{statement}', 'DO 0');
PREPARE nextseek_stmt FROM @nextseek_stmt;
EXECUTE nextseek_stmt;
DEALLOCATE PREPARE nextseek_stmt;
"""


def _add_column(table_name: str, column: str, definition: str) -> str:
    return _IDEMPOTENT.format(
        catalog="COLUMNS", table=table_name, name_column="COLUMN_NAME", name=column,
        statement=f"ALTER TABLE `{table_name}` ADD COLUMN `{column}` {definition}",
    )


def _add_unique_key(table_name: str, key: str) -> str:
    index = f"uq_{table_name}_{key}"
    return _IDEMPOTENT.format(
        catalog="STATISTICS", table=table_name, name_column="INDEX_NAME", name=index,
        statement=f"ALTER TABLE `{table_name}` ADD UNIQUE KEY `{index}` (`{key}`)",
    )


def render_update(table: str, rows: list[dict]) -> str:
    """The SQL that makes `table` hold exactly these rows, re-runnable.

    Four things happen before the upserts, in this order, and each one is needed
    against the 2026-09-11 production pull rather than hypothetical:

      1. **Add the columns the table may predate.** `repository_attributes` and
         `pi_names` are newer than every instance's table.
      2. **Delete the rows the curated source no longer names.** Production's
         `assay_context` holds 68 such names and `projects_context` holds one
         (`GBM`). An upsert alone leaves every one of them in place while
         reporting success.
      3. **Collapse duplicate keys, keeping the lowest id.** Production's
         `assay_context` has 22 duplicated `assay_name` values, 20 of them names
         the curated source carries, and the unique key in step 4 cannot be added
         while they exist.
      4. **Add the unique key.** `ON DUPLICATE KEY UPDATE` only fires against one,
         and no context table has one today.

    Then one upsert per row, which sets every column including the key: MySQL
    matches the key case-insensitively, so the one case-only correction in the
    curated data (`Chemical challenge` -> `Chemical Challenge`) needs the key
    reassigned or production keeps its old spelling.
    """
    spec = TABLES[table]
    check_columns(table, rows)
    keys = _checked_keys(table, rows)
    columns = ", ".join(f"`{c}`" for c in spec.columns)
    assignments = ", ".join(f"`{c}`=VALUES(`{c}`)" for c in spec.columns)

    out = [
        f"-- {spec.name}: {len(rows)} rows generated from {spec.source} by",
        "-- scripts/context_gen.py --emit update. Regenerate rather than hand-editing.",
        "--",
        "-- Re-runnable: every statement below is idempotent, so applying this twice",
        f"-- leaves {spec.name} holding exactly the {len(rows)} curated rows.",
        "",
        "-- 1. columns this instance's table may predate",
    ]
    for column, definition in ADDED_COLUMNS.get(table, {}).items():
        out.append(_add_column(spec.name, column, definition))
    out += [
        f"-- 2. rows {spec.source} no longer names",
        f"DELETE FROM `{spec.name}` WHERE `{spec.key}` NOT IN "
        f"({', '.join(literal(k) for k in keys)});",
        "",
        f"-- 3. duplicate `{spec.key}` values, keeping the lowest id",
        f"DELETE `a` FROM `{spec.name}` `a` JOIN `{spec.name}` `b` "
        f"ON `a`.`{spec.key}` = `b`.`{spec.key}` AND `a`.`id` > `b`.`id`;",
        "",
        "-- 4. the unique key the upsert fires against",
        _add_unique_key(spec.name, spec.key),
        ROWS_MARKER,
    ]
    for row in rows:
        values = ", ".join(literal(db_value(table, c, row.get(c))) for c in spec.columns)
        out.append(f"INSERT INTO `{spec.name}` ({columns}) VALUES ({values})\n"
                   f"  ON DUPLICATE KEY UPDATE {assignments};")
    return "\n".join(out) + "\n"
