#!/usr/bin/env python3
"""Turn `context/` into database writes.

The five JSON files Nessie reads are exports, not source. Once per UTC day
`_fetch_context_files_from_db`
(`NessieAI/chat_nextseek/src/chat_nextseek/config.py:717-725`) runs
`SELECT * FROM dmac.sample_types_context`, `dmac.assay_context` and
`dmac.projects_context` and rewrites them in place, so editing an export changes
nothing that survives a day. `context/` is the hand-owned source; this program is
how it reaches a database.

    python scripts/context_gen.py --emit update --table all --out /tmp/context.sql
    python scripts/context_gen.py --emit seed --table assays --out startup/seed/sql/assay_context.sql

Nothing here connects to a database. It reads committed JSON and writes SQL text.
"""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def load_source(path: Path) -> list[dict]:
    """The curated rows at `path`, as a list of dicts.

    A relative path is tried against the working directory first and then
    against the repository root, so callers can name `context/projects.json`
    from anywhere.
    """
    candidate = Path(path)
    if not candidate.is_absolute() and not candidate.exists():
        candidate = REPO_ROOT / candidate
    rows = json.loads(candidate.read_text(encoding="utf-8"))
    if not isinstance(rows, list):
        raise ValueError(f"{path}: expected a list of rows")
    return rows


# --- the three context tables ------------------------------------------------
#
# Column spellings, and where each one is pinned:
#
#   assays        scripts/generate_assay_context_seed.py::COLUMNS, whose database
#                 side is map_assay's first choice for each field, which is what
#                 production answered with
#   sample_types  the lowercase keys map_sampletype reads in
#                 NessieAI/chat_nextseek/src/chat_nextseek/config.py
#   projects      the CREATE TABLE in startup/seed/sql/projects_context.sql
#
# NessieAI/tests/api/test_context_gen.py re-derives all three from those files
# and fails if this module drifts from them.

# Columns newer than every one of those fixtures, so a table created before this
# change does not have them. render_update emits an idempotent ALTER for each.
ADDED_COLUMNS = {
    "sample_types": {
        # Curated in context/sample_types.json; see context/README.md
        # "repository_attributes". Absent from the 2026-09-11 production pull.
        "repository_attributes": "JSON NULL",
    },
    "projects": {
        # Generated by parse_pi, not curated: the free-text `pi` field parsed
        # into names the person-name rule can match without an LLM (plan D7).
        "pi_names": "JSON NULL",
    },
}


class UnknownColumn(KeyError):
    """A curated row carries a key that is not a column of its table."""


class MissingKey(ValueError):
    """A curated row has no value for the column rows are keyed on."""


class Table:
    """One context table: where its rows come from and how they are written."""

    def __init__(self, name, source, key, columns, json_columns=(), int_columns=()):
        self.name = name
        self.source = Path(source)
        self.key = key
        self.columns = tuple(columns)
        self.json_columns = frozenset(json_columns)
        self.int_columns = frozenset(int_columns)


TABLES = {
    "sample_types": Table(
        name="sample_types_context",
        source="context/sample_types.json",
        key="sample_type",
        columns=(
            "sample_type", "sampletype_id", "name", "clade", "description", "Tags",
            "required_metadata", "standard_metadata", "possible_metadata_fields",
            "parent_sampletypes", "child_sampletypes",
            "associated_assay_parents", "associated_assay_children",
            "repository_attributes", "sampletype_file_link",
        ),
        json_columns=("repository_attributes",),
        int_columns=("sampletype_id",),
    ),
    "assays": Table(
        name="assay_context",
        source="context/assays.json",
        key="assay_name",
        columns=(
            "assay_name", "Description", "Tags", "Alternative_Assay_Names",
            "Required_Parent_Sample_Types", "Optional_Parent_Sample_Types",
            "Children_Sample_Types", "Parent_Clade_Type", "Child_Clade_Type",
            "AssaySheet_Link", "AssociatedRepository", "Critical_Attributes",
            "Protocols_Phrases", "Protocols_UIDs", "internal_assay_id",
        ),
        int_columns=("internal_assay_id",),
    ),
    "projects": Table(
        name="projects_context",
        source="context/projects.json",
        key="name",
        columns=(
            "name", "alternative_names", "entity_type", "project_id",
            "parent_project", "pi", "pi_names", "research_focus", "key_data_types",
            "description", "nih_reporter_link", "fairdomhub_published_link", "tags",
        ),
        json_columns=("alternative_names", "key_data_types", "pi_names"),
        int_columns=("project_id",),
    ),
}

COLUMNS = {name: table.columns for name, table in TABLES.items()}


def check_columns(table: str, rows: list[dict]) -> None:
    """Refuse rows whose keys are not columns, or that lack the natural key.

    A typo in a curated file has to fail here. The alternative is a column
    silently dropped at write time, which looks like a successful write.
    """
    spec = TABLES[table]
    known = set(spec.columns)
    for index, row in enumerate(rows):
        unknown = sorted(set(row) - known)
        if unknown:
            raise UnknownColumn(
                f"{spec.source} row {index}: {', '.join(unknown)} "
                f"{'is not a column' if len(unknown) == 1 else 'are not columns'} "
                f"of {table} ({spec.name})"
            )
        if not row.get(spec.key):
            raise MissingKey(f"{spec.source} row {index}: no {spec.key}, which rows are keyed on")


# --- the PI field ------------------------------------------------------------

# Anything that means "no PI recorded". The database and the curated files
# disagree about how to spell an absent value.
_NO_PI = {"", "none", "null", "n/a", "na", "-", "tbd", "unknown"}


def _split_outside_parens(value: str, separator: str = ";") -> list[str]:
    """Split on `separator`, ignoring separators inside parentheses.

    Required, not defensive: one curated row is
    `Griffith, Linda G. (MIT, PI; Scientific Director, Center for Gynepathology
    Research); Goods, Brittany A. (...)`. Splitting on every semicolon invents a
    PI called "Scientific Director, Center for Gynepathology Research".
    """
    parts, current, depth = [], [], 0
    for char in value:
        if char == "(":
            depth += 1
        elif char == ")":
            depth = max(0, depth - 1)
        if char == separator and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(char)
    parts.append("".join(current))
    return [part.strip() for part in parts if part.strip()]


def parse_pi(value) -> list[str]:
    """The names in a free-text `pi` field: each PI's surname, then their full name.

    `Last, First M. (Affiliation, role)`, semicolon-separated, the parenthetical
    optional. Returns names in file order, deduplicated, so the person-name rule
    can match a question's person name without an LLM (plan D7). An absent PI
    gives an empty list.

        >>> parse_pi("White, Forest M. (MIT, contact PI); Michor, Franziska (Dana-Farber, co-PI)")
        ['White', 'Forest M. White', 'Michor', 'Franziska Michor']
    """
    if value is None:
        return []
    text = str(value).strip()
    if text.lower() in _NO_PI:
        return []

    names: list[str] = []
    for entry in _split_outside_parens(text):
        # Drop the affiliation and role, which are not names.
        bare = entry.split("(", 1)[0].strip().rstrip(",").strip()
        if not bare or bare.lower() in _NO_PI:
            continue
        surname, _, given = (part.strip() for part in bare.partition(","))
        for name in (surname, f"{given} {surname}".strip() if given else surname):
            if name and name not in names:
                names.append(name)
    return names


def with_pi_names(rows: list[dict]) -> list[dict]:
    """Copies of `rows` carrying `pi_names` beside the free-text `pi`.

    Every row gains the column, including the ones with no PI, so the write never
    leaves it undefined. This happens before the database write, not after.
    """
    return [{**row, "pi_names": parse_pi(row.get("pi"))} for row in rows]
