# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (11)
# #########################################################################

class ArtifactKind(str, Enum):
    GEO_XLSX = "GEO_XLSX"
    SRA_PACKAGE = "SRA_PACKAGE"
    PRIDE_PACKAGE = "PRIDE_PACKAGE"
    NFCORE_RNASEQ_CSV = "NFCORE_RNASEQ_CSV"
    NFCORE_SCRNASEQ_CSV = "NFCORE_SCRNASEQ_CSV"
    SVG_CHART = "SVG_CHART"
    UNKNOWN_FILE = "UNKNOWN_FILE"
    NONE_EXPECTED = "NONE_EXPECTED"

class ArtifactStatus(str, Enum):
    Valid = "Valid"
    Missing = "Missing"
    Inaccessible = "Inaccessible"
    Unreadable = "Unreadable"
    SchemaInvalid = "SchemaInvalid"
    Incomplete = "Incomplete"
    RuntimeFailed = "RuntimeFailed"
    PartialAfterFailure = "PartialAfterFailure"
    Indeterminate = "Indeterminate"
    NotExpected = "NotExpected"

class ExpectedBehavior(str, Enum):
    AnswerDirectly = "AnswerDirectly"
    GenerateArtifact = "GenerateArtifact"
    ClarifyIfAmbiguous = "ClarifyIfAmbiguous"
    UsePriorContext = "UsePriorContext"
    StateUnsupportedBoundary = "StateUnsupportedBoundary"
    RefuseUnsafeOnly = "RefuseUnsafeOnly"

class FailureMode(str, Enum):
    None_ = "None_"
    Timeout = "Timeout"
    Error = "Error"
    NoAnswer = "NoAnswer"

class FunctionalOutcome(str, Enum):
    FullySatisfied = "FullySatisfied"
    PartiallySatisfied = "PartiallySatisfied"
    AppropriateClarification = "AppropriateClarification"
    AppropriateBoundary = "AppropriateBoundary"
    NotSatisfied = "NotSatisfied"
    NotAssessable = "NotAssessable"

class JudgeVerdict(str, Enum):
    Passed = "Passed"
    Failed = "Failed"
    Refused = "Refused"
    Unsupported = "Unsupported"
    Fabricated = "Fabricated"
    Error = "Error"

class ModelClass(str, Enum):
    Sonnet = "Sonnet"
    Haiku = "Haiku"
    Opus = "Opus"

class PrimaryIssue(str, Enum):
    NoIssue = "NoIssue"
    RuntimeFailure = "RuntimeFailure"
    Timeout = "Timeout"
    MissingArtifact = "MissingArtifact"
    InvalidArtifact = "InvalidArtifact"
    IncompleteArtifact = "IncompleteArtifact"
    MissingContext = "MissingContext"
    AmbiguousRequest = "AmbiguousRequest"
    OverBroadSearch = "OverBroadSearch"
    UpstreamApiError = "UpstreamApiError"
    UnsupportedRequest = "UnsupportedRequest"
    RefusalError = "RefusalError"
    OverclaimedSuccess = "OverclaimedSuccess"
    InsufficientEvidence = "InsufficientEvidence"
    Other = "Other"

class ReviewPriority(str, Enum):
    Low = "Low"
    Medium = "Medium"
    High = "High"

class Route(str, Enum):
    NextseekQuery = "NextseekQuery"
    ContainerCC = "ContainerCC"
    Unrelated = "Unrelated"

class RouterJudgeVerdict(str, Enum):
    Pass = "Pass"
    Fail = "Fail"
    Inconclusive = "Inconclusive"

# #########################################################################
# Generated classes (10)
# #########################################################################

class FunctionalEvaluation(BaseModel):
    outcome: FunctionalOutcome
    usefulness_score: int = Field(description='0 to 4. 0 = unusable, 4 = fully useful.')
    primary_issue: typing.Union[PrimaryIssue, str]
    needs_human_review: bool
    review_priority: ReviewPriority
    rationale: str = Field(description='One or two concise sentences.')

class FunctionalEvaluationInput(BaseModel):
    task_family: str
    query_text: str
    final_answer: typing.Optional[str] = None
    answer_provided: bool
    runtime_success: bool
    failure_mode: FailureMode
    expected_behavior: typing.Union[ExpectedBehavior, str]
    artifact_expected: bool
    artifact_status: typing.Optional[ArtifactStatus] = None
    artifact_kind: typing.Optional[typing.Union[ArtifactKind, str]] = None
    declared_artifact_count: int

class RouteCapability(BaseModel):
    route_name: str
    description: str
    tools: typing.List[str]
    best_for: typing.Optional[str] = None
    not_for: typing.Optional[str] = None
    task_families: typing.List["TaskFamily"]

class RouterDecision(BaseModel):
    route: Route
    model_class: typing.Optional[ModelClass] = None
    reasoning: str

class RouterInput(BaseModel):
    user_query: str
    routes: typing.List["RouteCapability"]

class RouterJudgeInput(BaseModel):
    query_id: str
    query_text: str
    expected_route: str
    actual_route: str
    reply_text: str
    frames_summary: str

class RouterJudgeOutput(BaseModel):
    verdict: RouterJudgeVerdict
    reasoning: str

class SimpleEvaluatorInput(BaseModel):
    query: str
    pass_criteria: str
    ui_answer: str

class SimpleEvaluatorOutput(BaseModel):
    verdict: JudgeVerdict
    reasoning: str
    model: str

class TaskFamily(BaseModel):
    name: str
    description: str
    example_queries: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
