# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.FunctionalEvaluation": types.FunctionalEvaluation,
    "stream_types.FunctionalEvaluation": stream_types.FunctionalEvaluation,

    "types.FunctionalEvaluationInput": types.FunctionalEvaluationInput,
    "stream_types.FunctionalEvaluationInput": stream_types.FunctionalEvaluationInput,

    "types.RouteCapability": types.RouteCapability,
    "stream_types.RouteCapability": stream_types.RouteCapability,

    "types.RouterDecision": types.RouterDecision,
    "stream_types.RouterDecision": stream_types.RouterDecision,

    "types.RouterInput": types.RouterInput,
    "stream_types.RouterInput": stream_types.RouterInput,

    "types.RouterJudgeInput": types.RouterJudgeInput,
    "stream_types.RouterJudgeInput": stream_types.RouterJudgeInput,

    "types.RouterJudgeOutput": types.RouterJudgeOutput,
    "stream_types.RouterJudgeOutput": stream_types.RouterJudgeOutput,

    "types.SimpleEvaluatorInput": types.SimpleEvaluatorInput,
    "stream_types.SimpleEvaluatorInput": stream_types.SimpleEvaluatorInput,

    "types.SimpleEvaluatorOutput": types.SimpleEvaluatorOutput,
    "stream_types.SimpleEvaluatorOutput": stream_types.SimpleEvaluatorOutput,

    "types.TaskFamily": types.TaskFamily,
    "stream_types.TaskFamily": stream_types.TaskFamily,


    "types.ArtifactKind": types.ArtifactKind,

    "types.ArtifactStatus": types.ArtifactStatus,

    "types.ExpectedBehavior": types.ExpectedBehavior,

    "types.FailureMode": types.FailureMode,

    "types.FunctionalOutcome": types.FunctionalOutcome,

    "types.JudgeVerdict": types.JudgeVerdict,

    "types.ModelClass": types.ModelClass,

    "types.PrimaryIssue": types.PrimaryIssue,

    "types.ReviewPriority": types.ReviewPriority,

    "types.Route": types.Route,

    "types.RouterJudgeVerdict": types.RouterJudgeVerdict,

}