# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
from baml_py import type_builder
from baml_py import baml_py
# These are exports, not used here, hence the linter is disabled
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder # noqa: F401 # pylint: disable=unused-import
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME

class TypeBuilder(type_builder.TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["FunctionalEvaluation","FunctionalEvaluationInput","RouteCapability","RouterDecision","RouterInput","RouterJudgeInput","RouterJudgeOutput","SimpleEvaluatorInput","SimpleEvaluatorOutput","TaskFamily",]
        ), enums=set(
          ["ArtifactKind","ArtifactStatus","ExpectedBehavior","FailureMode","FunctionalOutcome","JudgeVerdict","ModelClass","PrimaryIssue","ReviewPriority","Route","RouterJudgeVerdict",]
        ), runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME)

    # #########################################################################
    # Generated enums 11
    # #########################################################################

    @property
    def ArtifactKind(self) -> "ArtifactKindBuilder":
        return ArtifactKindBuilder(self)

    @property
    def ArtifactStatus(self) -> "ArtifactStatusViewer":
        return ArtifactStatusViewer(self)

    @property
    def ExpectedBehavior(self) -> "ExpectedBehaviorBuilder":
        return ExpectedBehaviorBuilder(self)

    @property
    def FailureMode(self) -> "FailureModeViewer":
        return FailureModeViewer(self)

    @property
    def FunctionalOutcome(self) -> "FunctionalOutcomeViewer":
        return FunctionalOutcomeViewer(self)

    @property
    def JudgeVerdict(self) -> "JudgeVerdictViewer":
        return JudgeVerdictViewer(self)

    @property
    def ModelClass(self) -> "ModelClassViewer":
        return ModelClassViewer(self)

    @property
    def PrimaryIssue(self) -> "PrimaryIssueBuilder":
        return PrimaryIssueBuilder(self)

    @property
    def ReviewPriority(self) -> "ReviewPriorityViewer":
        return ReviewPriorityViewer(self)

    @property
    def Route(self) -> "RouteViewer":
        return RouteViewer(self)

    @property
    def RouterJudgeVerdict(self) -> "RouterJudgeVerdictViewer":
        return RouterJudgeVerdictViewer(self)


    # #########################################################################
    # Generated classes 10
    # #########################################################################

    @property
    def FunctionalEvaluation(self) -> "FunctionalEvaluationViewer":
        return FunctionalEvaluationViewer(self)

    @property
    def FunctionalEvaluationInput(self) -> "FunctionalEvaluationInputViewer":
        return FunctionalEvaluationInputViewer(self)

    @property
    def RouteCapability(self) -> "RouteCapabilityViewer":
        return RouteCapabilityViewer(self)

    @property
    def RouterDecision(self) -> "RouterDecisionViewer":
        return RouterDecisionViewer(self)

    @property
    def RouterInput(self) -> "RouterInputViewer":
        return RouterInputViewer(self)

    @property
    def RouterJudgeInput(self) -> "RouterJudgeInputViewer":
        return RouterJudgeInputViewer(self)

    @property
    def RouterJudgeOutput(self) -> "RouterJudgeOutputViewer":
        return RouterJudgeOutputViewer(self)

    @property
    def SimpleEvaluatorInput(self) -> "SimpleEvaluatorInputViewer":
        return SimpleEvaluatorInputViewer(self)

    @property
    def SimpleEvaluatorOutput(self) -> "SimpleEvaluatorOutputViewer":
        return SimpleEvaluatorOutputViewer(self)

    @property
    def TaskFamily(self) -> "TaskFamilyViewer":
        return TaskFamilyViewer(self)



# #########################################################################
# Generated enums 11
# #########################################################################

class ArtifactKindAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("ArtifactKind")
        self._values: typing.Set[str] = set([  "GEO_XLSX",  "SRA_PACKAGE",  "PRIDE_PACKAGE",  "NFCORE_RNASEQ_CSV",  "NFCORE_SCRNASEQ_CSV",  "SVG_CHART",  "UNKNOWN_FILE",  "NONE_EXPECTED",  ])
        self._vals = ArtifactKindValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "ArtifactKindValues":
        return self._vals


class ArtifactKindBuilder(ArtifactKindAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, baml_py.EnumValueBuilder]]:
        return [(name, self._bldr.value(name)) for name in self._values]

    def add_value(self, name: str) -> baml_py.EnumValueBuilder:
        if name in self._values:
            raise ValueError(f"Value {name} already exists.")
        return self._bldr.value(name)
    

class ArtifactKindValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    def __getattr__(self, name: str) -> baml_py.EnumValueBuilder:
        if name not in self.__values:
            raise AttributeError(f"Value {name} not found.")
        return self.__bldr.value(name)

    
    @property
    def GEO_XLSX(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("GEO_XLSX")
    
    @property
    def SRA_PACKAGE(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("SRA_PACKAGE")
    
    @property
    def PRIDE_PACKAGE(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("PRIDE_PACKAGE")
    
    @property
    def NFCORE_RNASEQ_CSV(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("NFCORE_RNASEQ_CSV")
    
    @property
    def NFCORE_SCRNASEQ_CSV(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("NFCORE_SCRNASEQ_CSV")
    
    @property
    def SVG_CHART(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("SVG_CHART")
    
    @property
    def UNKNOWN_FILE(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("UNKNOWN_FILE")
    
    @property
    def NONE_EXPECTED(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("NONE_EXPECTED")
    
    


class ArtifactStatusAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("ArtifactStatus")
        self._values: typing.Set[str] = set([  "Valid",  "Missing",  "Inaccessible",  "Unreadable",  "SchemaInvalid",  "Incomplete",  "RuntimeFailed",  "PartialAfterFailure",  "Indeterminate",  "NotExpected",  ])
        self._vals = ArtifactStatusValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "ArtifactStatusValues":
        return self._vals


class ArtifactStatusViewer(ArtifactStatusAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class ArtifactStatusValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def Valid(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Valid"))
    
    @property
    def Missing(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Missing"))
    
    @property
    def Inaccessible(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Inaccessible"))
    
    @property
    def Unreadable(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Unreadable"))
    
    @property
    def SchemaInvalid(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SchemaInvalid"))
    
    @property
    def Incomplete(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Incomplete"))
    
    @property
    def RuntimeFailed(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("RuntimeFailed"))
    
    @property
    def PartialAfterFailure(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PartialAfterFailure"))
    
    @property
    def Indeterminate(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Indeterminate"))
    
    @property
    def NotExpected(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("NotExpected"))
    
    


class ExpectedBehaviorAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("ExpectedBehavior")
        self._values: typing.Set[str] = set([  "AnswerDirectly",  "GenerateArtifact",  "ClarifyIfAmbiguous",  "UsePriorContext",  "StateUnsupportedBoundary",  "RefuseUnsafeOnly",  ])
        self._vals = ExpectedBehaviorValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "ExpectedBehaviorValues":
        return self._vals


class ExpectedBehaviorBuilder(ExpectedBehaviorAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, baml_py.EnumValueBuilder]]:
        return [(name, self._bldr.value(name)) for name in self._values]

    def add_value(self, name: str) -> baml_py.EnumValueBuilder:
        if name in self._values:
            raise ValueError(f"Value {name} already exists.")
        return self._bldr.value(name)
    

class ExpectedBehaviorValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    def __getattr__(self, name: str) -> baml_py.EnumValueBuilder:
        if name not in self.__values:
            raise AttributeError(f"Value {name} not found.")
        return self.__bldr.value(name)

    
    @property
    def AnswerDirectly(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("AnswerDirectly")
    
    @property
    def GenerateArtifact(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("GenerateArtifact")
    
    @property
    def ClarifyIfAmbiguous(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("ClarifyIfAmbiguous")
    
    @property
    def UsePriorContext(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("UsePriorContext")
    
    @property
    def StateUnsupportedBoundary(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("StateUnsupportedBoundary")
    
    @property
    def RefuseUnsafeOnly(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("RefuseUnsafeOnly")
    
    


class FailureModeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("FailureMode")
        self._values: typing.Set[str] = set([  "None_",  "Timeout",  "Error",  "NoAnswer",  ])
        self._vals = FailureModeValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "FailureModeValues":
        return self._vals


class FailureModeViewer(FailureModeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class FailureModeValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def None_(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("None_"))
    
    @property
    def Timeout(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Timeout"))
    
    @property
    def Error(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Error"))
    
    @property
    def NoAnswer(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("NoAnswer"))
    
    


class FunctionalOutcomeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("FunctionalOutcome")
        self._values: typing.Set[str] = set([  "FullySatisfied",  "PartiallySatisfied",  "AppropriateClarification",  "AppropriateBoundary",  "NotSatisfied",  "NotAssessable",  ])
        self._vals = FunctionalOutcomeValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "FunctionalOutcomeValues":
        return self._vals


class FunctionalOutcomeViewer(FunctionalOutcomeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class FunctionalOutcomeValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def FullySatisfied(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("FullySatisfied"))
    
    @property
    def PartiallySatisfied(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PartiallySatisfied"))
    
    @property
    def AppropriateClarification(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("AppropriateClarification"))
    
    @property
    def AppropriateBoundary(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("AppropriateBoundary"))
    
    @property
    def NotSatisfied(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("NotSatisfied"))
    
    @property
    def NotAssessable(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("NotAssessable"))
    
    


class JudgeVerdictAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("JudgeVerdict")
        self._values: typing.Set[str] = set([  "Passed",  "Failed",  "Refused",  "Unsupported",  "Fabricated",  "Error",  ])
        self._vals = JudgeVerdictValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "JudgeVerdictValues":
        return self._vals


class JudgeVerdictViewer(JudgeVerdictAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class JudgeVerdictValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def Passed(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Passed"))
    
    @property
    def Failed(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Failed"))
    
    @property
    def Refused(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Refused"))
    
    @property
    def Unsupported(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Unsupported"))
    
    @property
    def Fabricated(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Fabricated"))
    
    @property
    def Error(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Error"))
    
    


class ModelClassAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("ModelClass")
        self._values: typing.Set[str] = set([  "Sonnet",  "Haiku",  "Opus",  ])
        self._vals = ModelClassValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "ModelClassValues":
        return self._vals


class ModelClassViewer(ModelClassAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class ModelClassValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def Sonnet(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Sonnet"))
    
    @property
    def Haiku(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Haiku"))
    
    @property
    def Opus(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Opus"))
    
    


class PrimaryIssueAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("PrimaryIssue")
        self._values: typing.Set[str] = set([  "NoIssue",  "RuntimeFailure",  "Timeout",  "MissingArtifact",  "InvalidArtifact",  "IncompleteArtifact",  "MissingContext",  "AmbiguousRequest",  "OverBroadSearch",  "UpstreamApiError",  "UnsupportedRequest",  "RefusalError",  "OverclaimedSuccess",  "InsufficientEvidence",  "Other",  ])
        self._vals = PrimaryIssueValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "PrimaryIssueValues":
        return self._vals


class PrimaryIssueBuilder(PrimaryIssueAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, baml_py.EnumValueBuilder]]:
        return [(name, self._bldr.value(name)) for name in self._values]

    def add_value(self, name: str) -> baml_py.EnumValueBuilder:
        if name in self._values:
            raise ValueError(f"Value {name} already exists.")
        return self._bldr.value(name)
    

class PrimaryIssueValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    def __getattr__(self, name: str) -> baml_py.EnumValueBuilder:
        if name not in self.__values:
            raise AttributeError(f"Value {name} not found.")
        return self.__bldr.value(name)

    
    @property
    def NoIssue(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("NoIssue")
    
    @property
    def RuntimeFailure(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("RuntimeFailure")
    
    @property
    def Timeout(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("Timeout")
    
    @property
    def MissingArtifact(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("MissingArtifact")
    
    @property
    def InvalidArtifact(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("InvalidArtifact")
    
    @property
    def IncompleteArtifact(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("IncompleteArtifact")
    
    @property
    def MissingContext(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("MissingContext")
    
    @property
    def AmbiguousRequest(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("AmbiguousRequest")
    
    @property
    def OverBroadSearch(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("OverBroadSearch")
    
    @property
    def UpstreamApiError(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("UpstreamApiError")
    
    @property
    def UnsupportedRequest(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("UnsupportedRequest")
    
    @property
    def RefusalError(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("RefusalError")
    
    @property
    def OverclaimedSuccess(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("OverclaimedSuccess")
    
    @property
    def InsufficientEvidence(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("InsufficientEvidence")
    
    @property
    def Other(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("Other")
    
    


class ReviewPriorityAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("ReviewPriority")
        self._values: typing.Set[str] = set([  "Low",  "Medium",  "High",  ])
        self._vals = ReviewPriorityValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "ReviewPriorityValues":
        return self._vals


class ReviewPriorityViewer(ReviewPriorityAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class ReviewPriorityValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def Low(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Low"))
    
    @property
    def Medium(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Medium"))
    
    @property
    def High(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("High"))
    
    


class RouteAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("Route")
        self._values: typing.Set[str] = set([  "NextseekQuery",  "ContainerCC",  ])
        self._vals = RouteValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "RouteValues":
        return self._vals


class RouteViewer(RouteAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class RouteValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def NextseekQuery(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("NextseekQuery"))
    
    @property
    def ContainerCC(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("ContainerCC"))
    
    


class RouterJudgeVerdictAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("RouterJudgeVerdict")
        self._values: typing.Set[str] = set([  "Pass",  "Fail",  "Inconclusive",  ])
        self._vals = RouterJudgeVerdictValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "RouterJudgeVerdictValues":
        return self._vals


class RouterJudgeVerdictViewer(RouterJudgeVerdictAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class RouterJudgeVerdictValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def Pass(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Pass"))
    
    @property
    def Fail(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Fail"))
    
    @property
    def Inconclusive(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("Inconclusive"))
    
    



# #########################################################################
# Generated classes 10
# #########################################################################

class FunctionalEvaluationAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("FunctionalEvaluation")
        self._properties: typing.Set[str] = set([  "outcome",  "usefulness_score",  "primary_issue",  "needs_human_review",  "review_priority",  "rationale",  ])
        self._props = FunctionalEvaluationProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "FunctionalEvaluationProperties":
        return self._props


class FunctionalEvaluationViewer(FunctionalEvaluationAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class FunctionalEvaluationProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def outcome(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("outcome"))
    
    @property
    def usefulness_score(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("usefulness_score"))
    
    @property
    def primary_issue(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("primary_issue"))
    
    @property
    def needs_human_review(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("needs_human_review"))
    
    @property
    def review_priority(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("review_priority"))
    
    @property
    def rationale(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("rationale"))
    
    


class FunctionalEvaluationInputAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("FunctionalEvaluationInput")
        self._properties: typing.Set[str] = set([  "task_family",  "query_text",  "final_answer",  "answer_provided",  "runtime_success",  "failure_mode",  "expected_behavior",  "artifact_expected",  "artifact_status",  "artifact_kind",  "declared_artifact_count",  ])
        self._props = FunctionalEvaluationInputProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "FunctionalEvaluationInputProperties":
        return self._props


class FunctionalEvaluationInputViewer(FunctionalEvaluationInputAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class FunctionalEvaluationInputProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def task_family(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("task_family"))
    
    @property
    def query_text(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("query_text"))
    
    @property
    def final_answer(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("final_answer"))
    
    @property
    def answer_provided(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("answer_provided"))
    
    @property
    def runtime_success(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("runtime_success"))
    
    @property
    def failure_mode(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("failure_mode"))
    
    @property
    def expected_behavior(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("expected_behavior"))
    
    @property
    def artifact_expected(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("artifact_expected"))
    
    @property
    def artifact_status(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("artifact_status"))
    
    @property
    def artifact_kind(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("artifact_kind"))
    
    @property
    def declared_artifact_count(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("declared_artifact_count"))
    
    


class RouteCapabilityAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("RouteCapability")
        self._properties: typing.Set[str] = set([  "route_name",  "description",  "tools",  "best_for",  "not_for",  "task_families",  ])
        self._props = RouteCapabilityProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RouteCapabilityProperties":
        return self._props


class RouteCapabilityViewer(RouteCapabilityAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class RouteCapabilityProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def route_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("route_name"))
    
    @property
    def description(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("description"))
    
    @property
    def tools(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("tools"))
    
    @property
    def best_for(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("best_for"))
    
    @property
    def not_for(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("not_for"))
    
    @property
    def task_families(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("task_families"))
    
    


class RouterDecisionAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("RouterDecision")
        self._properties: typing.Set[str] = set([  "route",  "model_class",  "reasoning",  ])
        self._props = RouterDecisionProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RouterDecisionProperties":
        return self._props


class RouterDecisionViewer(RouterDecisionAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class RouterDecisionProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def route(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("route"))
    
    @property
    def model_class(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("model_class"))
    
    @property
    def reasoning(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("reasoning"))
    
    


class RouterInputAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("RouterInput")
        self._properties: typing.Set[str] = set([  "user_query",  "routes",  ])
        self._props = RouterInputProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RouterInputProperties":
        return self._props


class RouterInputViewer(RouterInputAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class RouterInputProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def user_query(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("user_query"))
    
    @property
    def routes(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("routes"))
    
    


class RouterJudgeInputAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("RouterJudgeInput")
        self._properties: typing.Set[str] = set([  "query_id",  "query_text",  "expected_route",  "actual_route",  "reply_text",  "frames_summary",  ])
        self._props = RouterJudgeInputProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RouterJudgeInputProperties":
        return self._props


class RouterJudgeInputViewer(RouterJudgeInputAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class RouterJudgeInputProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def query_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("query_id"))
    
    @property
    def query_text(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("query_text"))
    
    @property
    def expected_route(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("expected_route"))
    
    @property
    def actual_route(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("actual_route"))
    
    @property
    def reply_text(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("reply_text"))
    
    @property
    def frames_summary(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("frames_summary"))
    
    


class RouterJudgeOutputAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("RouterJudgeOutput")
        self._properties: typing.Set[str] = set([  "verdict",  "reasoning",  ])
        self._props = RouterJudgeOutputProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RouterJudgeOutputProperties":
        return self._props


class RouterJudgeOutputViewer(RouterJudgeOutputAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class RouterJudgeOutputProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def verdict(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("verdict"))
    
    @property
    def reasoning(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("reasoning"))
    
    


class SimpleEvaluatorInputAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("SimpleEvaluatorInput")
        self._properties: typing.Set[str] = set([  "query",  "pass_criteria",  "ui_answer",  ])
        self._props = SimpleEvaluatorInputProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "SimpleEvaluatorInputProperties":
        return self._props


class SimpleEvaluatorInputViewer(SimpleEvaluatorInputAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class SimpleEvaluatorInputProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def query(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("query"))
    
    @property
    def pass_criteria(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("pass_criteria"))
    
    @property
    def ui_answer(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("ui_answer"))
    
    


class SimpleEvaluatorOutputAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("SimpleEvaluatorOutput")
        self._properties: typing.Set[str] = set([  "verdict",  "reasoning",  "model",  ])
        self._props = SimpleEvaluatorOutputProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "SimpleEvaluatorOutputProperties":
        return self._props


class SimpleEvaluatorOutputViewer(SimpleEvaluatorOutputAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class SimpleEvaluatorOutputProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def verdict(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("verdict"))
    
    @property
    def reasoning(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("reasoning"))
    
    @property
    def model(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("model"))
    
    


class TaskFamilyAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("TaskFamily")
        self._properties: typing.Set[str] = set([  "name",  "description",  "example_queries",  ])
        self._props = TaskFamilyProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "TaskFamilyProperties":
        return self._props


class TaskFamilyViewer(TaskFamilyAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class TaskFamilyProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("name"))
    
    @property
    def description(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("description"))
    
    @property
    def example_queries(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("example_queries"))
    
    

