echo "Creating the NExtSEEK database"
mysql -h localhost -u root -p$MYSQL_ROOT_PASSWORD --execute \
"CREATE DATABASE IF NOT EXISTS $NEXTSEEK_MYSQL_DATABASE;
GRANT ALL PRIVILEGES ON $NEXTSEEK_MYSQL_DATABASE.* TO '$MYSQL_USER'@'%';
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%';
GRANT ALL PRIVILEGES ON seek_production.* TO '$MYSQL_USER'@'%';
FLUSH PRIVILEGES;"
